#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TARGET_INPUT="${1:-${ROOT}/../superpowers}"
TARGET_INPUT="$(cd "${TARGET_INPUT}" && pwd)"

LANHU_FRONTEND_AGENT="${TARGET_INPUT}/agents/lanhu-frontend-requirements-analyst.md"
LANHU_BACKEND_AGENT="${TARGET_INPUT}/agents/lanhu-backend-requirements-analyst.md"
LANHU_SKILL="${TARGET_INPUT}/skills/lanhu-requirements/SKILL.md"

for file in "$LANHU_FRONTEND_AGENT" "$LANHU_BACKEND_AGENT" "$LANHU_SKILL"; do
  if [[ ! -f "$file" ]]; then
    printf 'Expected installed Lanhu scoped evidence target: %s\n' "$file" >&2
    exit 1
  fi
done

if [[ -f "${TARGET_INPUT}/agents/lanhu-frontend-html-requirements-analyst.md" ]] && grep -Fq 'Generated by superpower-adapter' "${TARGET_INPUT}/agents/lanhu-frontend-html-requirements-analyst.md"; then
  printf 'Deprecated frontend HTML Lanhu analyst remains installed\n' >&2
  exit 1
fi

require_in_file() {
  local file="$1"
  local text="$2"
  if ! grep -Fq "$text" "$file"; then
    printf 'Expected %s to contain Lanhu scoped evidence text: %s\n' "$file" "$text" >&2
    exit 1
  fi
}

for agent in "$LANHU_FRONTEND_AGENT" "$LANHU_BACKEND_AGENT"; do
  for required in \
    'Allowed Lanhu MCP tools' \
    'lanhu_resolve_invite_link' \
    'lanhu_get_prd_page_scope' \
    'lanhu_get_prd_scoped_evidence' \
    'scope_policy: pageid_children_only' \
    'include_child_pages' \
    'confirmed_child_page_ids' \
    'output_mode: evidence_only' \
    'scopeValidation' \
    'returnedOutOfScopePages' \
    'scopedEvidenceContract' \
    'arbitraryLanhuToolsUsed: false' \
    'deliveryBoundaryPlan' \
    'possibleOverMerge' \
    'possibleOverSplit' \
    'confirmationGate.phase' \
    'targetPage' \
    "selected page's metadata check" \
    'selected target page only' \
    'do not silently fall back to `lanhu_get_pages`' \
    'Do not call any other Lanhu MCP tool' \
    'rootScopeContext' \
    'selectedFromRootTree' \
    'include_child_pages: false' \
    'confirmed_child_page_ids: []' \
    'pagePackageMode' \
    'full_package_per_page' \
    'complete package for the current selected page' \
    'Selective image analysis policy' \
    'must not broaden the allowed Lanhu MCP tool set' \
    'designInfo.images' \
    'output_mode: evidence_only'
  do
    require_in_file "$agent" "$required"
  done
done

for required in \
  'allowedLanhuMcpTools' \
  'lanhu_resolve_invite_link' \
  'lanhu_get_prd_page_scope' \
  'lanhu_get_prd_scoped_evidence' \
  'scopePolicy: pageid_children_only' \
  'scope_policy: pageid_children_only' \
  'include_child_pages' \
  'confirmed_child_page_ids' \
  'output_mode: evidence_only' \
  'scopeValidation.returnedOutOfScopePages == 0' \
  'scopedEvidenceContract.arbitraryLanhuToolsUsed == false' \
  'deliveryBoundaryPlan' \
  'confirmationGate.phase: delivery_boundary' \
  'Do not silently fall back to old broad Lanhu MCP tools' \
  'rootScopeUrl' \
  'rootPageId' \
  'selectedTargetPages' \
  'childPagePolicy: exclude' \
  'include_child_pages: false' \
  'confirmed_child_page_ids: []' \
  'pagePackageMode: true' \
  'aggregationPolicy: full_package_per_page' \
  'fixed Lanhu MCP tool sequence' \
  'selective image analysis policy' \
  'broad Lanhu design tools' \
  'role-prd/prd.md' \
  'role-prd/design/index.html'
do
  require_in_file "$LANHU_SKILL" "$required"
done

printf 'Lanhu scoped evidence smoke OK\n'
