#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TARGET_INPUT="${1:-${ROOT}/../superpowers}"
TARGET_INPUT="$(cd "${TARGET_INPUT}" && pwd)"

if [[ ! -f "${TARGET_INPUT}/agents/spec-researcher.md" ]]; then
  printf 'Expected installed spec-researcher agent\n' >&2
  exit 1
fi

for file in \
  "${TARGET_INPUT}/skills/brainstorming/SKILL.md" \
  "${TARGET_INPUT}/skills/writing-plans/SKILL.md" \
  "${TARGET_INPUT}/skills/executing-plans/SKILL.md" \
  "${TARGET_INPUT}/skills/subagent-driven-development/SKILL.md"
do
  if ! grep -Fq 'Generated by superpower-adapter' "$file"; then
    printf 'Expected adapter native patch marker in %s\n' "$file" >&2
    exit 1
  fi
done

if ! grep -Fq 'spec-researcher' "${TARGET_INPUT}/skills/brainstorming/SKILL.md"; then
  printf 'Expected brainstorming patch to mention spec-researcher\n' >&2
  exit 1
fi

if ! grep -Fq 'spec-researcher' "${TARGET_INPUT}/skills/writing-plans/SKILL.md"; then
  printf 'Expected writing-plans patch to mention spec-researcher\n' >&2
  exit 1
fi

if ! grep -Fq 'Referenced Project Specs' "${TARGET_INPUT}/skills/writing-plans/SKILL.md"; then
  printf 'Expected writing-plans patch to require Referenced Project Specs\n' >&2
  exit 1
fi

if ! grep -Fq 'Referenced Project Specs' "${TARGET_INPUT}/skills/executing-plans/SKILL.md"; then
  printf 'Expected executing-plans patch to consume Referenced Project Specs\n' >&2
  exit 1
fi

if ! grep -Fq 'Referenced Project Specs' "${TARGET_INPUT}/skills/subagent-driven-development/SKILL.md"; then
  printf 'Expected subagent-driven-development patch to forward Referenced Project Specs\n' >&2
  exit 1
fi

if grep -Fq 'spec-progressive-disclosure' "${TARGET_INPUT}/skills/brainstorming/SKILL.md"; then
  printf 'Expected brainstorming patch not to require spec-progressive-disclosure\n' >&2
  exit 1
fi

if grep -Fq 'spec-progressive-disclosure' "${TARGET_INPUT}/skills/writing-plans/SKILL.md"; then
  printf 'Expected writing-plans patch not to require spec-progressive-disclosure\n' >&2
  exit 1
fi

if [[ ! -f "${TARGET_INPUT}/skills/spec-progressive-disclosure/SKILL.md" ]]; then
  printf 'Expected installed spec-progressive-disclosure fallback skill\n' >&2
  exit 1
fi

if ! grep -Eq 'fallback|reference' "${TARGET_INPUT}/skills/spec-progressive-disclosure/SKILL.md"; then
  printf 'Expected spec-progressive-disclosure to be marked as fallback/reference\n' >&2
  exit 1
fi

if [[ ! -f "${TARGET_INPUT}/skills/update-spec/SKILL.md" ]]; then
  printf 'Expected installed update-spec skill\n' >&2
  exit 1
fi

if ! grep -Fq 'durable implementation knowledge' "${TARGET_INPUT}/skills/update-spec/SKILL.md"; then
  printf 'Expected update-spec skill to describe durable knowledge review\n' >&2
  exit 1
fi

if [[ -f "${TARGET_INPUT}/commands/update-spec.md" ]] && grep -Fq 'Generated by superpower-adapter' "${TARGET_INPUT}/commands/update-spec.md"; then
  printf 'Expected deprecated update-spec command overlay to be removed\n' >&2
  exit 1
fi

if grep -Fq 'workflow-gate.py" implement' "${TARGET_INPUT}/skills/executing-plans/SKILL.md"; then
  printf 'Expected executing-plans patch not to require workflow-gate implement\n' >&2
  exit 1
fi

if grep -Fq 'plan-context.py" render --phase implement' "${TARGET_INPUT}/skills/subagent-driven-development/SKILL.md"; then
  printf 'Expected subagent-driven-development patch not to require plan-context render\n' >&2
  exit 1
fi

printf 'native skill patch smoke test complete\n'
