#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TARGET_INPUT="${1:-${ROOT}/../superpowers}"
TARGET_INPUT="$(cd "${TARGET_INPUT}" && pwd)"

USING_SKILL="${TARGET_INPUT}/skills/using-git-worktrees/SKILL.md"
FINISHING_SKILL="${TARGET_INPUT}/skills/finishing-a-development-branch/SKILL.md"

for file in "$USING_SKILL" "$FINISHING_SKILL"; do
  if [[ ! -f "$file" ]]; then
    printf 'Expected native skill file: %s\n' "$file" >&2
    exit 1
  fi
  if ! grep -Fq 'Generated by superpower-adapter' "$file"; then
    printf 'Expected adapter native patch marker in %s\n' "$file" >&2
    exit 1
  fi
done

for required in \
  'worktree-origin.json' \
  'originalBranch' \
  'originalWorktree' \
  'originalHead' \
  'rev-parse --absolute-git-dir'
do
  if ! grep -Fq "$required" "$USING_SKILL"; then
    printf 'Expected using-git-worktrees patch to mention %s\n' "$required" >&2
    exit 1
  fi
done

for required in \
  'Merge back to original branch' \
  'originalWorktree' \
  'worktree-origin.json'
do
  if ! grep -Fq "$required" "$FINISHING_SKILL"; then
    printf 'Expected finishing-a-development-branch patch to mention %s\n' "$required" >&2
    exit 1
  fi
done

if grep -Fq 'write transient metadata into plan.md' "$USING_SKILL" "$FINISHING_SKILL"; then
  printf 'Expected worktree origin metadata not to be written into plan.md\n' >&2
  exit 1
fi

if grep -Fq 'write transient metadata into spec.md' "$USING_SKILL" "$FINISHING_SKILL"; then
  printf 'Expected worktree origin metadata not to be written into spec.md\n' >&2
  exit 1
fi

printf 'native worktree origin patch smoke test complete\n'
