#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TARGET_INPUT="${1:-${ROOT}/../superpowers}"
TARGET_INPUT="$(cd "${TARGET_INPUT}" && pwd)"

if [[ ! -f "${TARGET_INPUT}/agents/wiki-researcher.md" ]]; then
  printf 'Expected installed wiki-researcher agent\n' >&2
  exit 1
fi

if [[ ! -f "${TARGET_INPUT}/agents/lanhu-requirements-analyst.md" ]]; then
  printf 'Expected installed lanhu-requirements-analyst agent\n' >&2
  exit 1
fi

if [[ ! -f "${TARGET_INPUT}/agents/graphify-researcher.md" ]]; then
  printf 'Expected installed graphify-researcher agent\n' >&2
  exit 1
fi

if [[ ! -f "${TARGET_INPUT}/commands/lanhu-requirements.md" ]]; then
  printf 'Expected installed lanhu-requirements command\n' >&2
  exit 1
fi

for file in \
  "${TARGET_INPUT}/skills/brainstorming/SKILL.md" \
  "${TARGET_INPUT}/skills/systematic-debugging/SKILL.md" \
  "${TARGET_INPUT}/skills/writing-plans/SKILL.md" \
  "${TARGET_INPUT}/skills/executing-plans/SKILL.md" \
  "${TARGET_INPUT}/skills/subagent-driven-development/SKILL.md"
do
  if ! grep -Fq 'Generated by superpower-adapter' "$file"; then
    printf 'Expected adapter native patch marker in %s\n' "$file" >&2
    exit 1
  fi
done

BRAINSTORMING_SKILL="${TARGET_INPUT}/skills/brainstorming/SKILL.md"
if ! grep -Fq 'wiki-researcher' "$BRAINSTORMING_SKILL"; then
  printf 'Expected brainstorming patch to mention wiki-researcher\n' >&2
  exit 1
fi

for required in \
  'lanhu-requirements-analyst' \
  '.lanhu/MM-DD-需求命名.md' \
  '.lanhu/MM-DD-父级需求名称/' \
  '<父级需求名称>.md' \
  'index.md' \
  'Lanhu MCP is optional' \
  'do not block brainstorming' \
  'page display' \
  'user operation and interaction rules' \
  'state flow' \
  'business rules' \
  'role-specific PRD bundle' \
  'role: frontend | backend' \
  '前端开发角色视角 PRD' \
  '后端开发角色视角 PRD' \
  'Role PRD acceptance standards' \
  'Given / When / Then' \
  'no-child single-file mode' \
  'tree mode' \
  'test cases' \
  'testing points' \
  'technical test plans' \
  'frontend components' \
  'backend APIs' \
  'database impacts' \
  'file impacts' \
  'explicitPageId' \
  'pageid-tree-gated' \
  'childPagePolicy' \
  'lanhu_get_pages' \
  'lanhu_get_ai_analyze_page_result' \
  'page_names: all' \
  '__AI_INSTRUCTION__' \
  'ai_suggestion' \
  'page-by-page full analysis' \
  'mode: full' \
  'page_names` containing exactly that one page' \
  'one full request for the parent plus descendants' \
  'one combined MCP response to generate multiple PRD files' \
  'raw evidence only' \
  'not the adapter output schema' \
  '## 四、页面展示规则' \
  '### 4.1 页面布局结构草图' \
  '## 六、用户操作与交互规则' \
  '### 6.1 用户操作流程' \
  '### 6.2 交互规则' \
  '本组核心N点' \
  '功能清单表' \
  '字段规则表' \
  'STAGE 4 输出要求' \
  'Every parent and child PRD file must be a complete selected-role PRD' \
  'index.md` is never a substitute' \
  'Mermaid flowchart' \
  'mindmap is allowed only for small/simple structures' \
  'short node labels' \
  'limited depth' \
  'Split dense diagrams' \
  'move details to tables'
do
  if ! grep -Fq "$required" "$BRAINSTORMING_SKILL"; then
    printf 'Expected brainstorming patch to contain optional Lanhu requirement: %s\n' "$required" >&2
    exit 1
  fi
done

WRITING_SKILL="${TARGET_INPUT}/skills/writing-plans/SKILL.md"
if ! grep -Fq 'wiki-researcher' "$WRITING_SKILL"; then
  printf 'Expected writing-plans patch to mention wiki-researcher\n' >&2
  exit 1
fi

for required in \
  'graphify-researcher' \
  'Graphify is optional' \
  'candidate hints' \
  'Every useful hint must be verified against current source' \
  'not graphify alone'
do
  if ! grep -Fq "$required" "$WRITING_SKILL"; then
    printf 'Expected writing-plans patch to contain optional graphify requirement: %s\n' "$required" >&2
    exit 1
  fi
done

SYSTEMATIC_SKILL="${TARGET_INPUT}/skills/systematic-debugging/SKILL.md"
for required in \
  'wiki-researcher' \
  'phase: debug' \
  'maxWikiPages: 2' \
  'Do not call `wiki-researcher` at the start of debugging' \
  'graphify-researcher' \
  'Do not call `graphify-researcher` at the start of debugging' \
  'Phase 1 evidence has narrowed' \
  'candidate-hint research' \
  'not root-cause evidence' \
  'continue systematic debugging' \
  'do not write `.wiki-context.md`' \
  'break-loop'
do
  if ! grep -Fq "$required" "$SYSTEMATIC_SKILL"; then
    printf 'Expected systematic-debugging patch to contain: %s\n' "$required" >&2
    exit 1
  fi
done

if grep -Fq 'planPath:' "$SYSTEMATIC_SKILL"; then
  printf 'Expected systematic-debugging patch not to request a planPath\n' >&2
  exit 1
fi

if grep -Fq 'docs/superpowers/plans/<plan-stem>.wiki-context.md' "$SYSTEMATIC_SKILL"; then
  printf 'Expected systematic-debugging patch not to generate planning wiki context sidecar\n' >&2
  exit 1
fi

if grep -Fq 'Before attempting ANY fix, use wiki-researcher' "$SYSTEMATIC_SKILL"; then
  printf 'Expected systematic-debugging patch not to make wiki-researcher a debugging prerequisite\n' >&2
  exit 1
fi

if ! grep -Fq 'Referenced Project Wiki' "${TARGET_INPUT}/skills/writing-plans/SKILL.md"; then
  printf 'Expected writing-plans patch to require Referenced Project Wiki\n' >&2
  exit 1
fi

if ! grep -Fq '.wiki-context.md' "${TARGET_INPUT}/skills/writing-plans/SKILL.md"; then
  printf 'Expected writing-plans patch to require wiki context sidecar\n' >&2
  exit 1
fi

if ! grep -Fq 'concrete implementation/test/review constraints' "${TARGET_INPUT}/skills/writing-plans/SKILL.md"; then
  printf 'Expected writing-plans patch to require concrete constraints\n' >&2
  exit 1
fi

if ! grep -Fq 'hard constraint status' "${TARGET_INPUT}/skills/writing-plans/SKILL.md"; then
  printf 'Expected writing-plans patch to require hard constraint status\n' >&2
  exit 1
fi

if ! grep -Fq 'Referenced Project Wiki' "${TARGET_INPUT}/skills/executing-plans/SKILL.md"; then
  printf 'Expected executing-plans patch to consume Referenced Project Wiki\n' >&2
  exit 1
fi

if ! grep -Fq '.wiki-context.md' "${TARGET_INPUT}/skills/executing-plans/SKILL.md"; then
  printf 'Expected executing-plans patch to consume wiki context sidecar\n' >&2
  exit 1
fi

if ! grep -Fq 'Do not reselect wiki pages from scratch' "${TARGET_INPUT}/skills/executing-plans/SKILL.md"; then
  printf 'Expected executing-plans patch not to reselect wiki pages\n' >&2
  exit 1
fi

if ! grep -Fq 'Referenced Project Wiki' "${TARGET_INPUT}/skills/subagent-driven-development/SKILL.md"; then
  printf 'Expected subagent-driven-development patch to forward Referenced Project Wiki\n' >&2
  exit 1
fi

if ! grep -Fq '.wiki-context.md' "${TARGET_INPUT}/skills/subagent-driven-development/SKILL.md"; then
  printf 'Expected subagent-driven-development patch to forward wiki context sidecar\n' >&2
  exit 1
fi

if ! grep -Fq 'Do not make subagents reselect wiki pages' "${TARGET_INPUT}/skills/subagent-driven-development/SKILL.md"; then
  printf 'Expected subagent-driven-development patch not to reselect wiki pages\n' >&2
  exit 1
fi

if grep -Fq 'wiki-progressive-disclosure' "${TARGET_INPUT}/skills/brainstorming/SKILL.md"; then
  printf 'Expected brainstorming patch not to require wiki-progressive-disclosure\n' >&2
  exit 1
fi

if grep -Fq 'wiki-progressive-disclosure' "${TARGET_INPUT}/skills/writing-plans/SKILL.md"; then
  printf 'Expected writing-plans patch not to require wiki-progressive-disclosure\n' >&2
  exit 1
fi

if [[ ! -f "${TARGET_INPUT}/skills/wiki-progressive-disclosure/SKILL.md" ]]; then
  printf 'Expected installed wiki-progressive-disclosure fallback skill\n' >&2
  exit 1
fi

if ! grep -Eq 'fallback|reference' "${TARGET_INPUT}/skills/wiki-progressive-disclosure/SKILL.md"; then
  printf 'Expected wiki-progressive-disclosure to be marked as fallback/reference\n' >&2
  exit 1
fi

if [[ ! -f "${TARGET_INPUT}/skills/update-wiki/SKILL.md" ]]; then
  printf 'Expected installed update-wiki skill\n' >&2
  exit 1
fi

if ! grep -Fq 'durable implementation knowledge' "${TARGET_INPUT}/skills/update-wiki/SKILL.md"; then
  printf 'Expected update-wiki skill to describe durable knowledge review\n' >&2
  exit 1
fi

if [[ -f "${TARGET_INPUT}/commands/update-wiki.md" ]] && grep -Fq 'Generated by superpower-adapter' "${TARGET_INPUT}/commands/update-wiki.md"; then
  printf 'Expected deprecated update-wiki command overlay to be removed\n' >&2
  exit 1
fi

if grep -Fq 'workflow-gate.py" implement' "${TARGET_INPUT}/skills/executing-plans/SKILL.md"; then
  printf 'Expected executing-plans patch not to require workflow-gate implement\n' >&2
  exit 1
fi

if grep -Fq 'plan-context.py" render --phase implement' "${TARGET_INPUT}/skills/subagent-driven-development/SKILL.md"; then
  printf 'Expected subagent-driven-development patch not to require plan-context render\n' >&2
  exit 1
fi

if grep -Eq 'must install (lanhu-mcp|graphify)|requires (lanhu-mcp|graphify)|required dependency.*(lanhu-mcp|graphify)' \
  "${TARGET_INPUT}/skills/brainstorming/SKILL.md" \
  "${TARGET_INPUT}/skills/writing-plans/SKILL.md" \
  "${TARGET_INPUT}/skills/systematic-debugging/SKILL.md"; then
  printf 'Expected native patches not to require lanhu-mcp or graphify installation\n' >&2
  exit 1
fi

printf 'native skill patch smoke test complete\n'
