#!/usr/bin/env bash
set -euo pipefail

# Smoke test for the Superpowers minimum-version gate (>= manifest.minSuperpowersVersion, 6.0.0):
#   - resolve_target discovery filters out sub-minimum targets (version_below / _split_by_floor)
#   - install REFUSES a sub-minimum target even when passed explicitly (never writes overlays)
#   - install accepts an in-baseline 6.0.x target WITHOUT crying "newer" (only a newer MAJOR warns)
# Takes an installed Superpowers target to clone (so the fake targets have a real overlay structure).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TARGET_INPUT="${1:-${ROOT}/../superpowers}"
TARGET_INPUT="$(cd "${TARGET_INPUT}" && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

set_version() {
  python3 - "$1" "$2" <<'PY'
from pathlib import Path
import json, sys
path = Path(sys.argv[1]) / 'package.json'
data = json.loads(path.read_text(encoding='utf-8')) if path.is_file() else {}
data['version'] = sys.argv[2]
path.write_text(json.dumps(data, indent=2) + '\n', encoding='utf-8')
PY
}

managed_count() {
  grep -rlF "Generated by superpower-adapter" "$1/scripts" "$1/skills" "$1/agents" "$1/contracts" 2>/dev/null | wc -l | tr -d ' '
}

# --- Part 1: version_below / _split_by_floor unit ---
python3 - <<'PY'
import sys
sys.path.insert(0, "lib")
from adapter_manifest import version_below, min_superpowers_version, parse_version
from pathlib import Path
floor = min_superpowers_version(Path("."))
assert floor == "6.0.0", floor
assert version_below("5.1.0", floor) and version_below("5.0.7", floor)
assert not version_below("6.0.0", floor)
assert not version_below("6.0.2", floor) and not version_below("7.0.0", floor)
assert not version_below("", floor)              # unknown version is never gated out
import resolve_target as rt
compat, below = rt._split_by_floor([
    {"target": "/a", "version": "5.1.0"},
    {"target": "/b", "version": "6.0.2"},
    {"target": "/c", "version": None},
])
assert [e["target"] for e in compat] == ["/b", "/c"], compat
assert [e["target"] for e in below] == ["/a"], below
print("Part 1 (version_below / _split_by_floor) ok")
PY

# --- Part 2: explicit install to a sub-minimum target is REFUSED, writes nothing ---
OLD="$TMP/sp-old"
cp -R "$TARGET_INPUT" "$OLD"
# Start from a clean (unmanaged) clone so a refusal is provable by 0 managed files.
find "$OLD" -type f -exec grep -lF "Generated by superpower-adapter" {} + 2>/dev/null | xargs -r rm -f
set_version "$OLD" "5.9.0"
OUT_OLD="$("${ROOT}/manage.sh" install "$OLD" 2>&1)"
if [[ "$OUT_OLD" != *"Skipping incompatible Superpowers"* ]]; then
  printf 'Expected install to refuse sub-minimum target 5.9.0\n%s\n' "$OUT_OLD" >&2
  exit 1
fi
if [[ "$(managed_count "$OLD")" != "0" ]]; then
  printf 'Expected NO overlays written to refused sub-minimum target (got %s)\n' "$(managed_count "$OLD")" >&2
  exit 1
fi

# --- Part 3: explicit install to an in-baseline 6.0.x target installs WITHOUT a newer warning ---
NEW="$TMP/sp-new"
cp -R "$TARGET_INPUT" "$NEW"
set_version "$NEW" "6.0.9"
OUT_NEW="$("${ROOT}/manage.sh" install "$NEW" 2>&1)"
if [[ "$OUT_NEW" != *"install complete"* ]]; then
  printf 'Expected install to complete on in-baseline 6.0.9\n%s\n' "$OUT_NEW" >&2
  exit 1
fi
if [[ "$OUT_NEW" == *"newer MAJOR"* ]]; then
  printf 'Did NOT expect a newer-version warning for in-baseline 6.0.9\n%s\n' "$OUT_NEW" >&2
  exit 1
fi
if [[ "$(managed_count "$NEW")" == "0" ]]; then
  printf 'Expected overlays written to in-baseline target\n' >&2
  exit 1
fi

printf 'version-gate smoke test complete\n'
