#!/usr/bin/env bash
set -euo pipefail

# Smoke test for wiki section index generation (Phase 3).
# Usage: bash tests/wiki-section-index-smoke.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADAPTER_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCRIPTS="$ADAPTER_ROOT/overlays/scripts"

PASS=0
FAIL=0

assert_contains() {
  local label="$1" needle="$2" haystack="$3"
  if [[ "$haystack" == *"$needle"* ]]; then
    printf '  ✓ %s\n' "$label"
    PASS=$((PASS + 1))
  else
    printf '  ✗ %s (missing: %s)\n' "$label" "$needle"
    FAIL=$((FAIL + 1))
  fi
}

assert_file_exists() {
  local label="$1" path="$2"
  if [[ -f "$path" ]]; then
    printf '  ✓ %s\n' "$label"
    PASS=$((PASS + 1))
  else
    printf '  ✗ %s (not found: %s)\n' "$label" "$path"
    FAIL=$((FAIL + 1))
  fi
}

assert_file_not_exists() {
  local label="$1" path="$2"
  if [[ ! -f "$path" ]]; then
    printf '  ✓ %s\n' "$label"
    PASS=$((PASS + 1))
  else
    printf '  ✗ %s (should not exist: %s)\n' "$label" "$path"
    FAIL=$((FAIL + 1))
  fi
}

# --- Setup temp wiki ---
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

mkdir -p "$TMP/.superpowers/wiki/frontend"

cat > "$TMP/.superpowers/wiki/index.md" << 'WIKI'
# Project Wiki

- [Frontend](frontend/)
WIKI

cat > "$TMP/.superpowers/wiki/frontend/index.md" << 'WIKI'
# Frontend

- [Hook Guidelines](hook-guidelines.md)
- [Short Doc](short-doc.md)
WIKI

cat > "$TMP/.superpowers/wiki/frontend/hook-guidelines.md" << 'WIKI'
# Hook Guidelines

<!-- wiki-section:path-based-update -->
## Path-Based Update

All field updates MUST use updateByPath(path, value).
Direct props.model mutation is forbidden.
<!-- /wiki-section:path-based-update -->

<!-- wiki-section:deep-path -->
## Deep Path Handling

For nested objects, use dot-notation paths.
This is a recommended pattern.
<!-- /wiki-section:deep-path -->
WIKI

cat > "$TMP/.superpowers/wiki/frontend/short-doc.md" << 'WIKI'
# Short Doc

This document has no section markers.
It is too short to need them.
WIKI

# --- Tests ---

printf 'Test: generate index for single file\n'

python3 "$SCRIPTS/wiki_generate_section_index.py" \
  "frontend/hook-guidelines.md" \
  --wiki-root project --project-root "$TMP"

INDEX_PATH="$TMP/.superpowers/wiki/frontend/hook-guidelines.index.md"
assert_file_exists "index file created" "$INDEX_PATH"

INDEX_CONTENT="$(cat "$INDEX_PATH")"
assert_contains "contains section table header" "| section |" "$INDEX_CONTENT"
assert_contains "contains path-based-update" "path-based-update" "$INDEX_CONTENT"
assert_contains "contains deep-path" "deep-path" "$INDEX_CONTENT"
assert_contains "path-based-update is hard" "| path-based-update | Path-Based Update | hard |" "$INDEX_CONTENT"
assert_contains "deep-path is soft" "| deep-path | Deep Path Handling | soft |" "$INDEX_CONTENT"
assert_contains "has auto-generated notice" "Auto-generated" "$INDEX_CONTENT"

printf '\nTest: no index for file without markers\n'

python3 "$SCRIPTS/wiki_generate_section_index.py" \
  "frontend/short-doc.md" \
  --wiki-root project --project-root "$TMP"

SHORT_INDEX="$TMP/.superpowers/wiki/frontend/short-doc.index.md"
assert_file_not_exists "no index for markerless file" "$SHORT_INDEX"

printf '\nTest: --all mode\n'

# Remove previously generated index to test --all
rm -f "$INDEX_PATH"

python3 "$SCRIPTS/wiki_generate_section_index.py" \
  --all --wiki-root project --project-root "$TMP"

assert_file_exists "index regenerated by --all" "$INDEX_PATH"
assert_file_not_exists "still no index for short-doc" "$SHORT_INDEX"

printf '\nTest: idempotent regeneration\n'

FIRST="$(cat "$INDEX_PATH")"
python3 "$SCRIPTS/wiki_generate_section_index.py" \
  "frontend/hook-guidelines.md" \
  --wiki-root project --project-root "$TMP"
SECOND="$(cat "$INDEX_PATH")"

if [[ "$FIRST" == "$SECOND" ]]; then
  printf '  ✓ idempotent\n'
  PASS=$((PASS + 1))
else
  printf '  ✗ idempotent (content changed on re-run)\n'
  FAIL=$((FAIL + 1))
fi

# --- Summary ---
printf '\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n'
printf 'Results: %d passed, %d failed\n' "$PASS" "$FAIL"
if [[ "$FAIL" -gt 0 ]]; then
  exit 1
fi
