#!/usr/bin/env bash
set -euo pipefail

# Smoke test for wiki section index generation (Phase 3).
# Usage: bash tests/wiki-section-index-smoke.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADAPTER_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCRIPTS="$ADAPTER_ROOT/overlays/scripts"

PASS=0
FAIL=0

assert_contains() {
  local label="$1" needle="$2" haystack="$3"
  if [[ "$haystack" == *"$needle"* ]]; then
    printf '  ✓ %s\n' "$label"
    PASS=$((PASS + 1))
  else
    printf '  ✗ %s (missing: %s)\n' "$label" "$needle"
    FAIL=$((FAIL + 1))
  fi
}

assert_not_contains() {
  local label="$1" needle="$2" haystack="$3"
  if [[ "$haystack" != *"$needle"* ]]; then
    printf '  ✓ %s\n' "$label"
    PASS=$((PASS + 1))
  else
    printf '  ✗ %s (unexpected: %s)\n' "$label" "$needle"
    FAIL=$((FAIL + 1))
  fi
}

assert_file_exists() {
  local label="$1" path="$2"
  if [[ -f "$path" ]]; then
    printf '  ✓ %s\n' "$label"
    PASS=$((PASS + 1))
  else
    printf '  ✗ %s (not found: %s)\n' "$label" "$path"
    FAIL=$((FAIL + 1))
  fi
}

assert_file_not_exists() {
  local label="$1" path="$2"
  if [[ ! -f "$path" ]]; then
    printf '  ✓ %s\n' "$label"
    PASS=$((PASS + 1))
  else
    printf '  ✗ %s (should not exist: %s)\n' "$label" "$path"
    FAIL=$((FAIL + 1))
  fi
}

# --- Setup temp wiki ---
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

mkdir -p "$TMP/.superpowers/wiki/frontend"

cat > "$TMP/.superpowers/wiki/index.md" << 'WIKI'
# Project Wiki

- [Frontend](frontend/)
WIKI

cat > "$TMP/.superpowers/wiki/frontend/index.md" << 'WIKI'
# Frontend

- [Hook Guidelines](hook-guidelines.md)
- [Short Doc](short-doc.md)
WIKI

cat > "$TMP/.superpowers/wiki/frontend/hook-guidelines.md" << 'WIKI'
# Hook Guidelines

<!-- wiki-section:path-based-update -->
## Path-Based Update

All field updates MUST use updateByPath(path, value).
Direct props.model mutation is forbidden.
<!-- /wiki-section:path-based-update -->

<!-- wiki-section:deep-path -->
## Deep Path Handling

For nested objects, use dot-notation paths.
This is a recommended pattern.
<!-- /wiki-section:deep-path -->

<!-- wiki-section:summary-demo summary="作者摘要：本节演示 summary 覆盖机械提取" -->
## Summary Demo

VERBOSE_BODY_THAT_SHOULD_NOT_APPEAR in the description because an authored summary wins.
<!-- /wiki-section:summary-demo -->
WIKI

cat > "$TMP/.superpowers/wiki/frontend/short-doc.md" << 'WIKI'
# Short Doc

This document has no section markers.
It is too short to need them.
WIKI

# --- Tests ---

printf 'Test: generate index for single file\n'

python3 "$SCRIPTS/wiki_generate_section_index.py" \
  "frontend/hook-guidelines.md" \
  --wiki-root project --project-root "$TMP"

INDEX_PATH="$TMP/.superpowers/wiki/frontend/hook-guidelines.index.md"
assert_file_exists "index file created" "$INDEX_PATH"

INDEX_CONTENT="$(cat "$INDEX_PATH")"
assert_contains "contains section table header" "| section |" "$INDEX_CONTENT"
assert_contains "contains path-based-update" "path-based-update" "$INDEX_CONTENT"
assert_contains "contains deep-path" "deep-path" "$INDEX_CONTENT"
# Descriptions now fold the section heading plus content gist (heading alone just echoed
# the id); assert the heading prefix, that content was folded in, and the strength.
assert_contains "path-based-update heading prefix" "| path-based-update | Path-Based Update：" "$INDEX_CONTENT"
assert_contains "path-based-update folds content" "updateByPath(path, value)" "$INDEX_CONTENT"
assert_contains "path-based-update is hard" "is forbidden. | hard |" "$INDEX_CONTENT"
assert_contains "deep-path is soft" "recommended pattern. | soft |" "$INDEX_CONTENT"
# Authored summary="…" on the marker overrides the mechanical excerpt.
assert_contains "authored summary used" "| summary-demo | 作者摘要：本节演示 summary 覆盖机械提取 |" "$INDEX_CONTENT"
assert_not_contains "mechanical excerpt suppressed when summary present" "VERBOSE_BODY_THAT_SHOULD_NOT_APPEAR" "$INDEX_CONTENT"
assert_contains "has auto-generated notice" "Auto-generated" "$INDEX_CONTENT"

printf '\nTest: no index for file without markers\n'

python3 "$SCRIPTS/wiki_generate_section_index.py" \
  "frontend/short-doc.md" \
  --wiki-root project --project-root "$TMP"

SHORT_INDEX="$TMP/.superpowers/wiki/frontend/short-doc.index.md"
assert_file_not_exists "no index for markerless file" "$SHORT_INDEX"

printf '\nTest: --all mode\n'

# Remove previously generated index to test --all
rm -f "$INDEX_PATH"

python3 "$SCRIPTS/wiki_generate_section_index.py" \
  --all --wiki-root project --project-root "$TMP"

assert_file_exists "index regenerated by --all" "$INDEX_PATH"
assert_file_not_exists "still no index for short-doc" "$SHORT_INDEX"

printf '\nTest: preserve overview header during regeneration\n'

cat > "$INDEX_PATH" << 'INDEX'
# Sections: frontend/hook-guidelines.md

> Hook guidelines overview should survive table regeneration.

| section | 描述 | 约束强度 |
|---|---|---|
| stale-section | Stale content | soft |
INDEX

python3 "$SCRIPTS/wiki_generate_section_index.py" \
  "frontend/hook-guidelines.md" \
  --wiki-root project --project-root "$TMP"

INDEX_CONTENT="$(cat "$INDEX_PATH")"
assert_contains "preserves overview" "Hook guidelines overview should survive table regeneration" "$INDEX_CONTENT"
assert_contains "regenerates table row" "| path-based-update | Path-Based Update：" "$INDEX_CONTENT"
assert_not_contains "removes stale table row" "stale-section" "$INDEX_CONTENT"

printf '\nTest: idempotent regeneration\n'

FIRST="$(cat "$INDEX_PATH")"
python3 "$SCRIPTS/wiki_generate_section_index.py" \
  "frontend/hook-guidelines.md" \
  --wiki-root project --project-root "$TMP"
SECOND="$(cat "$INDEX_PATH")"

if [[ "$FIRST" == "$SECOND" ]]; then
  printf '  ✓ idempotent\n'
  PASS=$((PASS + 1))
else
  printf '  ✗ idempotent (content changed on re-run)\n'
  FAIL=$((FAIL + 1))
fi

printf '\nTest: aligned (spaced) delimiter table is replaced, not duplicated\n'

# A column-aligned index (pipes padded with spaces) is the format a human or markdown
# formatter may have committed. Regeneration must recognize and REPLACE it — not fail to
# detect the old table and append a second one, leaving two tables in the file.
cat > "$INDEX_PATH" << 'INDEX'
# Sections: frontend/hook-guidelines.md

> Aligned overview should survive regeneration.

| section        | 描述           | 约束强度 |
| -------------- | -------------- | -------- |
| aligned-stale  | Stale aligned  | soft     |
INDEX

python3 "$SCRIPTS/wiki_generate_section_index.py" \
  "frontend/hook-guidelines.md" \
  --wiki-root project --project-root "$TMP"

INDEX_CONTENT="$(cat "$INDEX_PATH")"
assert_contains "preserves aligned overview" "Aligned overview should survive regeneration" "$INDEX_CONTENT"
assert_contains "regenerates real rows" "| path-based-update | Path-Based Update：" "$INDEX_CONTENT"
assert_not_contains "removes aligned stale row" "aligned-stale" "$INDEX_CONTENT"
HEADER_COUNT="$(grep -c '约束强度' "$INDEX_PATH" || true)"
if [[ "$HEADER_COUNT" -eq 1 ]]; then
  printf '  ✓ single section table (no duplicate)\n'
  PASS=$((PASS + 1))
else
  printf '  ✗ single section table (found %s table header rows)\n' "$HEADER_COUNT"
  FAIL=$((FAIL + 1))
fi

printf '\nTest: project-root-relative path with wiki prefix resolves (no double-prefix)\n'

rm -f "$INDEX_PATH"
# The path a user copies is usually project-root-relative and already carries the
# .superpowers/wiki/ prefix; joining it onto the wiki root double-prefixed it into
# .superpowers/wiki/.superpowers/wiki/… → "file not found". It must now resolve.
python3 "$SCRIPTS/wiki_generate_section_index.py" \
  ".superpowers/wiki/frontend/hook-guidelines.md" \
  --wiki-root project --project-root "$TMP"
assert_file_exists "prefixed project-relative path resolved" "$INDEX_PATH"

# --- Summary ---
printf '\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n'
printf 'Results: %d passed, %d failed\n' "$PASS" "$FAIL"
if [[ "$FAIL" -gt 0 ]]; then
  exit 1
fi
