#!/usr/bin/env python3
"""Shared manifest helpers for superpower-adapter."""

from __future__ import annotations

import json
from pathlib import Path


def load_manifest(script_dir: Path) -> dict:
    path = script_dir / 'manifest.json'
    return json.loads(path.read_text(encoding='utf-8'))


def installed_paths(script_dir: Path) -> list[str]:
    manifest = load_manifest(script_dir)
    return list(manifest.get('installedPaths', []))


def generated_marker(script_dir: Path) -> str:
    manifest = load_manifest(script_dir)
    return str(manifest.get('generatedMarker', 'Generated by superpower-adapter'))


def removed_paths(script_dir: Path) -> list[str]:
    manifest = load_manifest(script_dir)
    return list(manifest.get('removedPaths', []))
