#!/usr/bin/env python3
"""Patch or verify Superpowers native skills for superpower-adapter wiki disclosure."""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

START_PREFIX = '<!-- superpower-adapter:native-skill:'
END_PREFIX = '<!-- /superpower-adapter:native-skill:'


@dataclass(frozen=True)
class PatchSpec:
    skill: str
    anchor: str
    block_id: str
    content: str
    legacy_block_ids: tuple[str, ...] = ()

    @property
    def relative_path(self) -> Path:
        return Path('skills') / self.skill / 'SKILL.md'

    @property
    def start_marker(self) -> str:
        return f'{START_PREFIX}{self.block_id} -->'

    @property
    def end_marker(self) -> str:
        return f'{END_PREFIX}{self.block_id} -->'

    def rendered_block(self, target: Path) -> str:
        plugin_root = target.as_posix()
        body = self.content.replace('__SUPERPOWER_ADAPTER_PLUGIN_ROOT__', plugin_root)
        return f'{self.start_marker}\n{body.rstrip()}\n{self.end_marker}\n'


PATCHES = [
    PatchSpec(
        skill='brainstorming',
        anchor='## The Process\n',
        block_id='brainstorming-wiki-disclosure',
        legacy_block_ids=('brainstorming-spec-disclosure',),
        content='''\n## Adapter Project Wiki Disclosure\n\nGenerated by superpower-adapter.\n\nAfter exploring project context and before proposing approaches, use the `wiki-researcher` agent to select a small amount of relevant project wiki context from `.superpowers/wiki/`:\n\n```yaml\ntask: <user request and current understanding>\nphase: brainstorm\nwikiRoot: .superpowers/wiki\nfocus: <module, workflow, or concern if known>\nmaxWikiPages: 3\n```\n\nUse the result as lightweight `Adapter Project Wiki Context` while designing the Superpowers spec. Do not block brainstorming if there is no matching wiki page or `.superpowers/wiki/index.md` is missing; mention the caveat and continue. Do not write sidecar JSONL during brainstorming.\n''',
    ),
    PatchSpec(
        skill='writing-plans',
        anchor='## File Structure\n',
        block_id='writing-plans-planning-gate',
        content='''\n## Adapter Referenced Project Wiki\n\nGenerated by superpower-adapter.\n\nBefore decomposing tasks, use the `wiki-researcher` agent to formally select the existing project wiki pages that constrain this implementation plan:\n\n```yaml\ntask: <confirmed Superpowers spec or requirements summary>\nphase: plan\nwikiRoot: .superpowers/wiki\nplanPath: docs/superpowers/plans/<filename>.md\nplanSummary: <plan goal and likely task areas>\nmaxWikiPages: 5\n```\n\nThe plan must include a `## Referenced Project Wiki` section. For each selected `.superpowers/wiki/` file, list the tasks it applies to and the concrete constraints the implementer and reviewer must follow. Read the necessary full text for selected wiki pages marked `readMode: full` before writing those constraints. If a selected project wiki conflicts with the confirmed Superpowers spec, stop and ask the user to resolve the conflict before writing the plan.\n''',
    ),
    PatchSpec(
        skill='executing-plans',
        anchor='### Step 2: Execute Tasks\n',
        block_id='executing-plans-implement-gate',
        content='''\n### Adapter Referenced Project Wiki\n\nGenerated by superpower-adapter.\n\nBefore touching code, read the plan's `Referenced Project Wiki` section and use those constraints as the selected project wiki context for implementation. Do not reselect wiki pages from scratch during execution, and do not require adapter sidecar JSONL or workflow gates as implementation preconditions.\n\nIf the plan does not contain `Referenced Project Wiki`, pause and ask whether to return to the planning step to add the missing project wiki references instead of inventing execution-time constraints.\n\nAfter completing implementation, use the `update-wiki` skill to review whether the work produced durable implementation knowledge that should be persisted to `.superpowers/wiki/`. Do not force a spec edit when there is nothing durable to record.\n''',
    ),
    PatchSpec(
        skill='subagent-driven-development',
        anchor='## The Process\n',
        block_id='subagent-driven-development-implement-gate',
        content='''\n## Adapter Referenced Project Wiki\n\nGenerated by superpower-adapter.\n\nWhen reading the implementation plan, extract its `Referenced Project Wiki` section and include those constraints in every implementer and reviewer subagent prompt. Treat the plan's referenced wiki pages as the selected project wiki context. Do not make subagents reselect wiki pages from `.superpowers/wiki/` unless the main agent explicitly determines that the plan's references are clearly insufficient.\n\nIf the plan has no `Referenced Project Wiki` section, pause and ask whether the plan should be updated before dispatching implementation subagents.\n\nAfter implementation and review, the main agent should use the `update-wiki` skill to decide whether any durable implementation knowledge should be persisted to `.superpowers/wiki/`. Subagents should not write wiki updates unless explicitly instructed.\n''',
    ),
]


def load_text(path: Path) -> str:
    return path.read_text(encoding='utf-8')


def save_text(path: Path, text: str) -> None:
    path.write_text(text, encoding='utf-8')


def strip_block_by_id(text: str, skill: str, block_id: str) -> tuple[str, bool]:
    start_marker = f'{START_PREFIX}{block_id} -->'
    end_marker = f'{END_PREFIX}{block_id} -->'
    start = text.find(start_marker)
    if start == -1:
        return text, False
    end = text.find(end_marker, start)
    if end == -1:
        raise SystemExit(f'Malformed adapter native skill patch: missing end marker for {skill}')
    end += len(end_marker)
    if end < len(text) and text[end:end + 1] == '\n':
        end += 1
    if start > 0 and text[start - 1:start] == '\n':
        start -= 1
    return text[:start] + text[end:], True


def strip_block(text: str, spec: PatchSpec) -> tuple[str, bool]:
    removed_any = False
    for block_id in (*spec.legacy_block_ids, spec.block_id):
        text, removed = strip_block_by_id(text, spec.skill, block_id)
        removed_any = removed_any or removed
    return text, removed_any


def apply_patch(path: Path, spec: PatchSpec, target: Path) -> bool:
    text = load_text(path)
    text, removed = strip_block(text, spec)
    anchor_index = text.find(spec.anchor)
    if anchor_index == -1:
        raise SystemExit(f'Missing anchor in {path}: {spec.anchor.strip()}')
    insert_at = anchor_index + len(spec.anchor)
    block = '\n' + spec.rendered_block(target) + '\n'
    updated = text[:insert_at] + block + text[insert_at:]
    if updated != load_text(path):
        save_text(path, updated)
        return True
    return removed


def remove_patch(path: Path, spec: PatchSpec) -> bool:
    text = load_text(path)
    updated, removed = strip_block(text, spec)
    if removed:
        save_text(path, updated)
    return removed


def verify_patch(path: Path, spec: PatchSpec, target: Path) -> None:
    text = load_text(path)
    expected = spec.rendered_block(target).rstrip()
    if expected not in text:
        raise SystemExit(f'Missing adapter native skill patch in {path}: {spec.block_id}')


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit('Usage: native_skill_patch.py <install|uninstall|verify> <superpowers-dir>')

    mode = sys.argv[1]
    target = Path(sys.argv[2]).resolve()
    if mode not in {'install', 'uninstall', 'verify'}:
        raise SystemExit(f'Unsupported mode: {mode}')

    changed = False
    for spec in PATCHES:
        path = target / spec.relative_path
        if not path.is_file():
            raise SystemExit(f'Missing Superpowers native skill: {path}')
        if mode == 'install':
            changed |= apply_patch(path, spec, target)
        elif mode == 'uninstall':
            changed |= remove_patch(path, spec)
        else:
            verify_patch(path, spec, target)

    if mode == 'verify':
        print('Native skill patches OK')
    elif changed:
        print(f'Native skill patches updated via {mode}')
    else:
        print(f'Native skill patches already satisfied for {mode}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
