#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

from spec_common import build_spec_index_graph, repo_root, summary_from_markdown

MAX_SCAN_RESULTS = 400
MAX_FILE_SAMPLES = 12
MAX_INITIALIZED_LEAVES = 5

EXTENSION_GROUPS: dict[str, set[str]] = {
    "python": {".py"},
    "typescript": {".ts", ".tsx", ".mts", ".cts"},
    "javascript": {".js", ".jsx", ".mjs", ".cjs"},
    "go": {".go"},
    "rust": {".rs"},
    "java": {".java"},
    "kotlin": {".kt", ".kts"},
    "swift": {".swift"},
    "ruby": {".rb"},
    "php": {".php"},
}

STACK_HINTS = {
    "react", "vue", "svelte", "next", "nuxt", "vite", "tailwind", "ui",
    "express", "fastapi", "django", "flask", "nestjs", "koa", "api", "server",
    "prisma", "postgres", "mysql", "sqlite", "mongodb", "redis", "database",
}


def run_find(project_root: Path) -> list[Path]:
    command = [
        "find", str(project_root), "-type", "f", "(",
        "-name", "*.py", "-o", "-name", "*.ts", "-o", "-name", "*.tsx", "-o",
        "-name", "*.js", "-o", "-name", "*.jsx", "-o", "-name", "*.go", "-o",
        "-name", "*.rs", "-o", "-name", "*.java", "-o", "-name", "*.kt", "-o",
        "-name", "*.swift", "-o", "-name", "*.rb", "-o", "-name", "*.php",
        ")", "-not", "-path", "*/node_modules/*", "-not", "-path", "*/.git/*",
        "-not", "-path", "*/dist/*", "-not", "-path", "*/build/*", "-not", "-path", "*/coverage/*",
        "-not", "-path", "*/.next/*", "-not", "-path", "*/target/*", "-print",
    ]
    result = subprocess.run(command, capture_output=True, text=True, check=True)
    paths = [Path(line.strip()) for line in result.stdout.splitlines() if line.strip()]
    return paths[:MAX_SCAN_RESULTS]


def read_package_json(project_root: Path) -> dict:
    package_json = project_root / "package.json"
    if not package_json.is_file():
        return {}
    try:
        return json.loads(package_json.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def detect_languages(files: list[Path]) -> list[str]:
    counts: Counter[str] = Counter()
    for path in files:
        for language, suffixes in EXTENSION_GROUPS.items():
            if path.suffix.lower() in suffixes:
                counts[language] += 1
                break
    return [name for name, _ in counts.most_common(3)]


def detect_stack(package_json: dict, languages: list[str]) -> set[str]:
    deps = {
        *(package_json.get("dependencies") or {}).keys(),
        *(package_json.get("devDependencies") or {}).keys(),
    }
    lowered = {dep.lower() for dep in deps}
    stack = set(languages)
    stack.update(sorted(word for word in lowered if word in STACK_HINTS))
    return stack


def dominant_directories(files: list[Path], project_root: Path) -> list[str]:
    counts: Counter[str] = Counter()
    for path in files:
        try:
            rel = path.relative_to(project_root)
        except ValueError:
            continue
        parts = rel.parts
        if len(parts) > 1:
            counts[parts[0]] += 1
    return [name for name, _ in counts.most_common(5)]


def file_samples(files: list[Path], project_root: Path) -> list[str]:
    samples: list[str] = []
    for path in files[:MAX_FILE_SAMPLES]:
        try:
            samples.append(path.relative_to(project_root).as_posix())
        except ValueError:
            continue
    return samples


def append_initialization_block(path: Path, title: str, why: list[str], rules: list[str], notes: list[str] | None = None) -> None:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    marker = f"## Update: {title}"
    if marker in existing:
        return

    lines = [existing.rstrip(), "", marker, "", "### Why"]
    lines.extend(f"- {item}" for item in why)
    lines.extend(["", "### Rules / Contracts"])
    lines.extend(f"- {item}" for item in rules)
    if notes:
        lines.extend(["", "### Validation / Notes"])
        lines.extend(f"- {item}" for item in notes)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def initialize_project_entry(path: Path, hint: str, languages: list[str], stack: set[str], top_dirs: list[str], samples: list[str]) -> None:
    why = [
        "This file was initialized from the current repository shape so the first spec pass starts from observed project reality.",
        "Treat these notes as a starting point for user review rather than an authoritative design document.",
    ]
    rules: list[str] = []
    if hint:
        rules.append(f"Focus hint: {hint}")
    if languages:
        rules.append(f"Primary implementation languages: {', '.join(languages)}")
    if stack:
        rules.append(f"Detected stack signals: {', '.join(sorted(stack))}")
    if top_dirs:
        rules.append(f"Top-level code directories worth reviewing first: {', '.join(top_dirs)}")
    if samples:
        rules.append(f"Example implementation files: {', '.join(samples)}")
    notes = [
        "This command initializes spec content for the user; during ongoing development, continue maintaining knowledge with update-spec.",
        "Replace any incorrect assumptions after reading the relevant code or after user confirmation.",
    ]
    append_initialization_block(path, "Initialization Summary", why, rules, notes)


def tokenize(value: str) -> list[str]:
    return [token for token in re.split(r"[^a-z0-9]+", value.lower()) if token]


def score_leaf(path: Path, spec_root: Path, hint: str, stack: set[str]) -> float:
    rel = path.relative_to(spec_root).as_posix().lower()
    summary = summary_from_markdown(path).lower()
    tokens = [*tokenize(hint), *sorted(stack)]
    score = 0.0
    for token in tokens:
        if token and token in rel:
            score += 3
        if token and token in summary:
            score += 2
    return score


def initialize_leaf(path: Path, spec_root: Path, languages: list[str], stack: set[str], top_dirs: list[str], samples: list[str]) -> None:
    rel = path.relative_to(spec_root).as_posix()
    why = [
        f"This indexed spec file was selected during initialization because it is reachable from the spec index graph: {rel}.",
        "The initial pass should capture observable project signals only, not unverified implementation contracts.",
    ]
    rules = [
        *( [f"Primary implementation languages: {', '.join(languages)}"] if languages else []),
        *( [f"Detected stack signals: {', '.join(sorted(stack))}"] if stack else []),
        *( [f"Candidate code directories to inspect first: {', '.join(top_dirs[:3])}"] if top_dirs else []),
        *( [f"Candidate files to inspect first: {', '.join(samples[:5])}"] if samples else []),
        "Confirm concrete behavior in code or docs before turning these observations into durable rules.",
    ]
    append_initialization_block(
        path,
        "Initialization Summary",
        why,
        rules,
        ["Use update-spec to capture verified durable knowledge after implementation or review."],
    )


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: init-spec.py <project-root> [analysis-hint]", file=sys.stderr)
        return 1

    project_root = repo_root(Path(sys.argv[1]).resolve())
    hint = sys.argv[2].strip() if len(sys.argv) > 2 else ""
    spec_root = project_root / ".superpowers" / "spec"
    spec_root.mkdir(parents=True, exist_ok=True)

    files = run_find(project_root)
    package_json = read_package_json(project_root)
    languages = detect_languages(files)
    stack = detect_stack(package_json, languages)
    top_dirs = dominant_directories(files, project_root)
    samples = file_samples(files, project_root)

    root_index = spec_root / "index.md"
    if root_index.is_file():
        initialize_project_entry(root_index, hint, languages, stack, top_dirs, samples)

    graph = build_spec_index_graph(spec_root)
    leaves = sorted(graph.leaves, key=lambda path: (-score_leaf(path, spec_root, hint, stack), path.relative_to(spec_root).as_posix()))
    for leaf in leaves[:MAX_INITIALIZED_LEAVES]:
        initialize_leaf(leaf, spec_root, languages, stack, top_dirs, samples)

    update_script = Path(__file__).with_name("update-spec.py")
    subprocess.run([sys.executable, str(update_script)], cwd=project_root, check=True)

    if leaves:
        print(f"Initialized spec content under {spec_root}")
    else:
        print(f"Initialized root spec index under {spec_root}; add leaf specs to index.md for deeper initialization")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
