#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from wiki_common import build_wiki_index_graph, rel_posix, repo_root, summary_from_markdown

MAX_SCAN_RESULTS = 400
MAX_FILE_SAMPLES = 12

EXTENSION_GROUPS: dict[str, set[str]] = {
    "python": {".py"},
    "typescript": {".ts", ".tsx", ".mts", ".cts"},
    "javascript": {".js", ".jsx", ".mjs", ".cjs"},
    "go": {".go"},
    "rust": {".rs"},
    "java": {".java"},
    "kotlin": {".kt", ".kts"},
    "swift": {".swift"},
    "ruby": {".rb"},
    "php": {".php"},
}

STACK_HINTS = {
    "react", "vue", "svelte", "next", "nuxt", "vite", "tailwind", "ui",
    "express", "fastapi", "django", "flask", "nestjs", "koa", "api", "server",
    "prisma", "postgres", "mysql", "sqlite", "mongodb", "redis", "database",
}


def run_find(project_root: Path) -> list[Path]:
    ignored_directories = {"node_modules", ".git", "dist", "build", "coverage", ".next", "target"}
    suffixes = {suffix for group in EXTENSION_GROUPS.values() for suffix in group}
    paths: list[Path] = []
    for path in sorted(project_root.rglob("*")):
        relative = path.relative_to(project_root)
        if any(part in ignored_directories for part in relative.parts):
            continue
        if path.is_file() and path.suffix.lower() in suffixes:
            paths.append(path)
            if len(paths) >= MAX_SCAN_RESULTS:
                break
    return paths


def read_package_json(project_root: Path) -> dict:
    package_json = project_root / "package.json"
    if not package_json.is_file():
        return {}
    try:
        return json.loads(package_json.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def detect_languages(files: list[Path]) -> list[str]:
    counts: Counter[str] = Counter()
    for path in files:
        for language, suffixes in EXTENSION_GROUPS.items():
            if path.suffix.lower() in suffixes:
                counts[language] += 1
                break
    return [name for name, _ in counts.most_common(3)]


def detect_stack(package_json: dict, languages: list[str]) -> list[str]:
    deps = {
        *(package_json.get("dependencies") or {}).keys(),
        *(package_json.get("devDependencies") or {}).keys(),
    }
    lowered = {dep.lower() for dep in deps}
    stack = set(languages)
    stack.update(word for word in lowered if word in STACK_HINTS)
    return sorted(stack)


def dominant_directories(files: list[Path], project_root: Path) -> list[str]:
    counts: Counter[str] = Counter()
    for path in files:
        try:
            rel = path.relative_to(project_root)
        except ValueError:
            continue
        parts = rel.parts
        if len(parts) > 1:
            counts[parts[0]] += 1
    return [name for name, _ in counts.most_common(5)]


def file_samples(files: list[Path], project_root: Path) -> list[str]:
    samples: list[str] = []
    for path in files[:MAX_FILE_SAMPLES]:
        try:
            samples.append(path.relative_to(project_root).as_posix())
        except ValueError:
            continue
    return samples


def indexed_wiki_pages(wiki_root: Path) -> tuple[list[dict[str, str]], list[str]]:
    graph = build_wiki_index_graph(wiki_root)
    wiki_pages = [
        {
            "path": rel_posix(wiki_root.resolve(), path),
            "summary": summary_from_markdown(path),
            "kind": "leaf",
        }
        for path in graph.leaves
    ]
    return wiki_pages, graph.warnings


def build_inventory(project_root_arg: str, hint: str) -> dict:
    project_root = repo_root(Path(project_root_arg).resolve())
    wiki_root = project_root / ".superpowers" / "wiki"
    files = run_find(project_root)
    package_json = read_package_json(project_root)
    languages = detect_languages(files)
    stack = detect_stack(package_json, languages)
    wiki_pages, warnings = indexed_wiki_pages(wiki_root)

    if not (wiki_root / "index.md").is_file():
        warnings.append("Missing .superpowers/wiki/index.md; run bootstrap-wiki before initializing starter wiki pages")

    return {
        "projectRoot": str(project_root),
        "wikiRoot": str(wiki_root),
        "focusHint": hint,
        "languages": languages,
        "stackSignals": stack,
        "topDirectories": dominant_directories(files, project_root),
        "sampleFiles": file_samples(files, project_root),
        "indexedWikiPages": wiki_pages,
        "warnings": warnings,
        "mechanicalOnly": True,
    }


def render_text(inventory: dict) -> str:
    lines = [
        "Project inventory only; no wiki content was written.",
        f"Project root: {inventory['projectRoot']}",
        f"Wiki root: {inventory['wikiRoot']}",
    ]
    if inventory["focusHint"]:
        lines.append(f"Focus hint: {inventory['focusHint']}")
    lines.extend([
        "",
        "Languages: " + (", ".join(inventory["languages"]) or "<none detected>"),
        "Stack signals: " + (", ".join(inventory["stackSignals"]) or "<none detected>"),
        "Top directories: " + (", ".join(inventory["topDirectories"]) or "<none detected>"),
        "",
        "Sample files:",
    ])
    lines.extend(f"- {path}" for path in inventory["sampleFiles"] or ["<none>"])
    lines.extend(["", "Indexed wiki pages:"])
    if inventory["indexedWikiPages"]:
        for wiki_page in inventory["indexedWikiPages"]:
            summary = f" — {wiki_page['summary']}" if wiki_page["summary"] else ""
            lines.append(f"- `{wiki_page['path']}`{summary}")
    else:
        lines.append("- <none>")
    if inventory["warnings"]:
        lines.extend(["", "Warnings:"])
        lines.extend(f"- {warning}" for warning in inventory["warnings"])
    return "\n".join(lines)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Output project inventory for agent-led .superpowers/wiki initialization.")
    parser.add_argument("project_root", help="Project root to inspect")
    parser.add_argument("analysis_hint", nargs="?", default="", help="Optional focus hint for the agent")
    parser.add_argument("--json", action="store_true", help="Emit JSON inventory")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    inventory = build_inventory(args.project_root, args.analysis_hint.strip())
    if args.json:
        print(json.dumps(inventory, ensure_ascii=False, indent=2))
    else:
        print(render_text(inventory))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
