#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json
import subprocess
from collections import Counter
from pathlib import Path

from spec_common import build_spec_index_graph, rel_posix, repo_root, summary_from_markdown

MAX_SCAN_RESULTS = 400
MAX_FILE_SAMPLES = 12

EXTENSION_GROUPS: dict[str, set[str]] = {
    "python": {".py"},
    "typescript": {".ts", ".tsx", ".mts", ".cts"},
    "javascript": {".js", ".jsx", ".mjs", ".cjs"},
    "go": {".go"},
    "rust": {".rs"},
    "java": {".java"},
    "kotlin": {".kt", ".kts"},
    "swift": {".swift"},
    "ruby": {".rb"},
    "php": {".php"},
}

STACK_HINTS = {
    "react", "vue", "svelte", "next", "nuxt", "vite", "tailwind", "ui",
    "express", "fastapi", "django", "flask", "nestjs", "koa", "api", "server",
    "prisma", "postgres", "mysql", "sqlite", "mongodb", "redis", "database",
}


def run_find(project_root: Path) -> list[Path]:
    command = [
        "find", str(project_root), "-type", "f", "(",
        "-name", "*.py", "-o", "-name", "*.ts", "-o", "-name", "*.tsx", "-o",
        "-name", "*.js", "-o", "-name", "*.jsx", "-o", "-name", "*.go", "-o",
        "-name", "*.rs", "-o", "-name", "*.java", "-o", "-name", "*.kt", "-o",
        "-name", "*.swift", "-o", "-name", "*.rb", "-o", "-name", "*.php",
        ")", "-not", "-path", "*/node_modules/*", "-not", "-path", "*/.git/*",
        "-not", "-path", "*/dist/*", "-not", "-path", "*/build/*", "-not", "-path", "*/coverage/*",
        "-not", "-path", "*/.next/*", "-not", "-path", "*/target/*", "-print",
    ]
    result = subprocess.run(command, capture_output=True, text=True, check=True)
    paths = [Path(line.strip()) for line in result.stdout.splitlines() if line.strip()]
    return paths[:MAX_SCAN_RESULTS]


def read_package_json(project_root: Path) -> dict:
    package_json = project_root / "package.json"
    if not package_json.is_file():
        return {}
    try:
        return json.loads(package_json.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def detect_languages(files: list[Path]) -> list[str]:
    counts: Counter[str] = Counter()
    for path in files:
        for language, suffixes in EXTENSION_GROUPS.items():
            if path.suffix.lower() in suffixes:
                counts[language] += 1
                break
    return [name for name, _ in counts.most_common(3)]


def detect_stack(package_json: dict, languages: list[str]) -> list[str]:
    deps = {
        *(package_json.get("dependencies") or {}).keys(),
        *(package_json.get("devDependencies") or {}).keys(),
    }
    lowered = {dep.lower() for dep in deps}
    stack = set(languages)
    stack.update(word for word in lowered if word in STACK_HINTS)
    return sorted(stack)


def dominant_directories(files: list[Path], project_root: Path) -> list[str]:
    counts: Counter[str] = Counter()
    for path in files:
        try:
            rel = path.relative_to(project_root)
        except ValueError:
            continue
        parts = rel.parts
        if len(parts) > 1:
            counts[parts[0]] += 1
    return [name for name, _ in counts.most_common(5)]


def file_samples(files: list[Path], project_root: Path) -> list[str]:
    samples: list[str] = []
    for path in files[:MAX_FILE_SAMPLES]:
        try:
            samples.append(path.relative_to(project_root).as_posix())
        except ValueError:
            continue
    return samples


def indexed_specs(spec_root: Path) -> tuple[list[dict[str, str]], list[str]]:
    graph = build_spec_index_graph(spec_root)
    specs = [
        {
            "path": rel_posix(spec_root.resolve(), path),
            "summary": summary_from_markdown(path),
            "kind": "leaf",
        }
        for path in graph.leaves
    ]
    return specs, graph.warnings


def build_inventory(project_root_arg: str, hint: str) -> dict:
    project_root = repo_root(Path(project_root_arg).resolve())
    spec_root = project_root / ".superpowers" / "spec"
    files = run_find(project_root)
    package_json = read_package_json(project_root)
    languages = detect_languages(files)
    stack = detect_stack(package_json, languages)
    specs, warnings = indexed_specs(spec_root)

    if not (spec_root / "index.md").is_file():
        warnings.append("Missing .superpowers/spec/index.md; run bootstrap-spec before initializing starter specs")

    return {
        "projectRoot": str(project_root),
        "specRoot": str(spec_root),
        "focusHint": hint,
        "languages": languages,
        "stackSignals": stack,
        "topDirectories": dominant_directories(files, project_root),
        "sampleFiles": file_samples(files, project_root),
        "indexedSpecs": specs,
        "warnings": warnings,
        "mechanicalOnly": True,
    }


def render_text(inventory: dict) -> str:
    lines = [
        "Project inventory only; no spec content was written.",
        f"Project root: {inventory['projectRoot']}",
        f"Spec root: {inventory['specRoot']}",
    ]
    if inventory["focusHint"]:
        lines.append(f"Focus hint: {inventory['focusHint']}")
    lines.extend([
        "",
        "Languages: " + (", ".join(inventory["languages"]) or "<none detected>"),
        "Stack signals: " + (", ".join(inventory["stackSignals"]) or "<none detected>"),
        "Top directories: " + (", ".join(inventory["topDirectories"]) or "<none detected>"),
        "",
        "Sample files:",
    ])
    lines.extend(f"- {path}" for path in inventory["sampleFiles"] or ["<none>"])
    lines.extend(["", "Indexed specs:"])
    if inventory["indexedSpecs"]:
        for spec in inventory["indexedSpecs"]:
            summary = f" — {spec['summary']}" if spec["summary"] else ""
            lines.append(f"- `{spec['path']}`{summary}")
    else:
        lines.append("- <none>")
    if inventory["warnings"]:
        lines.extend(["", "Warnings:"])
        lines.extend(f"- {warning}" for warning in inventory["warnings"])
    return "\n".join(lines)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Output project inventory for agent-led .superpowers/spec initialization.")
    parser.add_argument("project_root", help="Project root to inspect")
    parser.add_argument("analysis_hint", nargs="?", default="", help="Optional focus hint for the agent")
    parser.add_argument("--json", action="store_true", help="Emit JSON inventory")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    inventory = build_inventory(args.project_root, args.analysis_hint.strip())
    if args.json:
        print(json.dumps(inventory, ensure_ascii=False, indent=2))
    else:
        print(render_text(inventory))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
