#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

PROJECT_SETTINGS_REL = Path(".superpowers") / "settings.json"
LANHU_OUTPUT_MARKDOWN = "markdown"
LANHU_OUTPUT_HTML = "html"
LANHU_OUTPUT_VALUES = {LANHU_OUTPUT_MARKDOWN, LANHU_OUTPUT_HTML}
LANHU_ROLE_VALUES = {"frontend", "backend"}


def repo_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in (current, *current.parents):
        if (candidate / ".superpowers").exists() or (candidate / ".shared-superpowers").exists() or (candidate / "superpowers").exists():
            return candidate
    return current


def _read_object(settings_path: Path) -> dict:
    try:
        payload = json.loads(settings_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in {settings_path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"Settings must be a JSON object: {settings_path}")
    return payload


def _optional_object(parent: dict, key: str, settings_path: Path, dotted_path: str) -> dict:
    value = parent.get(key, {})
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ValueError(f"{dotted_path} must be an object in {settings_path}")
    return value


def load_lanhu_settings(project_root: Path) -> tuple[str | None, str, Path | None]:
    settings_path = project_root / PROJECT_SETTINGS_REL
    if not settings_path.is_file():
        return None, LANHU_OUTPUT_MARKDOWN, None

    payload = _read_object(settings_path)
    lanhu = _optional_object(payload, "lanhu", settings_path, "lanhu settings")

    configured_role = lanhu.get("role")
    if configured_role is not None and configured_role not in LANHU_ROLE_VALUES:
        allowed_roles = ", ".join(sorted(LANHU_ROLE_VALUES))
        raise ValueError(f"Invalid lanhu.role in {settings_path}: {configured_role!r}; expected one of {allowed_roles}")

    frontend = _optional_object(lanhu, "frontend", settings_path, "lanhu.frontend")
    output = _optional_object(frontend, "output", settings_path, "lanhu.frontend.output")

    value = output.get("format", LANHU_OUTPUT_MARKDOWN)
    if value not in LANHU_OUTPUT_VALUES:
        allowed = ", ".join(sorted(LANHU_OUTPUT_VALUES))
        raise ValueError(f"Invalid lanhu.frontend.output.format in {settings_path}: {value!r}; expected one of {allowed}")
    return configured_role, value, settings_path


def resolve_output_preference(project_root: Path, role: str | None) -> dict:
    configured_role, configured_format, settings_path = load_lanhu_settings(project_root)
    effective_role = role or configured_role
    if effective_role is None:
        raise ValueError("Lanhu role is required when lanhu.role is not configured; expected frontend or backend")
    if effective_role not in {"frontend", "backend"}:
        raise ValueError(f"Unsupported role: {effective_role!r}; expected frontend or backend")
    warnings: list[str] = []
    effective_format = configured_format if effective_role == "frontend" else LANHU_OUTPUT_MARKDOWN
    html_enabled = effective_role == "frontend" and configured_format == LANHU_OUTPUT_HTML

    if effective_role == "backend" and configured_format == LANHU_OUTPUT_HTML:
        warnings.append("lanhu.frontend.output.format is frontend-only; backend output remains markdown")

    settings_display = PROJECT_SETTINGS_REL.as_posix() if settings_path else None
    primary_kind = "html_prd" if html_enabled else "markdown_prd"
    primary_filename = "index.html" if html_enabled else "prd.md"
    return {
        "role": effective_role,
        "configuredRole": configured_role,
        "roleSource": settings_display if role is None and configured_role else "argument",
        "settingsPath": settings_display,
        "source": settings_display or "default",
        "format": effective_format,
        "primaryOutput": {
            "kind": primary_kind,
            "filename": primary_filename,
        },
        "htmlPrd": {
            "enabled": html_enabled,
            "filename": "index.html",
            "prototypeFilename": "prototype/index.html" if html_enabled else None,
            "companionFiles": ["prototype/index.html"] if html_enabled else [],
            "appliesToRole": "frontend",
            "fallbackToMarkdownWhenTextOnly": True,
        },
        "warnings": warnings,
    }


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Resolve Lanhu output settings from project-local .superpowers/settings.json")
    parser.add_argument("args", nargs="*")
    parsed = parser.parse_args(argv)
    if len(parsed.args) > 2:
        parser.error("expected [role] [project_root] or [project_root]")
    role = None
    project_root = "."
    if len(parsed.args) == 1:
        if parsed.args[0] in LANHU_ROLE_VALUES:
            role = parsed.args[0]
        else:
            project_root = parsed.args[0]
    elif len(parsed.args) == 2:
        role, project_root = parsed.args
        if role not in LANHU_ROLE_VALUES:
            parser.error("role must be frontend or backend")
    parsed.role = role
    parsed.project_root = project_root
    return parsed


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = repo_root(Path(args.project_root))
    try:
        preference = resolve_output_preference(project_root, args.role)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(json.dumps(preference, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
