#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
import sys

from spec_common import is_path_within, read_text, repo_root, summary_from_markdown

SCHEMA_VERSION = 1
CURRENT_PLAN_PATH = Path('.superpowers/current-plan')
DEFAULT_SPEC_ROOT = Path('.superpowers/spec')
DEFAULT_PLAN_ROOT = Path('docs/superpowers/plans')
PHASE_FILES = {
    'plan': 'plan.jsonl',
    'implement': 'implement.jsonl',
    'review': 'review.jsonl',
}


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def die(message: str) -> int:
    print(message, file=sys.stderr)
    return 1


def rel_posix(root: Path, target: Path) -> str:
    return target.relative_to(root).as_posix()


def ensure_project_root(root: Path) -> None:
    (root / '.superpowers').mkdir(exist_ok=True)


def resolve_plan_path(root: Path, value: str) -> Path:
    candidate = Path(value)
    if candidate.is_absolute():
        plan = candidate.resolve()
    else:
        plan = (root / candidate).resolve()
    if not is_path_within(root.resolve(), plan):
        raise ValueError(f'Plan path escapes repo root: {value}')
    if plan.suffix != '.md':
        raise ValueError(f'Plan path must be a .md file: {value}')
    return plan


def validate_plan_location(root: Path, plan_path: Path) -> None:
    plan_root = (root / DEFAULT_PLAN_ROOT).resolve()
    if not is_path_within(plan_root, plan_path.resolve()):
        raise ValueError(f'Plan must live under {DEFAULT_PLAN_ROOT.as_posix()}: {rel_posix(root, plan_path)}')


def context_dir_for_plan(plan_path: Path) -> Path:
    return plan_path.with_suffix('.context')


def current_plan_file(root: Path) -> Path:
    return root / CURRENT_PLAN_PATH


def load_state(context_dir: Path) -> dict | None:
    path = context_dir / 'state.json'
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding='utf-8'))


def save_state(context_dir: Path, state: dict) -> None:
    path = context_dir / 'state.json'
    path.write_text(json.dumps(state, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')


def initialize_jsonl_files(context_dir: Path) -> None:
    for filename in PHASE_FILES.values():
        path = context_dir / filename
        if not path.exists():
            path.write_text('', encoding='utf-8')


def set_current_plan(root: Path, plan_path: Path) -> None:
    ensure_project_root(root)
    current_plan_file(root).write_text(rel_posix(root, plan_path) + '\n', encoding='utf-8')


def get_current_plan(root: Path) -> Path | None:
    path = current_plan_file(root)
    if not path.is_file():
        return None
    value = path.read_text(encoding='utf-8').strip()
    if not value:
        return None
    try:
        return resolve_plan_path(root, value)
    except ValueError:
        return None


def load_jsonl(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    rows = []
    for index, line in enumerate(path.read_text(encoding='utf-8').splitlines(), start=1):
        stripped = line.strip()
        if not stripped:
            continue
        try:
            item = json.loads(stripped)
        except json.JSONDecodeError as exc:
            raise ValueError(f'Invalid JSON in {path.name}:{index}: {exc.msg}') from exc
        if not isinstance(item, dict):
            raise ValueError(f'Invalid record in {path.name}:{index}: expected object')
        rows.append(item)
    return rows


def append_jsonl(path: Path, item: dict) -> None:
    with path.open('a', encoding='utf-8') as fh:
        fh.write(json.dumps(item, ensure_ascii=False) + '\n')


def summarize_spec(root: Path, spec_path: Path) -> str:
    try:
        return summary_from_markdown(spec_path)
    except OSError:
        return ''


def render_records(root: Path, records: list[dict], title: str) -> str:
    lines = [f'## {title}', '']
    for item in records:
        rel = item.get('path', '')
        reason = item.get('reason', '')
        mode = item.get('mode', 'summary')
        spec_path = (root / rel).resolve()
        lines.append(f'- `{rel}`')
        if reason:
            lines.append(f'  - Reason: {reason}')
        lines.append(f'  - Mode: {mode}')
        if mode == 'full' and spec_path.is_file():
            lines.append('  - Content:')
            lines.append('')
            for raw in read_text(spec_path).splitlines():
                lines.append(f'    {raw}')
        else:
            summary = summarize_spec(root, spec_path)
            if summary:
                lines.append(f'  - Summary: {summary}')
        lines.append('')
    if len(lines) == 2:
        lines.append('- No records selected yet')
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def cmd_init(args: argparse.Namespace) -> int:
    root = repo_root(Path.cwd())
    ensure_project_root(root)
    try:
        plan_path = resolve_plan_path(root, args.plan)
        validate_plan_location(root, plan_path)
    except ValueError as exc:
        return die(str(exc))

    if not plan_path.is_file():
        return die(f'Plan file not found: {rel_posix(root, plan_path)}')

    context_dir = context_dir_for_plan(plan_path)
    context_dir.mkdir(parents=True, exist_ok=True)
    initialize_jsonl_files(context_dir)

    existing = load_state(context_dir) or {}
    timestamp = now_iso()
    state = {
        'schemaVersion': SCHEMA_VERSION,
        'planPath': rel_posix(root, plan_path),
        'contextDir': rel_posix(root, context_dir),
        'currentPhase': existing.get('currentPhase', 'plan'),
        'createdAt': existing.get('createdAt', timestamp),
        'updatedAt': timestamp,
        'selectionPolicy': 'planning-selected',
        'specRoot': DEFAULT_SPEC_ROOT.as_posix(),
    }
    save_state(context_dir, state)

    if args.set_current:
        set_current_plan(root, plan_path)

    print(f'Initialized context sidecar: {rel_posix(root, context_dir)}')
    if args.set_current:
        print(f'Set current plan: {rel_posix(root, plan_path)}')
    return 0


def cmd_current(args: argparse.Namespace) -> int:
    del args
    root = repo_root(Path.cwd())
    pointer = current_plan_file(root)
    plan_path = get_current_plan(root)
    if plan_path is None:
        if pointer.is_file():
            return die('Current plan pointer exists but does not resolve to a valid plan')
        print('No current plan set')
        return 0
    context_dir = context_dir_for_plan(plan_path)
    print(f'Current plan: {rel_posix(root, plan_path)}')
    print(f'Context sidecar: {rel_posix(root, context_dir)}')
    state = load_state(context_dir)
    if state:
        print(f"Current phase: {state.get('currentPhase', 'unknown')}")
    else:
        print('Current phase: unknown (state.json missing)')
    return 0


def cmd_set_current(args: argparse.Namespace) -> int:
    root = repo_root(Path.cwd())
    try:
        plan_path = resolve_plan_path(root, args.plan)
        validate_plan_location(root, plan_path)
    except ValueError as exc:
        return die(str(exc))
    if not plan_path.is_file():
        return die(f'Plan file not found: {rel_posix(root, plan_path)}')
    set_current_plan(root, plan_path)
    print(f'Set current plan: {rel_posix(root, plan_path)}')
    return 0


def cmd_clear_current(args: argparse.Namespace) -> int:
    del args
    root = repo_root(Path.cwd())
    path = current_plan_file(root)
    if path.exists():
        path.unlink()
    print('Cleared current plan')
    return 0


def resolve_spec_path(root: Path, value: str) -> Path:
    candidate = Path(value)
    if candidate.is_absolute():
        spec = candidate.resolve()
    else:
        spec = (root / candidate).resolve()
    spec_root = (root / DEFAULT_SPEC_ROOT).resolve()
    if not is_path_within(spec_root, spec):
        raise ValueError(f'Spec path must live under {DEFAULT_SPEC_ROOT.as_posix()}: {value}')
    if not spec.is_file():
        raise ValueError(f'Spec file not found: {value}')
    return spec


def load_plan_from_args(root: Path, plan_arg: str | None) -> Path | None:
    if plan_arg:
        plan = resolve_plan_path(root, plan_arg)
        validate_plan_location(root, plan)
        return plan
    return get_current_plan(root)


def update_phase_state(context_dir: Path, phase: str) -> None:
    state = load_state(context_dir) or {}
    timestamp = now_iso()
    state.setdefault('schemaVersion', SCHEMA_VERSION)
    state['currentPhase'] = phase
    state['updatedAt'] = timestamp
    save_state(context_dir, state)


def cmd_add(args: argparse.Namespace) -> int:
    root = repo_root(Path.cwd())
    try:
        plan_path = load_plan_from_args(root, args.plan)
        if plan_path is None:
            return die('No current plan set; pass --plan or run set-current first')
        validate_plan_location(root, plan_path)
        spec_path = resolve_spec_path(root, args.spec)
    except ValueError as exc:
        return die(str(exc))

    context_dir = context_dir_for_plan(plan_path)
    if not context_dir.is_dir():
        return die(f'Context sidecar not initialized: {rel_posix(root, context_dir)}')

    phase_file = context_dir / PHASE_FILES[args.phase]
    record = {
        'type': 'spec',
        'path': rel_posix(root, spec_path),
        'reason': args.reason,
        'phase': args.phase,
        'mode': args.mode,
        'selectedBy': args.selected_by,
        'createdAt': now_iso(),
    }
    append_jsonl(phase_file, record)
    update_phase_state(context_dir, args.phase)
    print(f'Added spec to {phase_file.name}: {record["path"]}')
    print(f'Reason: {args.reason}')
    return 0


def cmd_render(args: argparse.Namespace) -> int:
    root = repo_root(Path.cwd())
    try:
        plan_path = load_plan_from_args(root, args.plan)
        if plan_path is None:
            return die('No current plan set; pass --plan or run set-current first')
        validate_plan_location(root, plan_path)
    except ValueError as exc:
        return die(str(exc))

    context_dir = context_dir_for_plan(plan_path)
    if not context_dir.is_dir():
        return die(f'Context sidecar not initialized: {rel_posix(root, context_dir)}')

    state = load_state(context_dir) or {}
    plan_records = load_jsonl(context_dir / PHASE_FILES['plan'])
    phase_records = load_jsonl(context_dir / PHASE_FILES[args.phase])

    sections = [
        '## Current Plan',
        '',
        f'- Plan: `{rel_posix(root, plan_path)}`',
        f'- Context sidecar: `{rel_posix(root, context_dir)}`',
        f"- Current phase: {state.get('currentPhase', 'unknown')}",
        f'- Render phase: {args.phase}',
        '',
        render_records(root, plan_records, 'Planning-selected Context').rstrip(),
    ]

    if args.phase != 'plan':
        sections.extend(['', render_records(root, phase_records, f'{args.phase.title()} Context').rstrip()])

    print('\n'.join(sections).rstrip())
    return 0


def verify_jsonl_records(root: Path, context_dir: Path, filename: str) -> list[str]:
    path = context_dir / filename
    problems: list[str] = []
    try:
        rows = load_jsonl(path)
    except ValueError as exc:
        return [str(exc)]
    for item in rows:
        rel = item.get('path')
        if not isinstance(rel, str) or not rel:
            problems.append(f'{filename}: missing path field')
            continue
        target = (root / rel).resolve()
        if not is_path_within(root.resolve(), target):
            problems.append(f'{filename}: path escapes repo root: {rel}')
            continue
        if not target.is_file():
            problems.append(f'{filename}: referenced file missing: {rel}')
    return problems


def cmd_verify(args: argparse.Namespace) -> int:
    root = repo_root(Path.cwd())
    try:
        if args.current:
            plan_path = get_current_plan(root)
            if plan_path is None:
                return die('No current plan set')
        else:
            plan_path = resolve_plan_path(root, args.plan)
        validate_plan_location(root, plan_path)
    except ValueError as exc:
        return die(str(exc))

    if not plan_path.is_file():
        return die(f'Plan file not found: {rel_posix(root, plan_path)}')

    context_dir = context_dir_for_plan(plan_path)
    if not context_dir.is_dir():
        return die(f'Context sidecar not initialized: {rel_posix(root, context_dir)}')

    state_path = context_dir / 'state.json'
    if not state_path.is_file():
        return die(f'Missing state.json: {rel_posix(root, state_path)}')
    try:
        state = json.loads(state_path.read_text(encoding='utf-8'))
    except json.JSONDecodeError as exc:
        return die(f'Invalid state.json: {exc.msg}')

    problems: list[str] = []
    if state.get('planPath') != rel_posix(root, plan_path):
        problems.append('state.json planPath does not match target plan')
    if state.get('contextDir') != rel_posix(root, context_dir):
        problems.append('state.json contextDir does not match sidecar directory')

    for filename in PHASE_FILES.values():
        file_path = context_dir / filename
        if not file_path.is_file():
            problems.append(f'Missing {filename}')
        else:
            problems.extend(verify_jsonl_records(root, context_dir, filename))

    current = get_current_plan(root)
    if args.current and current is not None and current.resolve() != plan_path.resolve():
        problems.append('current-plan does not resolve to the verified plan')

    if problems:
        for problem in problems:
            print(f'- {problem}')
        return 1

    print(f'Plan context OK: {rel_posix(root, plan_path)}')
    print(f'Context sidecar OK: {rel_posix(root, context_dir)}')
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='command', required=True)

    init_parser = subparsers.add_parser('init')
    init_parser.add_argument('plan')
    init_parser.add_argument('--set-current', action='store_true')
    init_parser.set_defaults(func=cmd_init)

    current_parser = subparsers.add_parser('current')
    current_parser.set_defaults(func=cmd_current)

    set_current_parser = subparsers.add_parser('set-current')
    set_current_parser.add_argument('plan')
    set_current_parser.set_defaults(func=cmd_set_current)

    clear_current_parser = subparsers.add_parser('clear-current')
    clear_current_parser.set_defaults(func=cmd_clear_current)

    add_parser = subparsers.add_parser('add')
    add_parser.add_argument('--phase', choices=sorted(PHASE_FILES), required=True)
    add_parser.add_argument('--plan')
    add_parser.add_argument('--spec', required=True)
    add_parser.add_argument('--reason', required=True)
    add_parser.add_argument('--mode', choices=('summary', 'full'), default='summary')
    add_parser.add_argument('--selected-by', default='planning')
    add_parser.set_defaults(func=cmd_add)

    render_parser = subparsers.add_parser('render')
    render_parser.add_argument('--phase', choices=('plan', 'implement', 'review'), required=True)
    render_parser.add_argument('--plan')
    render_parser.set_defaults(func=cmd_render)

    verify_parser = subparsers.add_parser('verify')
    group = verify_parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--current', action='store_true')
    group.add_argument('plan', nargs='?')
    verify_parser.set_defaults(func=cmd_verify)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == '__main__':
    raise SystemExit(main())
