#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from spec_common import is_path_within

SCHEMA_VERSION = 1
CURRENT_PLAN_PATH = Path('.superpowers/current-plan')
DEFAULT_SPEC_ROOT = Path('.superpowers/spec')
DEFAULT_PLAN_ROOT = Path('docs/superpowers/plans')
PHASE_FILES = {
    'plan': 'plan.jsonl',
    'implement': 'implement.jsonl',
    'review': 'review.jsonl',
}


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def rel_posix(root: Path, target: Path) -> str:
    return target.relative_to(root).as_posix()


def ensure_project_root(root: Path) -> None:
    (root / '.superpowers').mkdir(exist_ok=True)


def resolve_plan_path(root: Path, value: str) -> Path:
    candidate = Path(value)
    if candidate.is_absolute():
        plan = candidate.resolve()
    else:
        plan = (root / candidate).resolve()
    if not is_path_within(root.resolve(), plan):
        raise ValueError(f'Plan path escapes repo root: {value}')
    if plan.suffix != '.md':
        raise ValueError(f'Plan path must be a .md file: {value}')
    return plan


def validate_plan_location(root: Path, plan_path: Path) -> None:
    plan_root = (root / DEFAULT_PLAN_ROOT).resolve()
    if not is_path_within(plan_root, plan_path.resolve()):
        raise ValueError(f'Plan must live under {DEFAULT_PLAN_ROOT.as_posix()}: {rel_posix(root, plan_path)}')


def context_dir_for_plan(plan_path: Path) -> Path:
    return plan_path.with_suffix('.context')


def current_plan_file(root: Path) -> Path:
    return root / CURRENT_PLAN_PATH


def load_state(context_dir: Path) -> dict | None:
    path = context_dir / 'state.json'
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding='utf-8'))


def save_state(context_dir: Path, state: dict) -> None:
    path = context_dir / 'state.json'
    path.write_text(json.dumps(state, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')


def initialize_jsonl_files(context_dir: Path) -> None:
    for filename in PHASE_FILES.values():
        path = context_dir / filename
        if not path.exists():
            path.write_text('', encoding='utf-8')


def set_current_plan(root: Path, plan_path: Path) -> None:
    ensure_project_root(root)
    current_plan_file(root).write_text(rel_posix(root, plan_path) + '\n', encoding='utf-8')


def get_current_plan(root: Path) -> Path | None:
    path = current_plan_file(root)
    if not path.is_file():
        return None
    value = path.read_text(encoding='utf-8').strip()
    if not value:
        return None
    try:
        return resolve_plan_path(root, value)
    except ValueError:
        return None


def load_jsonl(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    rows = []
    for index, line in enumerate(path.read_text(encoding='utf-8').splitlines(), start=1):
        stripped = line.strip()
        if not stripped:
            continue
        try:
            item = json.loads(stripped)
        except json.JSONDecodeError as exc:
            raise ValueError(f'Invalid JSON in {path.name}:{index}: {exc.msg}') from exc
        if not isinstance(item, dict):
            raise ValueError(f'Invalid record in {path.name}:{index}: expected object')
        rows.append(item)
    return rows


def write_jsonl(path: Path, rows: list[dict]) -> None:
    content = ''
    if rows:
        content = '\n'.join(json.dumps(row, ensure_ascii=False) for row in rows) + '\n'
    path.write_text(content, encoding='utf-8')


def append_jsonl(path: Path, item: dict) -> None:
    with path.open('a', encoding='utf-8') as fh:
        fh.write(json.dumps(item, ensure_ascii=False) + '\n')
