#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from source_truth_common import SourceTruthError, classify_path, load_source_truth_settings



def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if not hasattr(stream, "reconfigure"):
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="replace", newline="\n")
        except (OSError, ValueError):
            pass

def main() -> int:
    _configure_stdio()
    parser = argparse.ArgumentParser(description="Inspect sourceOfTruth settings and classify repo-relative paths.")
    parser.add_argument("project_root", help="Target project root")
    parser.add_argument("--show-policy", action="store_true", help="Include normalized policy in output")
    parser.add_argument("--classify", action="append", default=[], help="Repo-relative path to classify; repeatable")
    args = parser.parse_args()

    try:
        project_root = Path(args.project_root).resolve()
        policy = load_source_truth_settings(project_root)
        payload = {
            "status": "configured" if policy.configured else "not_configured",
            "heuristics": policy.heuristics,
            "settingsPath": policy.settings_path.as_posix(),
            "classifications": [classify_path(project_root, item, policy) for item in args.classify],
        }
        if args.show_policy or not args.classify:
            payload["policy"] = policy.as_dict()
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        return 0
    except SourceTruthError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
