#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

KIND = "superpower-adapter.source-truth-constraints"
SCHEMA_VERSION = 1
CONSTRAINT_CATEGORIES = ("implementation", "test", "review", "general")
ROLE_CATEGORIES = {
    "implementer": ("implementation", "test", "general"),
    "reviewer": ("implementation", "test", "review", "general"),
}
PLAN_WIDE_TASKS = {"all", "plan-wide", "plan_wide", "*"}


class ValidationError(Exception):
    pass


def _as_list(value: Any, field: str) -> list[Any]:
    if value is None:
        return []
    if not isinstance(value, list):
        raise ValidationError(f"{field} must be a list")
    return value


def _as_dict(value: Any, field: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValidationError(f"{field} must be an object")
    return value


def _load_constraints(path: Path) -> dict[str, Any]:
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValidationError(f"Cannot read source-truth constraints: {exc}") from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValidationError(f"Invalid JSON: {exc}") from exc
    return _as_dict(data, "source-truth constraints")


def _validate_constraints(data: dict[str, Any], strict: bool) -> list[str]:
    caveats: list[str] = []
    if data.get("schemaVersion") != SCHEMA_VERSION:
        raise ValidationError(f"schemaVersion must be {SCHEMA_VERSION}")
    if data.get("kind") != KIND:
        raise ValidationError(f"kind must be {KIND}")
    if data.get("status") not in {"passed", "needs_revision", "blocked", "not_configured"}:
        raise ValidationError("status must be one of: passed, needs_revision, blocked, not_configured")

    for index, item in enumerate(_as_list(data.get("taskConstraints"), "taskConstraints")):
        constraint = _as_dict(item, f"taskConstraints[{index}]")
        if not constraint.get("taskId"):
            raise ValidationError(f"taskConstraints[{index}].taskId is required")
        _as_list(constraint.get("appliesTo"), f"taskConstraints[{index}].appliesTo")
        constraints = _as_dict(constraint.get("constraints"), f"taskConstraints[{index}].constraints")
        unknown = sorted(set(constraints) - set(CONSTRAINT_CATEGORIES))
        if unknown:
            message = f"taskConstraints[{index}].constraints contains unsupported categories: {', '.join(unknown)}"
            if strict:
                raise ValidationError(message)
            caveats.append(message)
        for category in CONSTRAINT_CATEGORIES:
            _as_list(constraints.get(category), f"taskConstraints[{index}].constraints.{category}")
        if "sourceRefs" in constraint:
            _as_list(constraint.get("sourceRefs"), f"taskConstraints[{index}].sourceRefs")
    return caveats


def _task_matches(constraint: dict[str, Any], requested_tasks: set[str]) -> bool:
    applies_to = [str(item).strip() for item in _as_list(constraint.get("appliesTo"), "appliesTo") if str(item).strip()]
    if not applies_to:
        return False
    normalized = {item.lower() for item in applies_to}
    if normalized & PLAN_WIDE_TASKS:
        return True
    return bool(set(applies_to) & requested_tasks)


def _matching_constraints(data: dict[str, Any], tasks: list[str]) -> list[dict[str, Any]]:
    requested = {task.strip() for task in tasks if task.strip()}
    matched: list[dict[str, Any]] = []
    for item in _as_list(data.get("taskConstraints"), "taskConstraints"):
        constraint = _as_dict(item, "taskConstraints[]")
        if _task_matches(constraint, requested):
            matched.append(constraint)
    return matched


def _append_constraints(lines: list[str], constraints: dict[str, Any], role: str) -> None:
    for category in ROLE_CATEGORIES[role]:
        items = _as_list(constraints.get(category), f"constraints.{category}")
        if not items:
            continue
        lines.append(f"#### {category.capitalize()} constraints")
        for item in items:
            lines.append(f"- {item}")


def render_markdown(data: dict[str, Any], tasks: list[str], role: str) -> str:
    if data.get("status") == "not_configured":
        return "No configured source-of-truth constraints for this plan."
    if data.get("status") == "blocked":
        return "## Source-of-Truth Constraints\n\n- Plan source-of-truth verification is blocked; stop and return to planning before implementation."
    constraints = _matching_constraints(data, tasks)
    if not constraints:
        return "No applicable source-of-truth constraints for this task/role."

    lines = ["## Source-of-Truth Constraints", ""]
    for constraint in constraints:
        task_id = constraint.get("taskId", "unknown task")
        lines.append(f"### Constraint Set: `{task_id}`")
        applies = ", ".join(str(item) for item in _as_list(constraint.get("appliesTo"), "appliesTo"))
        if applies:
            lines.append(f"- Applies to: {applies}")
        lines.append(f"- Hard constraint: `{'true' if constraint.get('hardConstraint') else 'false'}`")
        for caveat in _as_list(constraint.get("caveats"), "constraint.caveats"):
            lines.append(f"- Caveat: {caveat}")
        _append_constraints(lines, _as_dict(constraint.get("constraints"), "constraints"), role)
        lines.append("")
    for caveat in _as_list(data.get("caveats"), "caveats"):
        lines.append(f"- Source-of-truth caveat: {caveat}")
    return "\n".join(lines).rstrip()


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate, filter, and render source-truth constraints JSON.")
    parser.add_argument("constraints_path", help="Path to docs/superpowers/plans/<plan-stem>.source-truth-constraints.json")
    parser.add_argument("--task", action="append", default=[], help="Task id or label to include; repeatable")
    parser.add_argument("--role", choices=["implementer", "reviewer"], default="implementer")
    parser.add_argument("--format", choices=["markdown"], default="markdown")
    parser.add_argument("--validate-only", action="store_true")
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()

    try:
        data = _load_constraints(Path(args.constraints_path))
        caveats = _validate_constraints(data, args.strict)
        if args.validate_only:
            for caveat in caveats:
                print(f"Warning: {caveat}", file=sys.stderr)
            print("source-truth constraints JSON is valid")
            return 0
        if not args.task:
            raise ValidationError("At least one --task is required unless --validate-only is used")
        print(render_markdown(data, args.task, args.role))
        return 0
    except ValidationError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
