#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any
import json
import re

PROJECT_SETTINGS_REL = Path(".superpowers") / "settings.json"
ROLE_VALUES = {"truth", "evidence", "ignore"}
EDIT_VALUES = {"never", "ask"}
DEFAULT_HEURISTICS = False


class SourceTruthError(ValueError):
    pass


@dataclass(frozen=True)
class SourceTruthRule:
    paths: tuple[str, ...]
    role: str
    edit: str | None = None

    def as_dict(self) -> dict[str, Any]:
        payload: dict[str, Any] = {"paths": list(self.paths), "role": self.role}
        if self.edit is not None:
            payload["edit"] = self.edit
        return payload


@dataclass(frozen=True)
class SourceTruthPolicy:
    settings_path: Path
    heuristics: bool = DEFAULT_HEURISTICS
    sources: tuple[SourceTruthRule, ...] = ()

    @property
    def configured(self) -> bool:
        return bool(self.sources)

    def as_dict(self) -> dict[str, Any]:
        return {
            "settingsPath": self.settings_path.as_posix(),
            "heuristics": self.heuristics,
            "sources": [source.as_dict() for source in self.sources],
        }


def repo_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in (current, *current.parents):
        if (candidate / ".git").exists() or (candidate / ".superpowers").exists() or (candidate / "superpowers").exists():
            return candidate
    return current


def normalize_rel_path(path: str | Path) -> str:
    raw = Path(path).as_posix().strip()
    if not raw:
        raise SourceTruthError("path must not be empty")
    if raw.startswith("./"):
        raw = raw[2:]
    if raw.startswith("/"):
        raise SourceTruthError(f"classified path must be repo-relative, got absolute path: {path}")
    parts = [part for part in raw.split("/") if part not in {"", "."}]
    if any(part == ".." for part in parts):
        raise SourceTruthError(f"classified path must not contain '..': {path}")
    return "/".join(parts)


def _validate_pattern(pattern: Any, settings_path: Path) -> str:
    if not isinstance(pattern, str):
        raise SourceTruthError(f"sourceOfTruth.sources[].paths entries must be strings in {settings_path}")
    value = pattern.strip()
    if not value:
        raise SourceTruthError(f"sourceOfTruth.sources[].paths entries must not be empty in {settings_path}")
    body = value[1:] if value.startswith("!") else value
    body = body[1:] if body.startswith("/") else body
    parts = [part for part in body.split("/") if part not in {"", "."}]
    if any(part == ".." for part in parts):
        raise SourceTruthError(f"sourceOfTruth pattern must not contain '..' in {settings_path}: {value!r}")
    return value


def _load_settings_payload(settings_path: Path) -> dict[str, Any]:
    if not settings_path.is_file():
        return {}
    try:
        payload = json.loads(settings_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SourceTruthError(f"Invalid JSON in {settings_path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise SourceTruthError(f"Settings must be a JSON object: {settings_path}")
    return payload


def load_source_truth_settings(project_root: Path) -> SourceTruthPolicy:
    settings_path = project_root.resolve() / PROJECT_SETTINGS_REL
    payload = _load_settings_payload(settings_path)
    raw = payload.get("sourceOfTruth", {})
    if raw is None:
        raw = {}
    if not isinstance(raw, dict):
        raise SourceTruthError(f"sourceOfTruth must be an object in {settings_path}")
    unknown = sorted(set(raw) - {"heuristics", "sources"})
    if unknown:
        raise SourceTruthError(f"Unknown sourceOfTruth key(s) in {settings_path}: {', '.join(unknown)}")

    heuristics = raw.get("heuristics", DEFAULT_HEURISTICS)
    if not isinstance(heuristics, bool):
        raise SourceTruthError(f"sourceOfTruth.heuristics must be a boolean in {settings_path}")

    sources_raw = raw.get("sources", [])
    if sources_raw is None:
        sources_raw = []
    if not isinstance(sources_raw, list):
        raise SourceTruthError(f"sourceOfTruth.sources must be an array in {settings_path}")

    sources: list[SourceTruthRule] = []
    for index, item in enumerate(sources_raw):
        label = f"sourceOfTruth.sources[{index}]"
        if not isinstance(item, dict):
            raise SourceTruthError(f"{label} must be an object in {settings_path}")
        unknown_item = sorted(set(item) - {"paths", "role", "edit"})
        if unknown_item:
            raise SourceTruthError(f"Unknown {label} key(s) in {settings_path}: {', '.join(unknown_item)}")
        paths_raw = item.get("paths")
        if not isinstance(paths_raw, list) or not paths_raw:
            raise SourceTruthError(f"{label}.paths must be a non-empty string array in {settings_path}")
        paths = tuple(_validate_pattern(pattern, settings_path) for pattern in paths_raw)
        role = item.get("role")
        if role not in ROLE_VALUES:
            allowed = ", ".join(sorted(ROLE_VALUES))
            raise SourceTruthError(f"Invalid {label}.role in {settings_path}: {role!r}; expected one of {allowed}")
        edit = item.get("edit")
        if role == "truth":
            if edit not in EDIT_VALUES:
                allowed = ", ".join(sorted(EDIT_VALUES))
                raise SourceTruthError(f"{label}.edit is required for role 'truth' in {settings_path}; expected one of {allowed}")
        elif "edit" in item:
            raise SourceTruthError(f"{label}.edit is only allowed when role is 'truth' in {settings_path}")
        sources.append(SourceTruthRule(paths=paths, role=role, edit=edit))
    return SourceTruthPolicy(settings_path=settings_path, heuristics=heuristics, sources=tuple(sources))


def _glob_regex(pattern: str, anchored: bool, directory: bool, segment_only: bool) -> re.Pattern[str]:
    regex = ""
    index = 0
    while index < len(pattern):
        char = pattern[index]
        if char == "*":
            if index + 1 < len(pattern) and pattern[index + 1] == "*":
                index += 2
                if index < len(pattern) and pattern[index] == "/":
                    index += 1
                    regex += "(?:.*/)?"
                else:
                    regex += ".*"
                continue
            regex += "[^/]*"
        elif char == "?":
            regex += "[^/]"
        else:
            regex += re.escape(char)
        index += 1

    if segment_only:
        return re.compile(rf"(^|.*/){regex}(/.*)?$")
    prefix = "^" if anchored else r"(^|.*/)"
    suffix = r"(/.*)?$" if directory else "$"
    return re.compile(prefix + regex + suffix)


def _pattern_matches(pattern: str, rel_path: str, is_dir: bool = False) -> bool:
    value = pattern.strip()
    if not value or value.startswith("#"):
        return False
    if value.startswith("!"):
        value = value[1:]
    directory = value.endswith("/")
    if directory:
        value = value.rstrip("/")
    anchored = value.startswith("/")
    if anchored:
        value = value.lstrip("/")
    if not value:
        return False
    segment_only = "/" not in value
    regex = _glob_regex(value, anchored=anchored, directory=directory, segment_only=segment_only)
    if regex.search(rel_path):
        return True
    return bool(directory and is_dir and regex.search(rel_path.rstrip("/") + "/"))


def match_gitignore_patterns(patterns: list[str] | tuple[str, ...], rel_path: str, is_dir: bool = False) -> bool:
    normalized = normalize_rel_path(rel_path)
    matched = False
    for pattern in patterns:
        value = pattern.strip()
        if not value or value.startswith("#"):
            continue
        negated = value.startswith("!")
        if _pattern_matches(value, normalized, is_dir=is_dir):
            matched = not negated
    return matched


def classify_path(project_root: Path, rel_path: str | Path, policy: SourceTruthPolicy) -> dict[str, Any]:
    normalized = normalize_rel_path(rel_path)
    matched_rule: SourceTruthRule | None = None
    matched_index: int | None = None
    for index, source in enumerate(policy.sources):
        if match_gitignore_patterns(source.paths, normalized):
            matched_rule = source
            matched_index = index
    if matched_rule is None:
        return {
            "path": normalized,
            "role": "unconfigured",
            "edit": None,
            "sourceIndex": None,
            "heuristicsEnabled": policy.heuristics,
        }
    return {
        "path": normalized,
        "role": matched_rule.role,
        "edit": matched_rule.edit,
        "sourceIndex": matched_index,
        "heuristicsEnabled": policy.heuristics,
    }
