#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from spec_common import AUTO_END, AUTO_START, ENTRY_STUB, is_path_within, repo_root, summary_from_markdown

SUPPORTED_SUFFIXES = {".md", ".markdown", ".mdx", ".txt"}
CHILD_STUB = "# Spec Index\n\nUse this index to navigate the specs in this section.\n\n" + AUTO_START + "\n" + AUTO_END + "\n"


@dataclass(frozen=True)
class ImportItem:
    source_path: Path
    source_rel: Path
    target_rel: Path


def title_from_path(path: Path) -> str:
    return path.name.replace("-", " ").replace("_", " ").title()


def discover_sources(source: Path) -> list[Path]:
    if source.is_file():
        return [source]
    if not source.is_dir():
        raise SystemExit(f"Missing source spec path: {source}")
    return sorted(
        path
        for path in source.rglob("*")
        if path.is_file()
        and path.suffix.lower() in SUPPORTED_SUFFIXES
        and ".git" not in path.parts
        and "node_modules" not in path.parts
    )


def normalize_suffix(path: Path) -> Path:
    return path.with_suffix(".md") if path.suffix.lower() != ".md" else path


def plan_import_items(source: Path, target_prefix: Path) -> list[ImportItem]:
    source = source.expanduser().resolve()
    sources = discover_sources(source)
    root = source if source.is_dir() else source.parent
    items: list[ImportItem] = []
    for path in sources:
        source_rel = path.relative_to(root) if source.is_dir() else Path(path.name)
        target_rel = normalize_suffix(target_prefix / source_rel)
        items.append(ImportItem(path, source_rel, target_rel))
    return items


def copy_item(spec_root: Path, item: ImportItem, merge_existing: bool) -> bool:
    target = (spec_root / item.target_rel).resolve()
    if not is_path_within(spec_root.resolve(), target):
        raise SystemExit(f"Invalid target path: {item.target_rel.as_posix()}")
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        incoming = item.source_path.read_text(encoding="utf-8")
        if existing == incoming:
            return False
        if not merge_existing:
            raise SystemExit(f"Target already exists: {item.target_rel.as_posix()}")
        raise SystemExit(f"Refusing to overwrite existing spec file: {item.target_rel.as_posix()}")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(item.source_path.read_text(encoding="utf-8"), encoding="utf-8")
    return True


def replace_auto_section(text: str, content: str) -> str:
    if AUTO_START not in text or AUTO_END not in text:
        text = text.rstrip() + "\n\n" + AUTO_START + "\n" + AUTO_END + "\n"
    start = text.index(AUTO_START) + len(AUTO_START)
    end = text.index(AUTO_END)
    body = "\n" + content.rstrip() + "\n" if content.strip() else "\n"
    return text[:start] + body + text[end:]


def ensure_index_file(index_path: Path, title: str) -> None:
    if index_path.exists():
        return
    index_path.parent.mkdir(parents=True, exist_ok=True)
    if index_path.name == "index.md" and index_path.parent.name == "spec":
        index_path.write_text(ENTRY_STUB, encoding="utf-8")
    else:
        index_path.write_text(f"# {title}\n\nUse this index to navigate the specs in this section.\n\n{AUTO_START}\n{AUTO_END}\n", encoding="utf-8")


def index_entry(base_dir: Path, target: Path) -> str:
    rel = target.relative_to(base_dir).as_posix()
    if target.name == "index.md":
        rel = target.parent.relative_to(base_dir).as_posix().rstrip("/") + "/"
    summary = summary_from_markdown(target)
    return f"- `{rel}`" + (f" — {summary}" if summary else "")


def rebuild_indexes(spec_root: Path) -> None:
    directories = {spec_root}
    for path in spec_root.rglob("*.md"):
        directories.add(path.parent)
        for parent in path.parent.parents:
            if parent == spec_root.parent:
                break
            if is_path_within(spec_root.resolve(), parent.resolve()):
                directories.add(parent)

    for directory in sorted(directories, key=lambda item: len(item.relative_to(spec_root).parts) if item != spec_root else 0):
        title = "Project Specs" if directory == spec_root else title_from_path(directory)
        ensure_index_file(directory / "index.md", title)

    for directory in sorted(directories, key=lambda item: item.relative_to(spec_root).as_posix() if item != spec_root else ""):
        index_path = directory / "index.md"
        children: list[Path] = []
        for child in sorted(directory.iterdir()):
            if child.name.startswith("."):
                continue
            if child.is_dir() and (child / "index.md").is_file():
                children.append(child / "index.md")
            elif child.is_file() and child.suffix == ".md" and child.name != "index.md":
                children.append(child)
        content = "\n".join(index_entry(directory, child) for child in children)
        index_path.write_text(replace_auto_section(index_path.read_text(encoding="utf-8"), content), encoding="utf-8")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert an existing spec tree into index-driven .superpowers/spec structure.")
    parser.add_argument("source", help="Path to a source spec file or directory")
    parser.add_argument("--target", default="", help="Optional target subdirectory or file under .superpowers/spec")
    parser.add_argument("--merge-existing", action="store_true", help="Allow identical existing files; never overwrites different content")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = repo_root(Path.cwd())
    spec_root = root / ".superpowers" / "spec"
    spec_root.mkdir(parents=True, exist_ok=True)

    target_prefix = Path(args.target) if args.target else Path()
    items = plan_import_items(Path(args.source), target_prefix)
    imported: list[str] = []
    skipped: list[str] = []

    for item in items:
        changed = copy_item(spec_root, item, args.merge_existing)
        row = f"{item.source_rel.as_posix()} -> {item.target_rel.as_posix()}"
        if changed:
            imported.append(row)
        else:
            skipped.append(row)

    rebuild_indexes(spec_root)

    for item in imported:
        print(f"Imported {item}")
    for item in skipped:
        print(f"Skipped identical {item}")
    print(f"Imported {len(imported)} spec file(s), skipped {len(skipped)} existing file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
