#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

from spec_common import build_spec_index_graph, rel_posix, repo_root, summary_from_markdown


def candidate_rows(spec_root: Path) -> list[dict[str, str]]:
    graph = build_spec_index_graph(spec_root)
    return [
        {
            "path": rel_posix(spec_root.resolve(), path),
            "summary": summary_from_markdown(path),
            "kind": "leaf",
        }
        for path in graph.leaves
    ]


def render_text(payload: dict) -> str:
    lines = [
        "Indexed spec candidates only; no target decision was made.",
        "Read relevant specs and choose ownership yourself.",
    ]
    if payload["hint"]:
        lines.append(f"Hint: {payload['hint']}")
    if payload["warnings"]:
        lines.append("")
        lines.append("Warnings:")
        lines.extend(f"- {warning}" for warning in payload["warnings"])
    lines.append("")
    lines.append("Candidates:")
    if not payload["candidates"]:
        lines.append("- <none>")
    else:
        for candidate in payload["candidates"]:
            summary = f" — {candidate['summary']}" if candidate["summary"] else ""
            lines.append(f"- `{candidate['path']}`{summary}")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="List indexed leaf spec candidates without choosing an update target."
    )
    parser.add_argument("hint", nargs="?", default="", help="Optional context to echo for the agent; not used for scoring.")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable candidate data.")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    root = repo_root(Path.cwd())
    spec_root = root / ".superpowers" / "spec"
    graph = build_spec_index_graph(spec_root)
    payload = {
        "decisionMade": False,
        "hint": args.hint,
        "specRoot": str(spec_root),
        "candidates": candidate_rows(spec_root),
        "warnings": graph.warnings,
    }

    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        print(render_text(payload))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
