#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from spec_common import repo_root


def main() -> int:
    if len(sys.argv) < 4:
        raise SystemExit('Usage: spec_update_run.py <hint> <title> <why> [rule ...]')

    hint = sys.argv[1]
    title = sys.argv[2]
    why = sys.argv[3]
    rules = sys.argv[4:]

    scripts = Path(__file__).resolve().parent

    target = subprocess.check_output(
        [sys.executable, str(scripts / 'spec_select_target.py'), hint],
        text=True,
    ).strip()

    subprocess.check_call(
        [sys.executable, str(scripts / 'spec_apply_update.py'), target, title, why, *rules]
    )
    subprocess.check_call([sys.executable, str(scripts / 'update-spec.py')])

    print(f'Updated spec target: {target}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
