#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

from pathlib import Path
import sys

from spec_common import repo_root


def main() -> int:
    root = repo_root(Path.cwd())
    spec_root = root / '.superpowers' / 'spec'
    target = sys.argv[1] if len(sys.argv) > 1 else '<choose-target-spec>'
    print(f'''Update the spec body before refreshing indexes.

Project spec root:
- {spec_root}

Recommended workflow:
1. Identify what was learned from the completed task, bug fix, or design discussion.
2. Choose the best target spec file under .superpowers/spec/.
3. Add or revise durable content in that file:
   - implementation rules
   - contracts and constraints
   - validation or error behavior
   - non-obvious conventions
   - cross-cutting guides when the content is about what to consider rather than how to implement
4. Keep index.md files lightweight; put detailed content in leaf spec files.
5. After updating the spec body, run:
   python3 superpowers/scripts/update-spec.py

Suggested target:
- {target}
''')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
