#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

from pathlib import Path
import re
import sys

from spec_common import build_spec_index_graph, repo_root, summary_from_markdown


def tokenize(value: str) -> list[str]:
    return [token for token in re.split(r'[^a-z0-9]+', value.lower()) if token]


def score_candidate(path: Path, rel: str, summary: str, tokens: list[str]) -> float:
    score = 0.0
    filename = path.name.lower()
    rel_lower = rel.lower()
    summary_lower = summary.lower()
    for token in tokens:
        if token in filename:
            score += 4.0
        elif token in rel_lower:
            score += 3.0
        if token in summary_lower:
            score += 2.0
    return score


def choose_target(spec_root: Path, hint: str) -> str:
    graph = build_spec_index_graph(spec_root)
    if not graph.leaves:
        return '<create-new-leaf-spec>'

    tokens = tokenize(hint)
    if not tokens:
        return graph.leaves[0].relative_to(spec_root).as_posix()

    rows: list[tuple[float, str]] = []
    for path in graph.leaves:
        rel = path.relative_to(spec_root).as_posix()
        summary = summary_from_markdown(path)
        score = score_candidate(path, rel, summary, tokens)
        if score > 0:
            rows.append((score, rel))

    if rows:
        rows.sort(key=lambda item: (-item[0], item[1]))
        return rows[0][1]

    return graph.leaves[0].relative_to(spec_root).as_posix()


def main() -> int:
    hint = sys.argv[1] if len(sys.argv) > 1 else ''
    root = repo_root(Path.cwd())
    spec_root = root / '.superpowers' / 'spec'
    spec_root.mkdir(parents=True, exist_ok=True)
    print(choose_target(spec_root, hint))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
