#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return slug or "spec-update"


def main() -> int:
    if len(sys.argv) < 4:
        raise SystemExit('Usage: spec_update_run.py <hint> <title> <why> [rule ...]')

    hint = sys.argv[1]
    title = sys.argv[2]
    why = sys.argv[3]
    rules = sys.argv[4:]

    scripts = Path(__file__).resolve().parent

    target = subprocess.check_output(
        [sys.executable, str(scripts / 'spec_select_target.py'), hint],
        text=True,
    ).strip()
    if target == '<create-new-leaf-spec>':
        target = f'updates/{slugify(title)}.md'

    subprocess.check_call(
        [sys.executable, str(scripts / 'spec_apply_update.py'), target, title, why, *rules]
    )
    subprocess.check_call([sys.executable, str(scripts / 'update-spec.py')])

    print(f'Updated spec target: {target}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
