#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json

STATUS_NO_UPDATE = 'no_update_needed'
STATUS_RECOMMEND = 'recommend_update'
STATUS_STRONGLY_RECOMMEND = 'strongly_recommend_update'

KEYWORDS = [
    'contract',
    'payload',
    'error',
    'validation',
    'convention',
    'behavior',
    'api',
    'response',
    'request',
    'schema',
    'normalization',
]

INTERESTING_PATHS = [
    'api',
    'handler',
    'backend',
    'frontend',
    'route',
    'controller',
    'schema',
    'validator',
]


def evaluate(summary: str, changed_files: list[str]) -> dict:
    summary_lower = summary.strip().lower()
    files_lower = ' '.join(changed_files).lower()
    signals: list[str] = []

    for keyword in KEYWORDS:
        if keyword in summary_lower:
            signals.append(f'summary mentions {keyword}')
            break

    for marker in INTERESTING_PATHS:
        if marker in files_lower:
            signals.append(f'changed files suggest implementation rule changes ({marker})')
            break

    if len(signals) >= 2:
        status = STATUS_STRONGLY_RECOMMEND
    elif signals:
        status = STATUS_RECOMMEND
    else:
        status = STATUS_NO_UPDATE

    next_steps = []
    if status != STATUS_NO_UPDATE:
        next_steps.append('Consider running python3 superpowers/scripts/spec_update_run.py ...')

    return {
        'status': status,
        'signals': signals,
        'nextSteps': next_steps,
    }


def render_text(result: dict) -> str:
    status = result['status']
    if status == STATUS_NO_UPDATE:
        lines = ['NO_UPDATE_NEEDED: no strong durable-knowledge signal detected']
    elif status == STATUS_RECOMMEND:
        lines = ['RECOMMEND_UPDATE: this task may have produced durable implementation knowledge']
    else:
        lines = ['STRONGLY_RECOMMEND_UPDATE: this task likely produced durable implementation knowledge']

    if result['signals']:
        lines.extend(['', 'Why:'])
        for signal in result['signals']:
            lines.append(f'- {signal}')

    if result['nextSteps']:
        lines.extend(['', 'Suggested next step:'])
        for step in result['nextSteps']:
            lines.append(step)

    return '\n'.join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument('--summary', default='')
    parser.add_argument('--changed-file', action='append', default=[])
    parser.add_argument('--json', action='store_true')
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    result = evaluate(args.summary, args.changed_file)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(render_text(result))

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
