#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

from pathlib import Path
import sys

from spec_common import repo_root, relevant_markdown_files, relevant_child_directories, load_ignored_dir_names


def gather_leaf_specs(directory: Path, ignored: set[str]) -> list[Path]:
    results = list(relevant_markdown_files(directory))
    for child in relevant_child_directories(directory, ignored):
        results.extend(gather_leaf_specs(child, ignored))
    return sorted(results)


def choose_target(spec_root: Path, hint: str) -> str:
    ignored = load_ignored_dir_names(spec_root)
    leaves = gather_leaf_specs(spec_root, ignored)
    if not leaves:
        return '<create-new-leaf-spec>'

    hint_l = hint.lower()
    for path in leaves:
        rel = path.relative_to(spec_root).as_posix()
        if hint_l and hint_l in rel.lower():
            return rel

    keyword_map = [
        ('error', 'error-handling.md'),
        ('contract', 'contract.md'),
        ('api', 'contract.md'),
        ('component', 'component.md'),
        ('frontend', 'frontend/'),
        ('backend', 'backend/'),
    ]
    for key, needle in keyword_map:
        if key in hint_l:
            for path in leaves:
                rel = path.relative_to(spec_root).as_posix()
                if needle in rel:
                    return rel

    return leaves[0].relative_to(spec_root).as_posix()


def main() -> int:
    hint = sys.argv[1] if len(sys.argv) > 1 else ''
    root = repo_root(Path.cwd())
    spec_root = root / '.superpowers' / 'spec'
    spec_root.mkdir(parents=True, exist_ok=True)
    print(choose_target(spec_root, hint))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
