#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

from pathlib import Path

from spec_common import (
    child_directory_summary,
    is_ignored_directory,
    load_ignored_dir_names,
    relevant_child_directories,
    relevant_markdown_files,
    repo_root,
    summary_from_markdown,
    has_relevant_content,
)

AUTO_START = "<!-- superpower-adapter:auto:start -->"
AUTO_END = "<!-- superpower-adapter:auto:end -->"
ENTRY_STUB = "# Project Specs\n\nUse this file as the entry point for project-specific specs.\n\n" + AUTO_START + "\n" + AUTO_END + "\n"
CHILD_STUB = "# Spec Index\n\nSummarize this section and keep links to narrower spec files below.\n\n" + AUTO_START + "\n" + AUTO_END + "\n"


def ensure_index(path: Path, stub: str) -> None:
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(stub, encoding="utf-8")


def replace_auto_section(text: str, content: str) -> str:
    if AUTO_START not in text or AUTO_END not in text:
        text = text.rstrip() + "\n\n" + AUTO_START + "\n" + AUTO_END + "\n"
    start = text.index(AUTO_START) + len(AUTO_START)
    end = text.index(AUTO_END)
    body = "\n" + content.rstrip() + "\n" if content.strip() else "\n"
    return text[:start] + body + text[end:]


def index_stub_for(path: Path, spec_root: Path) -> str:
    return ENTRY_STUB if path == spec_root / "index.md" else CHILD_STUB


def ensure_directory_indexes(spec_root: Path, ignored_dir_names: set[str]) -> list[Path]:
    indexes = [spec_root / "index.md"]
    ensure_index(indexes[0], ENTRY_STUB)

    for directory in sorted(path for path in spec_root.rglob("*") if path.is_dir() and not is_ignored_directory(path, ignored_dir_names)):
        if has_relevant_content(directory, ignored_dir_names):
            index_path = directory / "index.md"
            ensure_index(index_path, CHILD_STUB)
            indexes.append(index_path)

    return indexes


def render_index(index_path: Path, ignored_dir_names: set[str]) -> str:
    directory = index_path.parent
    child_dirs = relevant_child_directories(directory, ignored_dir_names)
    leaf_files = relevant_markdown_files(directory)
    lines: list[str] = []

    if child_dirs:
        lines.extend(["## Auto-discovered child indexes", ""])
        for child in child_dirs:
            child_index = child / "index.md"
            rel = child_index.relative_to(directory).as_posix()
            summary = child_directory_summary(child, ignored_dir_names)
            if summary:
                lines.append(f"- `{rel}` — {summary}")
            else:
                lines.append(f"- `{rel}`")
        lines.append("")

    if leaf_files:
        lines.extend(["## Auto-discovered leaf files", ""])
        for file_path in leaf_files:
            rel = file_path.relative_to(directory).as_posix()
            summary = summary_from_markdown(file_path)
            if summary:
                lines.append(f"- `{rel}` — {summary}")
            else:
                lines.append(f"- `{rel}`")
        lines.append("")

    if not child_dirs and not leaf_files:
        lines.extend(["## Auto-discovered contents", "", "- No child indexes or leaf spec files discovered yet", ""])

    content = "\n".join(lines).rstrip()
    existing = index_path.read_text(encoding="utf-8")
    return replace_auto_section(existing, content)


def main() -> int:
    root = repo_root(Path.cwd())
    spec_root = root / ".superpowers" / "spec"
    spec_root.mkdir(parents=True, exist_ok=True)

    ignored_dir_names = load_ignored_dir_names(spec_root)
    indexes = ensure_directory_indexes(spec_root, ignored_dir_names)

    for index_path in indexes:
        ensure_index(index_path, index_stub_for(index_path, spec_root))
        index_path.write_text(render_index(index_path, ignored_dir_names), encoding="utf-8")

    print(f"Updated spec indexes under {spec_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
