#!/usr/bin/env python3
"""Generated by superpower-adapter.

Generate per-document section index files from wiki-section markers.

Usage:
  wiki_generate_section_index.py <wiki-file-path> [--wiki-root project|shared] [--project-root PATH]
  wiki_generate_section_index.py --all [--wiki-root project|shared|all] [--project-root PATH]

Scans section markers in wiki documents and generates companion .index.md files.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from wiki_section import extract_section, list_section_ids, page_type  # noqa: E402
from wiki_common import (  # noqa: E402
    build_section_graph,
    build_wiki_index_graph,
    existing_wiki_roots,
    rel_posix,
    repo_root,
    select_wiki_root,
)

HARD_KEYWORDS = {"必须", "禁止", "MUST", "MUST NOT", "REQUIRED", "SHALL NOT"}
GENERATED_HEADER = "> Auto-generated from section markers. Do not edit manually.\n"
SECTION_GRAPH_FILE = ".graph.json"


def _split_header_and_table(content: str) -> tuple[str, str]:
    """Split existing .index.md into preserved header and generated table."""
    lines = content.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.strip().startswith("|---"):
            split_at = max(i - 1, 0)
            return "".join(lines[:split_at]), "".join(lines[split_at:])
    return content, ""


def detect_strength(content: str) -> str:
    upper = content.upper()
    for kw in HARD_KEYWORDS:
        if kw.upper() in upper:
            return "hard"
    return "soft"


def first_description(content: str) -> str:
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            text = stripped.lstrip("#").strip()
            if text:
                return text[:80]
        elif stripped and not stripped.startswith("<!--"):
            return stripped[:80]
    return "(empty section)"


def _with_trailing_newline(content: str) -> str:
    return content if content.endswith("\n") else content + "\n"


def _format_link_cell(values: list[tuple[str, str]]) -> str:
    if not values:
        return "—"
    parts = []
    for node, edge_type in values:
        label = f"`{node}`"
        if edge_type and edge_type != "see-also":
            label += f" _({edge_type})_"
        parts.append(label)
    return "<br>".join(parts)


def build_links_index(graph) -> dict[str, dict[str, dict[str, list[tuple[str, str]]]]]:
    """Index a SectionGraph as {page_rel: {section_id: {"out": [...], "in": [...]}}}.

    Each entry is (node, edge_type). Only section-targeted backlinks are surfaced per
    section row; page-level [[page]] edges still live in full fidelity inside .graph.json.
    """
    index: dict[str, dict[str, dict[str, list[tuple[str, str]]]]] = {}

    def ensure(rel: str, sid: str) -> dict[str, list[tuple[str, str]]]:
        return index.setdefault(rel, {}).setdefault(sid, {"out": [], "in": []})

    for edge in graph.edges:
        rel, _, sid = edge["from"].rpartition("#")
        if rel and sid:
            ensure(rel, sid)["out"].append((edge["to"], edge["type"]))
    for to_node, sources in graph.backlinks.items():
        if "#" not in to_node:
            continue
        rel, _, sid = to_node.rpartition("#")
        if rel and sid:
            ensure(rel, sid)["in"].extend((s["from"], s["type"]) for s in sources)
    return index


def generate_index(
    file_path: Path,
    existing_content: str | None = None,
    links_for_file: dict[str, dict[str, list[str]]] | None = None,
) -> str | None:
    """Generate index content for a wiki file. Returns None if no markers found."""
    text = file_path.read_text(encoding="utf-8")
    section_ids = list_section_ids(text)
    if not section_ids:
        return None

    links_for_file = links_for_file or {}
    table_lines = [
        "| section | 描述 | 约束强度 | 引用 | 被引用 |",
        "|---|---|---|---|---|",
    ]

    for sid in section_ids:
        content = extract_section(text, sid)
        if content is None:
            continue
        desc = first_description(content)
        strength = detect_strength(content)
        section_links = links_for_file.get(sid, {})
        out_cell = _format_link_cell(section_links.get("out", []))
        in_cell = _format_link_cell(section_links.get("in", []))
        table_lines.append(f"| {sid} | {desc} | {strength} | {out_cell} | {in_cell} |")

    table_lines.append("")
    table_part = "\n".join(table_lines)

    if existing_content:
        header_part = _split_header_and_table(existing_content)[0]
    else:
        title_line = ""
        for line in text.splitlines():
            if line.startswith("# "):
                title_line = line.lstrip("# ").strip()
                break
        if not title_line:
            title_line = file_path.stem
        header_part = f"# {title_line} — Section Index\n\n{GENERATED_HEADER}\n"

    header_part = _with_trailing_newline(_reconcile_type_line(header_part, page_type(text)))
    return header_part + table_part


def _reconcile_type_line(header: str, ptype: str) -> str:
    """Ensure the index header carries a single ``> Type: <ptype>`` metadata line.

    Idempotent: stale Type lines are dropped and the current one is re-inserted right
    after the auto-generated notice (or after the title). Type is a blockquote metadata
    line, like the notice, so extract_document_context_from_index skips it from overview.
    """
    kept = [line for line in header.splitlines() if not line.strip().lstrip(">").strip().startswith("Type:")]
    type_line = f"> Type: {ptype}"
    insert_at = next((i + 1 for i, line in enumerate(kept) if "Auto-generated from section markers" in line), None)
    if insert_at is None:
        insert_at = next((i + 1 for i, line in enumerate(kept) if line.startswith("# ")), 0)
    kept.insert(insert_at, type_line)
    return "\n".join(kept).rstrip() + "\n\n"


def index_path_for(file_path: Path) -> Path:
    return file_path.parent / f"{file_path.stem}.index.md"


def process_file(file_path: Path, links_for_file: dict[str, dict[str, list[str]]] | None = None) -> bool:
    """Process a single file. Returns True if index was written."""
    out = index_path_for(file_path)
    existing = out.read_text(encoding="utf-8") if out.is_file() else None
    content = generate_index(file_path, existing, links_for_file)
    if content is None:
        return False
    out.write_text(content, encoding="utf-8")
    print(f"  Generated: {out.name}")
    return True


def write_section_graph(wiki_root: Path):
    """Build and persist the section graph for a wiki root; return (graph, links_index)."""
    graph = build_section_graph(wiki_root)
    payload = json.dumps(graph.to_payload(), indent=2, ensure_ascii=False) + "\n"
    (wiki_root / SECTION_GRAPH_FILE).write_text(payload, encoding="utf-8")
    print(f"  Generated: {SECTION_GRAPH_FILE} ({len(graph.edges)} edge(s), {len(graph.dangling)} dangling)")
    return graph, build_links_index(graph)


def process_all(project_root: Path, wiki_root_selector: str) -> int:
    """Process all indexed leaf pages. Returns count of generated indexes."""
    roots = existing_wiki_roots(project_root) if wiki_root_selector == "all" else [select_wiki_root(project_root, wiki_root_selector)]
    count = 0
    for root in roots:
        if not (root.path / "index.md").is_file():
            continue
        _, links_index = write_section_graph(root.path)
        graph = build_wiki_index_graph(root.path)
        for leaf in graph.leaves:
            if leaf.name == "index.md" or leaf.suffix == ".index.md":
                continue
            print(f"Scanning: {leaf.relative_to(root.path)}")
            leaf_rel = rel_posix(root.path.resolve(), leaf.resolve())
            if process_file(leaf, links_index.get(leaf_rel)):
                count += 1
    return count



def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if not hasattr(stream, "reconfigure"):
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="replace", newline="\n")
        except (OSError, ValueError):
            pass

def main() -> None:
    _configure_stdio()
    parser = argparse.ArgumentParser(description="Generate section index files.")
    parser.add_argument("file_path", nargs="?", help="Wiki file path (relative to wiki root or absolute)")
    parser.add_argument("--all", action="store_true", help="Process all indexed leaf pages")
    parser.add_argument("--wiki-root", choices=["project", "shared", "all"], default="project")
    parser.add_argument("--project-root", default=None)
    args = parser.parse_args()

    project = Path(args.project_root) if args.project_root else repo_root(Path.cwd())

    if args.all:
        count = process_all(project, args.wiki_root)
        print(f"\nGenerated {count} section index file(s).")
    elif args.file_path:
        wiki = select_wiki_root(project, "project" if args.wiki_root == "all" else args.wiki_root)
        file_path = Path(args.file_path)
        if not file_path.is_absolute():
            file_path = wiki.path / file_path
        if not file_path.is_file():
            print(f"Error: file not found: {file_path}", file=sys.stderr)
            sys.exit(1)
        # A single edited page can shift the whole root's graph, so rebuild the
        # root-level .graph.json and feed this file's slice into its index.
        _, links_index = write_section_graph(wiki.path)
        leaf_rel = rel_posix(wiki.path.resolve(), file_path.resolve())
        if not process_file(file_path, links_index.get(leaf_rel)):
            print("No section markers found. No index generated.")
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
