#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

KIND = "superpower-adapter.wiki-context"
SCHEMA_VERSION = 3
CONSTRAINT_CATEGORIES = ("implementation", "test", "review", "general")
ROLE_CATEGORIES = {
    "implementer": ("implementation", "test", "general"),
    "reviewer": ("implementation", "test", "review", "general"),
}


class ValidationError(Exception):
    pass


def _as_list(value: Any, field: str) -> list[Any]:
    if value is None:
        return []
    if not isinstance(value, list):
        raise ValidationError(f"{field} must be a list")
    return value


def _as_dict(value: Any, field: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValidationError(f"{field} must be an object")
    return value


def _load_context(path: Path) -> dict[str, Any]:
    if path.suffix == ".md":
        raise ValidationError("Legacy .wiki-context.md is not supported for selected wiki context rendering; regenerate a schemaVersion 3 .wiki-context.json during planning.")
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValidationError(f"Cannot read wiki context: {exc}") from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValidationError(f"Invalid JSON: {exc}") from exc
    return _as_dict(data, "wiki context")


def _validate_context(data: dict[str, Any], strict: bool) -> list[str]:
    caveats: list[str] = []
    if data.get("schemaVersion") != SCHEMA_VERSION:
        raise ValidationError(f"schemaVersion must be {SCHEMA_VERSION}")
    if data.get("kind") != KIND:
        raise ValidationError(f"kind must be {KIND}")

    pages = _as_list(data.get("wikiPages"), "wikiPages")
    for page_index, page in enumerate(pages):
        page_obj = _as_dict(page, f"wikiPages[{page_index}]")
        _as_dict(page_obj.get("documentContext"), f"wikiPages[{page_index}].documentContext")
        sections = _as_list(page_obj.get("sections"), f"wikiPages[{page_index}].sections")
        for section_index, section in enumerate(sections):
            section_obj = _as_dict(section, f"wikiPages[{page_index}].sections[{section_index}]")
            if strict and "documentContext" in section_obj:
                raise ValidationError(f"wikiPages[{page_index}].sections[{section_index}].documentContext is not allowed; documentContext belongs on the page")
            section_id = section_obj.get("sectionId") or section_obj.get("section_name")
            if not section_id:
                raise ValidationError(f"wikiPages[{page_index}].sections[{section_index}] must include sectionId or section_name")
            constraints = _as_dict(section_obj.get("constraints"), f"wikiPages[{page_index}].sections[{section_index}].constraints")
            unknown = sorted(set(constraints) - set(CONSTRAINT_CATEGORIES))
            if unknown:
                message = f"wikiPages[{page_index}].sections[{section_index}].constraints contains unsupported categories: {', '.join(unknown)}"
                if strict:
                    raise ValidationError(message)
                caveats.append(message)
            for category in CONSTRAINT_CATEGORIES:
                _as_list(constraints.get(category), f"wikiPages[{page_index}].sections[{section_index}].constraints.{category}")
            if "appliesTo" in section_obj:
                _as_list(section_obj.get("appliesTo"), f"wikiPages[{page_index}].sections[{section_index}].appliesTo")
            if "sourceAnchors" in section_obj:
                _as_list(section_obj.get("sourceAnchors"), f"wikiPages[{page_index}].sections[{section_index}].sourceAnchors")
    return caveats


def _selected_pages(data: dict[str, Any]) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    for page in _as_list(data.get("wikiPages"), "wikiPages"):
        page_obj = dict(_as_dict(page, "wikiPages[]"))
        sections = [_as_dict(section, "sections[]") for section in _as_list(page_obj.get("sections"), "sections")]
        if sections:
            page_obj["sections"] = sections
            selected.append(page_obj)
    return selected


def _format_bool(value: Any) -> str:
    return "true" if bool(value) else "false"


def _append_metadata(lines: list[str], page: dict[str, Any]) -> None:
    for key, label in (
        ("root", "Root"),
        ("source", "Source"),
        ("localPath", "Local path"),
        ("wikiPath", "Wiki path"),
    ):
        value = page.get(key)
        if value:
            lines.append(f"- {label}: `{value}`")
    revision = page.get("revision")
    if isinstance(revision, dict):
        commit = revision.get("commitSha") or revision.get("shortSha") or revision.get("ref")
        if commit:
            lines.append(f"- Revision: `{commit}`")


def _append_document_context(lines: list[str], context: dict[str, Any]) -> None:
    lines.append("### Document Context")
    if context.get("title"):
        lines.append(f"- Document: {context['title']}")
    if context.get("overview"):
        lines.append(f"- Overview: {context['overview']}")
    if context.get("scope"):
        lines.append(f"- Scope: {context['scope']}")
    if context.get("contextSource"):
        lines.append(f"- Context source: `{context['contextSource']}`")
    for caveat in _as_list(context.get("caveats"), "documentContext.caveats"):
        lines.append(f"- Caveat: {caveat}")


def _append_constraints(lines: list[str], constraints: dict[str, Any], role: str) -> None:
    for category in ROLE_CATEGORIES[role]:
        items = _as_list(constraints.get(category), f"constraints.{category}")
        if not items:
            continue
        lines.append(f"#### {category.capitalize()} constraints")
        for item in items:
            lines.append(f"- {item}")


def _append_reread(lines: list[str], reread: Any) -> None:
    if not reread:
        return
    reread_obj = _as_dict(reread, "reread")
    lines.append("#### Reread")
    for key, label in (
        ("root", "Root"),
        ("source", "Source"),
        ("filePath", "File path"),
        ("localPath", "Local path"),
        ("wikiPath", "Wiki path"),
        ("sectionId", "Section"),
        ("section_name", "Section"),
    ):
        value = reread_obj.get(key)
        if value:
            lines.append(f"- {label}: `{value}`")
    if reread_obj.get("includeDocumentContext") is not None:
        lines.append(f"- Include document context: `{_format_bool(reread_obj.get('includeDocumentContext'))}`")


def _append_source_anchors(lines: list[str], anchors: Any) -> None:
    source_anchors = _as_list(anchors, "sourceAnchors")
    if not source_anchors:
        return
    lines.append("#### Source anchors")
    for anchor in source_anchors:
        if isinstance(anchor, dict):
            heading = anchor.get("heading")
            excerpt = anchor.get("excerpt")
            prefix = f"{heading}: " if heading else ""
            lines.append(f"- {prefix}{excerpt or ''}".rstrip())
        else:
            lines.append(f"- {anchor}")


def render_markdown(data: dict[str, Any], role: str) -> str:
    pages = _selected_pages(data)
    if not pages:
        return "No selected wiki constraints for this role."

    lines: list[str] = ["## Wiki Constraints", ""]
    for page in pages:
        display = page.get("displayPath") or page.get("path") or page.get("wikiPath") or "unknown wiki page"
        lines.append(f"### Wiki Page: `{display}`")
        _append_metadata(lines, page)
        page_caveats = _as_list(page.get("caveats"), "page.caveats")
        for caveat in page_caveats:
            lines.append(f"- Caveat: {caveat}")
        lines.append("")
        _append_document_context(lines, _as_dict(page.get("documentContext"), "documentContext"))
        lines.append("")

        for section in _as_list(page.get("sections"), "sections"):
            section_id = section.get("sectionId") or section.get("section_name")
            lines.append(f"### Section: `{section_id}`")
            if section.get("relevanceTo"):
                lines.append(f"- Relevance to: {section['relevanceTo']}")
            applies = ", ".join(str(item) for item in _as_list(section.get("appliesTo"), "appliesTo"))
            if applies:
                lines.append(f"- Applies to (legacy): {applies}")
            if section.get("relevance"):
                lines.append(f"- Relevance: {section['relevance']}")
            if section.get("confidence"):
                lines.append(f"- Confidence: {section['confidence']}")
            if section.get("reason"):
                lines.append(f"- Reason: {section['reason']}")
            lines.append(f"- Hard constraint: `{_format_bool(section.get('hardConstraint'))}`")
            for caveat in _as_list(section.get("caveats"), "section.caveats"):
                lines.append(f"- Caveat: {caveat}")
            _append_constraints(lines, _as_dict(section.get("constraints"), "constraints"), role)
            _append_reread(lines, section.get("reread"))
            _append_source_anchors(lines, section.get("sourceAnchors"))
            lines.append("")
    for caveat in _as_list(data.get("caveats"), "caveats"):
        lines.append(f"- Context caveat: {caveat}")
    return "\n".join(lines).rstrip()


def render_reread_list(data: dict[str, Any]) -> str:
    lines: list[str] = []
    for page in _selected_pages(data):
        for section in _as_list(page.get("sections"), "sections"):
            if not section.get("hardConstraint") or not section.get("reread"):
                continue
            section_id = section.get("sectionId") or section.get("section_name")
            lines.append(json.dumps({"displayPath": page.get("displayPath"), "sectionId": section_id, "reread": section.get("reread")}, ensure_ascii=False, sort_keys=True))
    return "\n".join(lines) if lines else "No hard-constraint rereads for selected wiki context."


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate and render schemaVersion 3 selected wiki context JSON.")
    parser.add_argument("context_path", help="Path to docs/superpowers/plans/<plan-stem>.wiki-context.json")
    parser.add_argument("--task", action="append", default=[], help="Deprecated compatibility option; selected wiki context is not task-filtered")
    parser.add_argument("--role", choices=["implementer", "reviewer"], default="implementer")
    parser.add_argument("--format", choices=["markdown"], default="markdown")
    parser.add_argument("--validate-only", action="store_true")
    parser.add_argument("--reread-list", action="store_true")
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()

    try:
        data = _load_context(Path(args.context_path))
        caveats = _validate_context(data, args.strict)
        if args.validate_only:
            for caveat in caveats:
                print(f"Warning: {caveat}", file=sys.stderr)
            print("wiki context JSON is valid")
            return 0
        if args.reread_list:
            print(render_reread_list(data))
            return 0
        print(render_markdown(data, args.role))
        return 0
    except ValidationError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
