#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from wiki_common import build_wiki_index_graph, rel_posix, repo_root

VALID = "valid"
WARNING = "warning"
INVALID = "invalid"
UPDATE_PREFIX = "## Update: "
REQUIRED_UPDATE_HEADERS = ["### Why", "### Rules / Contracts", "### Validation / Notes"]
OVERSIZED_THRESHOLDS = [
    (800, 40000, "critical"),
    (500, 24000, "large"),
    (250, 12000, "notice"),
]


def update_block_ranges(lines: list[str]) -> list[tuple[int, int]]:
    starts = [i for i, line in enumerate(lines) if line.startswith(UPDATE_PREFIX)]
    ranges: list[tuple[int, int]] = []
    for index, start in enumerate(starts):
        end = starts[index + 1] if index + 1 < len(starts) else len(lines)
        ranges.append((start, end))
    return ranges


def has_unclosed_fence(text: str) -> bool:
    open_fence: str | None = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("````"):
            fence = "````"
        elif stripped.startswith("```"):
            fence = "```"
        else:
            continue
        if open_fence is None:
            open_fence = fence
        elif stripped.startswith(open_fence):
            open_fence = None
    return open_fence is not None


def oversized_level(lines_count: int, chars_count: int) -> str | None:
    for line_threshold, char_threshold, level in OVERSIZED_THRESHOLDS:
        if lines_count >= line_threshold or chars_count >= char_threshold:
            return level
    return None


def check_leaf(wiki_root: Path, path: Path) -> tuple[list[str], list[str], dict | None]:
    warnings: list[str] = []
    errors: list[str] = []
    oversized: dict | None = None
    rel = rel_posix(wiki_root.resolve(), path)
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return warnings, [f"Could not read {rel}: {exc}"], oversized

    if not text.strip():
        warnings.append(f"Empty indexed wiki page: {rel}")
    if "<fill-me>" in text:
        warnings.append(f"Placeholder remains in {rel}: <fill-me>")
    if has_unclosed_fence(text):
        errors.append(f"Unclosed markdown fence in {rel}")

    lines = text.splitlines()
    lines_count = len(lines)
    chars_count = len(text)
    level = oversized_level(lines_count, chars_count)
    if level:
        oversized = {
            "path": rel,
            "lines": lines_count,
            "chars": chars_count,
            "level": level,
        }
        warnings.append(f"Oversized indexed wiki page: {rel} ({lines_count} lines, {chars_count} chars, {level})")

    for start, end in update_block_ranges(lines):
        block = {line.strip() for line in lines[start:end]}
        missing = [header for header in REQUIRED_UPDATE_HEADERS if header not in block]
        if missing:
            title = lines[start].strip()
            warnings.append(f"Incomplete update block in {rel} ({title}): missing {', '.join(missing)}")

    return warnings, errors, oversized


def check_wiki_tree() -> dict:
    root = repo_root(Path.cwd())
    wiki_root = root / ".superpowers" / "wiki"
    graph = build_wiki_index_graph(wiki_root)
    warnings = list(graph.warnings)
    errors: list[str] = []
    oversized_pages: list[dict] = []

    for leaf in graph.leaves:
        leaf_warnings, leaf_errors, oversized = check_leaf(wiki_root, leaf)
        warnings.extend(leaf_warnings)
        errors.extend(leaf_errors)
        if oversized:
            oversized_pages.append(oversized)

    if not graph.leaves:
        warnings.append("No indexed leaf wiki pages found")

    status = INVALID if errors else WARNING if warnings else VALID
    return {
        "status": status,
        "wikiRoot": str(wiki_root),
        "filesChecked": len(graph.files),
        "indexesChecked": len(graph.indexes),
        "leavesChecked": len(graph.leaves),
        "oversizedPages": oversized_pages,
        "warnings": warnings,
        "errors": errors,
        "mechanicalOnly": True,
    }


def render_text(result: dict) -> str:
    status = result["status"]
    heading = {
        VALID: "WIKI_UPDATE_CHECK_VALID: wiki index and leaf mechanics look valid",
        WARNING: "WIKI_UPDATE_CHECK_WARN: mechanical warnings found",
        INVALID: "WIKI_UPDATE_CHECK_INVALID: mechanical errors found",
    }[status]
    lines = [heading, f"Files checked: {result['filesChecked']}"]
    if result["oversizedPages"]:
        lines.extend(["", "Oversized pages:"])
        lines.extend(
            f"- {page['path']} ({page['lines']} lines, {page['chars']} chars, {page['level']})"
            for page in result["oversizedPages"]
        )
    if result["warnings"]:
        lines.extend(["", "Warnings:"])
        lines.extend(f"- {warning}" for warning in result["warnings"])
    if result["errors"]:
        lines.extend(["", "Errors:"])
        lines.extend(f"- {error}" for error in result["errors"])
    lines.extend(["", "This is a mechanical validator only; it does not decide whether durable knowledge exists."])
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Validate .superpowers/wiki index and leaf mechanics.")
    parser.add_argument("--json", action="store_true", help="Emit JSON validation result.")
    parser.add_argument("--summary", default="", help="Deprecated compatibility option; ignored.")
    parser.add_argument("--changed-file", action="append", default=[], help="Deprecated compatibility option; ignored.")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    result = check_wiki_tree()
    if args.summary or args.changed_file:
        result["warnings"].append("Deprecated semantic inputs were ignored: --summary / --changed-file")
        if result["status"] == VALID:
            result["status"] = WARNING
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(render_text(result))
    return 1 if result["status"] == INVALID else 0


if __name__ == "__main__":
    raise SystemExit(main())
