#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

KIND = "superpower-adapter.wiki-context"
SCHEMA_VERSION = 4
CONSTRAINT_CATEGORIES = ("implementation", "test", "review", "general")
ROLE_CATEGORIES = {
    "implementer": ("implementation", "test", "general"),
    "reviewer": ("implementation", "test", "review", "general"),
}
DESTINATION_KINDS = {"task-bound", "global", "planning-only"}
SCAFFOLD_GENERATED_BY = "superpower-adapter"
# taskRouting block emitted by --scaffold. These are the pre-confirmation values: the author flips
# status to "confirmed" and selectedSectionsFrozen to true once routing is final, and
# --bind-fingerprints + --execution-ready then gate it. The other three are fixed declared strings.
SCAFFOLD_TASK_ROUTING = {
    "status": "candidate_sections_only",
    "planTaskFormat": "superpower-adapter-plan-task-heading-v1",
    "fingerprintAlgorithm": "sha256:superpower-adapter-task-text-v1",
    "selectedSectionsFrozen": False,
    "refreshPolicy": "refresh-taskWikiRefs-and-fingerprints-only",
}
TASK_HEADING_RE = re.compile(r"^### Task\s+([A-Za-z0-9][A-Za-z0-9_-]*):\s*(.+?)\s*$")
TASK_OR_HIGHER_HEADING_RE = re.compile(r"^#{1,3}\s+")
HEX_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
# A digest of 64 identical hex chars (0000…, 1111…, ffff…) is an authoring placeholder, never a
# real sha256. Rejecting it stops copy-pasted skeleton fingerprints from passing validation and
# only blowing up later at the execution-side --fingerprint-preflight.
PLACEHOLDER_FINGERPRINT_RE = re.compile(r"^([0-9a-f])\1{63}$")


class ValidationError(Exception):
    pass


class FingerprintError(Exception):
    pass


def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if not hasattr(stream, "reconfigure"):
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="replace", newline="\n")
        except (OSError, ValueError):
            pass


def _as_list(value: Any, field: str) -> list[Any]:
    if value is None:
        return []
    if not isinstance(value, list):
        raise ValidationError(f"{field} must be a list")
    return value


def _as_dict(value: Any, field: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValidationError(f"{field} must be an object")
    return value


def _load_json(path: Path, label: str) -> dict[str, Any]:
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValidationError(f"Cannot read {label}: {exc}") from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValidationError(f"Invalid JSON in {label}: {exc}") from exc
    return _as_dict(data, label)


def _load_context(path: Path) -> dict[str, Any]:
    if path.suffix == ".md":
        raise ValidationError("Legacy .wiki-context.md is not supported for selected wiki context rendering; regenerate a schemaVersion 4 .wiki-context.json during planning.")
    return _load_json(path, "wiki context")


def _section_id(section: dict[str, Any]) -> str:
    section_id = section.get("sectionId") or section.get("section_name")
    if not section_id:
        raise ValidationError("section must include sectionId or section_name")
    return str(section_id)


def _section_key(page: dict[str, Any], section: dict[str, Any]) -> tuple[str, str, str, str]:
    root = str(page.get("root") or "")
    source = str(page.get("source") or "")
    path = str(page.get("localPath") or page.get("wikiPath") or page.get("displayPath") or page.get("path") or "")
    return (root, source, path, _section_id(section))


def _iter_sections(data: dict[str, Any]) -> list[tuple[dict[str, Any], dict[str, Any]]]:
    pairs: list[tuple[dict[str, Any], dict[str, Any]]] = []
    for page in _as_list(data.get("wikiPages"), "wikiPages"):
        page_obj = _as_dict(page, "wikiPages[]")
        for section in _as_list(page_obj.get("sections"), "sections"):
            pairs.append((page_obj, _as_dict(section, "sections[]")))
    return pairs


def _validate_task_fingerprint(task_ref: dict[str, Any], field: str) -> None:
    fingerprint = task_ref.get("taskFingerprint")
    if not isinstance(fingerprint, str) or not HEX_SHA256_RE.match(fingerprint):
        raise ValidationError(f"{field}.taskFingerprint must be a 64-character lowercase sha256 hex digest")
    if PLACEHOLDER_FINGERPRINT_RE.match(fingerprint):
        raise ValidationError(
            f"{field}.taskFingerprint looks like a placeholder; run --bind-fingerprints --plan-path <plan> to stamp the real fingerprint"
        )


def _validate_execution_ready(data: dict[str, Any]) -> None:
    task_routing = _as_dict(data.get("taskRouting"), "taskRouting")
    if task_routing.get("status") != "confirmed":
        raise ValidationError("taskRouting.status must be confirmed for execution-ready wiki context")
    if task_routing.get("selectedSectionsFrozen") is not True:
        raise ValidationError("taskRouting.selectedSectionsFrozen must be true for execution-ready wiki context")

    # taskWikiRefs is the task roster + fingerprint anchor only. In schemaVersion 4 there are no per-task
    # wiki refs and no globalWikiRefs collection; routing lives entirely on each section's destination.
    # Collect valid task ids first so task-bound sections can be checked against them.
    task_refs = _as_list(data.get("taskWikiRefs"), "taskWikiRefs")
    task_ids: set[str] = set()
    for index, task_ref in enumerate(task_refs):
        task_obj = _as_dict(task_ref, f"taskWikiRefs[{index}]")
        task_id = task_obj.get("taskId")
        if not isinstance(task_id, str) or not task_id.strip():
            raise ValidationError(f"taskWikiRefs[{index}].taskId is required")
        if task_id in task_ids:
            raise ValidationError(f"taskWikiRefs[{index}].taskId duplicates {task_id}")
        task_ids.add(task_id)
        if not isinstance(task_obj.get("taskTitle"), str) or not task_obj.get("taskTitle", "").strip():
            raise ValidationError(f"taskWikiRefs[{index}].taskTitle is required")
        _validate_task_fingerprint(task_obj, f"taskWikiRefs[{index}]")

    for page, section in _iter_sections(data):
        key = _section_key(page, section)
        destination = _as_dict(section.get("destination"), f"section {key}.destination")
        kind = destination.get("kind")
        if kind not in DESTINATION_KINDS:
            raise ValidationError(f"section {key}.destination.kind must be one of {', '.join(sorted(DESTINATION_KINDS))}")
        if not str(destination.get("reason") or "").strip():
            raise ValidationError(f"section {key}.destination.reason is required")
        relevance = section.get("relevance")
        if (section.get("hardConstraint") or relevance == "direct") and kind == "planning-only":
            raise ValidationError(f"hard/direct section {key} cannot have planning-only destination")
        # Hard constraints are authoritative and must be reread in full at execution time, not
        # only distilled into planning bullets. render_reread_list() silently skips hard sections
        # that lack a reread block, so requiring it here is a load-bearing backstop: do not relax it
        # to save planning tokens (guarded by tests/wiki-context-json-render-smoke.sh HARD_NO_REREAD).
        if section.get("hardConstraint"):
            reread = section.get("reread")
            if not isinstance(reread, dict) or not reread:
                raise ValidationError(
                    f"hard-constraint section {key} must include a reread block so execution can reread the full section text"
                )
        # Routing: task-bound sections name the plan tasks they bind to (the one genuinely authored
        # mapping); global/planning-only carry no task list. globalWikiRefs/wikiRefs are gone -- the
        # renderer derives task scope straight from destination.kind and destination.tasks.
        tasks = destination.get("tasks")
        if kind == "task-bound":
            task_list = _as_list(tasks, f"section {key}.destination.tasks")
            if not task_list:
                raise ValidationError(f"task-bound section {key} must list one or more plan task ids in destination.tasks")
            seen_tasks: set[str] = set()
            for bound_id in task_list:
                if not isinstance(bound_id, str) or not bound_id.strip():
                    raise ValidationError(f"section {key}.destination.tasks entries must be non-empty task id strings")
                if bound_id in seen_tasks:
                    raise ValidationError(f"section {key}.destination.tasks duplicates {bound_id}")
                seen_tasks.add(bound_id)
                if bound_id not in task_ids:
                    raise ValidationError(f"task-bound section {key}.destination.tasks references unknown task id {bound_id}")
        elif tasks:
            raise ValidationError(f"{kind} section {key} must not set destination.tasks")


def _validate_context(data: dict[str, Any], strict: bool, execution_ready: bool = False) -> list[str]:
    caveats: list[str] = []
    if data.get("schemaVersion") != SCHEMA_VERSION:
        raise ValidationError(f"schemaVersion must be {SCHEMA_VERSION}")
    if data.get("kind") != KIND:
        raise ValidationError(f"kind must be {KIND}")

    # Optional shared-wiki identity (which github_mcp shared wiki this plan was built against).
    # Tolerated when absent; lightly type-checked when present so execution can compare it to the
    # connected server's repoUrl and detect rebinding drift.
    shared_wiki = data.get("sharedWiki")
    if shared_wiki is not None:
        shared_wiki_obj = _as_dict(shared_wiki, "sharedWiki")
        repo_url = shared_wiki_obj.get("repoUrl")
        if repo_url is not None and (not isinstance(repo_url, str) or not repo_url.strip()):
            raise ValidationError("sharedWiki.repoUrl must be a non-empty string when present")

    pages = _as_list(data.get("wikiPages"), "wikiPages")
    for page_index, page in enumerate(pages):
        page_obj = _as_dict(page, f"wikiPages[{page_index}]")
        _as_dict(page_obj.get("documentContext"), f"wikiPages[{page_index}].documentContext")
        sections = _as_list(page_obj.get("sections"), f"wikiPages[{page_index}].sections")
        for section_index, section in enumerate(sections):
            section_obj = _as_dict(section, f"wikiPages[{page_index}].sections[{section_index}]")
            if strict and "documentContext" in section_obj:
                raise ValidationError(f"wikiPages[{page_index}].sections[{section_index}].documentContext is not allowed; documentContext belongs on the page")
            section_id = section_obj.get("sectionId") or section_obj.get("section_name")
            if not section_id:
                raise ValidationError(f"wikiPages[{page_index}].sections[{section_index}] must include sectionId or section_name")
            constraints = _as_dict(section_obj.get("constraints"), f"wikiPages[{page_index}].sections[{section_index}].constraints")
            unknown = sorted(set(constraints) - set(CONSTRAINT_CATEGORIES))
            if unknown:
                message = f"wikiPages[{page_index}].sections[{section_index}].constraints contains unsupported categories: {', '.join(unknown)}"
                if strict:
                    raise ValidationError(message)
                caveats.append(message)
            for category in CONSTRAINT_CATEGORIES:
                _as_list(constraints.get(category), f"wikiPages[{page_index}].sections[{section_index}].constraints.{category}")
            if strict and "appliesTo" in section_obj:
                raise ValidationError(f"wikiPages[{page_index}].sections[{section_index}].appliesTo is removed in schemaVersion {SCHEMA_VERSION}; bind tasks via section.destination.tasks instead")
            if "sourceAnchors" in section_obj:
                _as_list(section_obj.get("sourceAnchors"), f"wikiPages[{page_index}].sections[{section_index}].sourceAnchors")
    if execution_ready:
        _validate_execution_ready(data)
    return caveats


def _selected_pages(data: dict[str, Any], section_keys: set[tuple[str, str, str, str]] | None = None) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    for page in _as_list(data.get("wikiPages"), "wikiPages"):
        page_obj = dict(_as_dict(page, "wikiPages[]"))
        sections = []
        for section in _as_list(page_obj.get("sections"), "sections"):
            section_obj = _as_dict(section, "sections[]")
            if section_keys is not None and _section_key(page_obj, section_obj) not in section_keys:
                continue
            sections.append(section_obj)
        if sections:
            page_obj["sections"] = sections
            selected.append(page_obj)
    return selected


def _task_section_keys(data: dict[str, Any], task_id: str) -> set[tuple[str, str, str, str]]:
    # The task must exist in the taskWikiRefs roster (preserves the "unknown task id" guard for rendering).
    matches = [
        _as_dict(task_ref, "taskWikiRefs[]")
        for task_ref in _as_list(data.get("taskWikiRefs"), "taskWikiRefs")
        if _as_dict(task_ref, "taskWikiRefs[]").get("taskId") == task_id
    ]
    if len(matches) != 1:
        raise ValidationError(f"taskWikiRefs must contain exactly one entry for taskId {task_id}")
    # Routing is read straight from each section's destination: global sections reach every task; a
    # task-bound section reaches this task only when its destination.tasks lists this task id.
    keys: set[tuple[str, str, str, str]] = set()
    for page, section in _iter_sections(data):
        destination = section.get("destination")
        if not isinstance(destination, dict):
            continue
        kind = destination.get("kind")
        if kind == "global":
            keys.add(_section_key(page, section))
        elif kind == "task-bound" and task_id in _as_list(destination.get("tasks"), "destination.tasks"):
            keys.add(_section_key(page, section))
    return keys


def _format_bool(value: Any) -> str:
    return "true" if bool(value) else "false"


def _append_metadata(lines: list[str], page: dict[str, Any]) -> None:
    for key, label in (
        ("root", "Root"),
        ("source", "Source"),
        ("localPath", "Local path"),
        ("wikiPath", "Wiki path"),
    ):
        value = page.get(key)
        if value:
            lines.append(f"- {label}: `{value}`")
    revision = page.get("revision")
    if isinstance(revision, dict):
        commit = revision.get("commitSha") or revision.get("shortSha") or revision.get("ref")
        if commit:
            lines.append(f"- Revision: `{commit}`")


def _append_document_context(lines: list[str], context: dict[str, Any]) -> None:
    lines.append("### Document Context")
    if context.get("title"):
        lines.append(f"- Document: {context['title']}")
    if context.get("overview"):
        lines.append(f"- Overview: {context['overview']}")
    if context.get("scope"):
        lines.append(f"- Scope: {context['scope']}")
    if context.get("contextSource"):
        lines.append(f"- Context source: `{context['contextSource']}`")
    for caveat in _as_list(context.get("caveats"), "documentContext.caveats"):
        lines.append(f"- Caveat: {caveat}")


def _append_constraints(lines: list[str], constraints: dict[str, Any], role: str) -> None:
    for category in ROLE_CATEGORIES[role]:
        items = _as_list(constraints.get(category), f"constraints.{category}")
        if not items:
            continue
        lines.append(f"#### {category.capitalize()} constraints")
        for item in items:
            lines.append(f"- {item}")


def _append_reread(lines: list[str], reread: Any) -> None:
    if not reread:
        return
    reread_obj = _as_dict(reread, "reread")
    lines.append("#### Reread")
    for key, label in (
        ("root", "Root"),
        ("source", "Source"),
        ("filePath", "File path"),
        ("localPath", "Local path"),
        ("wikiPath", "Wiki path"),
        ("sectionId", "Section"),
        ("section_name", "Section"),
    ):
        value = reread_obj.get(key)
        if value:
            lines.append(f"- {label}: `{value}`")
    if reread_obj.get("includeDocumentContext") is not None:
        lines.append(f"- Include document context: `{_format_bool(reread_obj.get('includeDocumentContext'))}`")


def _append_source_anchors(lines: list[str], anchors: Any) -> None:
    source_anchors = _as_list(anchors, "sourceAnchors")
    if not source_anchors:
        return
    lines.append("#### Source anchors")
    for anchor in source_anchors:
        if isinstance(anchor, dict):
            heading = anchor.get("heading")
            excerpt = anchor.get("excerpt")
            prefix = f"{heading}: " if heading else ""
            lines.append(f"- {prefix}{excerpt or ''}".rstrip())
        else:
            lines.append(f"- {anchor}")


def render_markdown(data: dict[str, Any], role: str, task_id: str | None = None) -> str:
    section_keys = _task_section_keys(data, task_id) if task_id else None
    pages = _selected_pages(data, section_keys)
    if not pages:
        if task_id:
            return f"No selected wiki constraints for task `{task_id}` and role `{role}`."
        return "No selected wiki constraints for this role."

    lines: list[str] = ["## Wiki Constraints", ""]
    if task_id:
        lines.append(f"- Task ID: `{task_id}`")
        lines.append("")
    shared_wiki = data.get("sharedWiki")
    if isinstance(shared_wiki, dict):
        repo_url = shared_wiki.get("repoUrl")
        revision = shared_wiki.get("revision")
        commit = None
        if isinstance(revision, dict):
            commit = revision.get("commitSha") or revision.get("shortSha") or revision.get("ref")
        identity_bits: list[str] = []
        if repo_url:
            identity_bits.append(f"repo `{repo_url}`")
        if commit:
            identity_bits.append(f"revision `{commit}`")
        if identity_bits:
            lines.append(f"- Shared wiki source: {', '.join(identity_bits)}")
            lines.append("- Before trusting github_mcp rereads, confirm the connected shared-wiki MCP still serves this repo; a mismatch means the project rebound its shared wiki after planning.")
            lines.append("")
    for page in pages:
        display = page.get("displayPath") or page.get("path") or page.get("wikiPath") or "unknown wiki page"
        lines.append(f"### Wiki Page: `{display}`")
        _append_metadata(lines, page)
        page_caveats = _as_list(page.get("caveats"), "page.caveats")
        for caveat in page_caveats:
            lines.append(f"- Caveat: {caveat}")
        lines.append("")
        _append_document_context(lines, _as_dict(page.get("documentContext"), "documentContext"))
        lines.append("")

        for section in _as_list(page.get("sections"), "sections"):
            section_id = section.get("sectionId") or section.get("section_name")
            lines.append(f"### Section: `{section_id}`")
            if section.get("relevanceTo"):
                lines.append(f"- Relevance to: {section['relevanceTo']}")
            if section.get("relevance"):
                lines.append(f"- Relevance: {section['relevance']}")
            if section.get("confidence"):
                lines.append(f"- Confidence: {section['confidence']}")
            if section.get("reason"):
                lines.append(f"- Reason: {section['reason']}")
            lines.append(f"- Hard constraint: `{_format_bool(section.get('hardConstraint'))}`")
            destination = section.get("destination")
            if isinstance(destination, dict):
                lines.append(f"- Destination: `{destination.get('kind')}`")
                if destination.get("reason"):
                    lines.append(f"- Destination reason: {destination['reason']}")
            for caveat in _as_list(section.get("caveats"), "section.caveats"):
                lines.append(f"- Caveat: {caveat}")
            _append_constraints(lines, _as_dict(section.get("constraints"), "constraints"), role)
            _append_reread(lines, section.get("reread"))
            _append_source_anchors(lines, section.get("sourceAnchors"))
            lines.append("")
    for caveat in _as_list(data.get("caveats"), "caveats"):
        lines.append(f"- Context caveat: {caveat}")
    return "\n".join(lines).rstrip()


def _load_project_section_graph() -> dict[str, Any] | None:
    """Load the project wiki's derived .graph.json, or None if unavailable.

    Read lazily and defensively: depends-on closure is an additive convenience, so any
    failure to locate/parse the graph must degrade to "no closure", never break rereads.
    """
    try:
        from wiki_common import PROJECT_WIKI_REL, repo_root  # local import keeps the renderer stdlib-only otherwise

        graph_path = repo_root(Path.cwd()) / PROJECT_WIKI_REL / ".graph.json"
        if not graph_path.is_file():
            return None
        graph = json.loads(graph_path.read_text(encoding="utf-8"))
        return graph if isinstance(graph, dict) else None
    except Exception:
        return None


def _depends_on_closure_entries(
    project_source_nodes: list[str],
    emitted_keys: set[tuple[str, str]],
) -> list[dict[str, Any]]:
    """1-hop selection-time closure of depends-on edges for hard-constraint sections.

    For each selected project hard-constraint section, pull its `depends-on` targets into
    the reread set so a load-bearing dependency is never left behind a link at execution.
    Bounded to one hop (a target's own depends-on edges are NOT followed) and deduped
    against the directly-emitted rereads. Returns synthesized reread entries (project root,
    section-level targets only); page-level depends-on targets are skipped (not rereadable
    as a section).
    """
    if not project_source_nodes:
        return []
    graph = _load_project_section_graph()
    if not graph:
        return []

    from wiki_common import one_hop_neighbors  # local import keeps the renderer stdlib-only otherwise

    slices = one_hop_neighbors(graph, project_source_nodes)
    entries: list[dict[str, Any]] = []
    for source_node in project_source_nodes:
        for edge in slices.get(source_node, {}).get("out", []):
            if edge.get("type") != "depends-on":
                continue
            target_node = edge.get("to") or ""
            if "#" not in target_node:
                continue  # whole-page depends-on is not rereadable as a single section
            local_path, _, section_id = target_node.rpartition("#")
            if not local_path or not section_id:
                continue
            key = ("project", f"{local_path}#{section_id}")
            if key in emitted_keys:
                continue
            emitted_keys.add(key)
            entries.append({
                "root": "project",
                "source": "local",
                "displayPath": local_path,
                "localPath": local_path,
                "wikiPath": local_path,
                "sectionId": section_id,
                "reread": {"localPath": local_path, "sectionId": section_id, "includeDocumentContext": True},
                "closureType": "depends-on",
                "closedVia": source_node,
            })
    return entries


def render_reread_list(data: dict[str, Any], task_id: str | None = None) -> str:
    section_keys = _task_section_keys(data, task_id) if task_id else None
    entries: list[dict[str, Any]] = []
    emitted_keys: set[tuple[str, str]] = set()
    project_source_nodes: list[str] = []

    for page in _selected_pages(data, section_keys):
        root = page.get("root")
        local_path = page.get("localPath")
        for section in _as_list(page.get("sections"), "sections"):
            if not section.get("hardConstraint") or not section.get("reread"):
                continue
            section_id = section.get("sectionId") or section.get("section_name")
            entry = {
                "root": root,
                "source": page.get("source"),
                "displayPath": page.get("displayPath"),
                "localPath": local_path,
                "wikiPath": page.get("wikiPath"),
                "revision": page.get("revision"),
                "sectionId": section_id,
                "reread": section.get("reread"),
            }
            entries.append({key: value for key, value in entry.items() if value is not None})
            # Track project-root hard sections so we can close their depends-on edges below.
            if root in (None, "project") and local_path and section_id:
                emitted_keys.add(("project", f"{local_path}#{section_id}"))
                project_source_nodes.append(f"{local_path}#{section_id}")

    entries.extend(_depends_on_closure_entries(project_source_nodes, emitted_keys))

    lines = [json.dumps(entry, ensure_ascii=False, sort_keys=True) for entry in entries]
    if lines:
        return "\n".join(lines)
    if task_id:
        return f"No hard-constraint rereads for task `{task_id}`."
    return "No hard-constraint rereads for selected wiki context."


def _normalize_task_text(task_text: str) -> str:
    lines = task_text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    lines = [line.rstrip() for line in lines]
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines) + "\n"


def _task_fingerprint(task_text: str) -> str:
    normalized = _normalize_task_text(task_text)
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def extract_plan_tasks(plan_path: Path) -> dict[str, dict[str, str]]:
    try:
        text = plan_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise FingerprintError(f"Cannot read plan: {exc}") from exc
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    starts: list[tuple[int, str, str]] = []
    for index, line in enumerate(lines):
        match = TASK_HEADING_RE.match(line)
        if match:
            starts.append((index, match.group(1), match.group(2)))
    if not starts:
        raise FingerprintError("No stable task headings found; expected numeric headings like `### Task 1: Title`")

    tasks: dict[str, dict[str, str]] = {}
    for position, (start, task_id, title) in enumerate(starts):
        if task_id in tasks:
            raise FingerprintError(f"Duplicate task id in plan: {task_id}")
        end = len(lines)
        next_task_start = starts[position + 1][0] if position + 1 < len(starts) else None
        for index in range(start + 1, len(lines)):
            if next_task_start is not None and index == next_task_start:
                end = index
                break
            if TASK_OR_HIGHER_HEADING_RE.match(lines[index]) and not lines[index].startswith("####"):
                end = index
                break
        task_text = "\n".join(lines[start:end])
        tasks[task_id] = {"title": title, "text": task_text, "hash": _task_fingerprint(task_text)}
    return tasks


def fingerprint_preflight(data: dict[str, Any], plan_path: Path) -> str:
    plan_tasks = extract_plan_tasks(plan_path)
    sidecar_tasks: dict[str, dict[str, Any]] = {}
    errors: list[str] = []
    for index, task_ref in enumerate(_as_list(data.get("taskWikiRefs"), "taskWikiRefs")):
        task_obj = _as_dict(task_ref, f"taskWikiRefs[{index}]")
        task_id = task_obj.get("taskId")
        if not isinstance(task_id, str) or not task_id:
            errors.append(f"taskWikiRefs[{index}] missing taskId")
            continue
        if task_id in sidecar_tasks:
            errors.append(f"duplicate sidecar taskId: {task_id}")
            continue
        sidecar_tasks[task_id] = task_obj

    for task_id, task in plan_tasks.items():
        sidecar = sidecar_tasks.get(task_id)
        if not sidecar:
            errors.append(f"plan task missing from taskWikiRefs: {task_id}")
            continue
        fingerprint = sidecar.get("taskFingerprint")
        if fingerprint != task["hash"]:
            errors.append(f"fingerprint mismatch for {task_id}: expected {fingerprint}, current {task['hash']}")

    for task_id in sorted(set(sidecar_tasks) - set(plan_tasks)):
        errors.append(f"taskWikiRefs contains task not found in plan: {task_id}")

    if errors:
        raise FingerprintError("\n".join(errors))
    return f"fingerprint preflight passed for {len(plan_tasks)} task(s)"


def bind_fingerprints(data: dict[str, Any], plan_path: Path) -> tuple[int, int, list[str]]:
    """Stamp each taskWikiRefs entry's taskFingerprint from the current plan task text.

    Routing (which sections bind to which task) stays author-owned; only the mechanical sha256 of
    the normalized plan task text is (re)written here, from the single source of truth in this
    module. Mirrors fingerprint_preflight's structural checks and refuses to write on any mismatch,
    so a successful bind guarantees the execution-side --fingerprint-preflight will pass.
    """
    plan_tasks = extract_plan_tasks(plan_path)
    sidecar_tasks: dict[str, dict[str, Any]] = {}
    errors: list[str] = []
    for index, task_ref in enumerate(_as_list(data.get("taskWikiRefs"), "taskWikiRefs")):
        task_obj = _as_dict(task_ref, f"taskWikiRefs[{index}]")
        task_id = task_obj.get("taskId")
        if not isinstance(task_id, str) or not task_id:
            errors.append(f"taskWikiRefs[{index}] missing taskId")
            continue
        if task_id in sidecar_tasks:
            errors.append(f"duplicate sidecar taskId: {task_id}")
            continue
        sidecar_tasks[task_id] = task_obj

    for task_id in sorted(set(sidecar_tasks) - set(plan_tasks)):
        errors.append(f"taskWikiRefs contains task not found in plan: {task_id}")
    for task_id in plan_tasks:
        if task_id not in sidecar_tasks:
            errors.append(f"plan task missing from taskWikiRefs: {task_id}")
    if errors:
        raise FingerprintError("\n".join(errors))

    changed = 0
    for task_id, task_obj in sidecar_tasks.items():
        current_hash = plan_tasks[task_id]["hash"]
        if task_obj.get("taskFingerprint") != current_hash:
            task_obj["taskFingerprint"] = current_hash
            changed += 1
    return len(sidecar_tasks), changed, sorted(sidecar_tasks)


def _default_destination_kind(section: dict[str, Any]) -> str:
    """Starting-guess routing for a freshly scaffolded section.

    hard/direct sections may never be planning-only (execution-ready validation rejects that), so they
    default to task-bound; soft context defaults to planning-only. The author confirms or overrides the
    kind and MUST supply a non-empty destination.reason before --execution-ready passes.
    """
    if section.get("hardConstraint") or section.get("relevance") == "direct":
        return "task-bound"
    return "planning-only"


def _derive_reread(page: dict[str, Any], section_id: str) -> dict[str, Any]:
    """Mechanically build the reread block every hardConstraint section needs.

    Derivable entirely from the page identity plus the section id, this removes the single most common
    authoring omission (a hard section missing reread, which fails execution-ready validation). Mirrors
    the page's path shape: localPath for local pages, wikiPath for github_mcp pages.
    """
    reread: dict[str, Any] = {"root": page.get("root"), "source": page.get("source")}
    if page.get("localPath"):
        reread["localPath"] = page["localPath"]
    if page.get("wikiPath"):
        reread["wikiPath"] = page["wikiPath"]
    reread["sectionId"] = section_id
    reread["includeDocumentContext"] = True
    return {key: value for key, value in reread.items() if value is not None}


def _scaffold_section(page: dict[str, Any], raw_section: Any, page_index: int, section_index: int) -> dict[str, Any]:
    where = f"selection wikiPages[{page_index}].sections[{section_index}]"
    section = _as_dict(raw_section, where)
    section_id = section.get("sectionId") or section.get("section_name")
    if not section_id:
        raise ValidationError(f"{where} must include sectionId or section_name")
    section_id = str(section_id)

    out: dict[str, Any] = {"sectionId": section_id, "section_name": str(section.get("section_name") or section_id)}
    for field_name in ("readDepth", "relevance", "confidence", "reason", "relevanceTo"):
        if section.get(field_name) is not None:
            out[field_name] = section[field_name]
    out["hardConstraint"] = bool(section.get("hardConstraint"))

    constraints = _as_dict(section.get("constraints") or {}, f"{where}.constraints")
    unknown = sorted(set(constraints) - set(CONSTRAINT_CATEGORIES))
    if unknown:
        raise ValidationError(f"{where}.constraints contains unsupported categories: {', '.join(unknown)}")
    out["constraints"] = {
        category: _as_list(constraints.get(category), f"{where}.constraints.{category}")
        for category in CONSTRAINT_CATEGORIES
    }

    # destination.kind is a starting guess; reason stays empty on purpose so the author must justify
    # routing before --execution-ready (which requires a non-empty reason for every section) passes.
    # A task-bound default also seeds an empty tasks list for the author to fill with plan task ids
    # once --scaffold-tasks has populated the task roster.
    default_kind = _default_destination_kind(section)
    out["destination"] = {"kind": default_kind, "reason": ""}
    if default_kind == "task-bound":
        out["destination"]["tasks"] = []
    if out["hardConstraint"]:
        out["reread"] = _derive_reread(page, section_id)
    if "sourceAnchors" in section:
        out["sourceAnchors"] = _as_list(section.get("sourceAnchors"), f"{where}.sourceAnchors")
    if "caveats" in section:
        out["caveats"] = _as_list(section.get("caveats"), f"{where}.caveats")
    return out


def _scaffold_page(raw_page: Any, page_index: int) -> dict[str, Any]:
    where = f"selection wikiPages[{page_index}]"
    page = _as_dict(raw_page, where)
    if not any(page.get(key) for key in ("displayPath", "localPath", "wikiPath", "path")):
        raise ValidationError(f"{where} must include one of displayPath, localPath, wikiPath, or path")

    out: dict[str, Any] = {}
    for field_name in ("root", "source", "displayPath", "localPath", "wikiPath", "path", "revision"):
        if page.get(field_name) is not None:
            out[field_name] = page[field_name]
    out["documentContext"] = _as_dict(page.get("documentContext") or {}, f"{where}.documentContext")
    if "caveats" in page:
        out["caveats"] = _as_list(page.get("caveats"), f"{where}.caveats")

    raw_sections = _as_list(page.get("sections"), f"{where}.sections")
    out["sections"] = [
        _scaffold_section(out, raw_section, page_index, section_index)
        for section_index, raw_section in enumerate(raw_sections)
    ]
    return out


def _scaffold_shared_wiki(selection: dict[str, Any], pages: list[dict[str, Any]]) -> dict[str, Any] | None:
    # Record shared-wiki identity only when a github_mcp page is actually selected (mirrors the
    # contract: omit the block entirely otherwise). Identity comes from the researcher's
    # sharedWikiSource (shared_wiki_status) so execution can later detect rebinding drift.
    if not any(page.get("source") == "github_mcp" for page in pages):
        return None
    source = selection.get("sharedWikiSource")
    if not isinstance(source, dict):
        return None
    repo_url = source.get("repoUrl")
    if not isinstance(repo_url, str) or not repo_url.strip():
        return None
    shared: dict[str, Any] = {"source": "github_mcp", "repoUrl": repo_url}
    if source.get("baseBranch"):
        shared["baseBranch"] = source["baseBranch"]
    if isinstance(source.get("revision"), dict):
        shared["revision"] = source["revision"]
    return shared


def scaffold_from_selection(selection: dict[str, Any], plan_path: str | None) -> dict[str, Any]:
    """Mechanically turn a wiki-researcher selection JSON into a complete-shaped sidecar skeleton.

    Copies the researcher's page/section selection verbatim and fills everything mechanical: schema
    constants, the taskRouting block, an auto reread block for each hard section, shared-wiki identity,
    and default destination kinds (task-bound defaults also get an empty destination.tasks). The author
    then edits only the semantic routing on each section's destination (reason, kind, and the tasks list
    for task-bound) plus taskRouting.status. taskWikiRefs are intentionally empty here; --scaffold-tasks
    adds them once the plan has stable task ids.
    """
    raw_pages = _as_list(selection.get("wikiPages"), "selection.wikiPages")
    pages = [_scaffold_page(raw_page, page_index) for page_index, raw_page in enumerate(raw_pages)]

    data: dict[str, Any] = {"schemaVersion": SCHEMA_VERSION, "kind": KIND, "generatedBy": SCAFFOLD_GENERATED_BY}
    if plan_path:
        data["planPath"] = plan_path
    shared = _scaffold_shared_wiki(selection, pages)
    if shared:
        data["sharedWiki"] = shared
    data["taskRouting"] = dict(SCAFFOLD_TASK_ROUTING)
    data["wikiPages"] = pages
    data["taskWikiRefs"] = []
    data["caveats"] = _as_list(selection.get("caveats"), "selection.caveats") if "caveats" in selection else []
    return data


def scaffold_tasks(data: dict[str, Any], plan_path: Path) -> tuple[list[str], list[str]]:
    """Scaffold one taskWikiRefs entry per stable plan task (the task roster + fingerprint anchor).

    taskId/taskTitle come mechanically from the plan headings (extract_plan_tasks). Any prior
    taskFingerprint/caveats are preserved for surviving tasks so re-running after a plan edit is
    idempotent; tasks no longer in the plan are dropped and reported. taskFingerprint is never stamped
    here -- that stays --bind-fingerprints' single responsibility. Section->task routing is NOT touched
    here: it lives on each section's destination.tasks, independent of this roster.
    """
    plan_tasks = extract_plan_tasks(plan_path)
    existing: dict[str, dict[str, Any]] = {}
    for index, raw_ref in enumerate(_as_list(data.get("taskWikiRefs"), "taskWikiRefs")):
        ref = _as_dict(raw_ref, f"taskWikiRefs[{index}]")
        task_id = ref.get("taskId")
        if isinstance(task_id, str) and task_id:
            existing[task_id] = ref

    new_refs: list[dict[str, Any]] = []
    for task_id, task in plan_tasks.items():
        prev = existing.get(task_id)
        ref: dict[str, Any] = {"taskId": task_id, "taskTitle": task["title"]}
        if prev and prev.get("taskFingerprint"):
            ref["taskFingerprint"] = prev["taskFingerprint"]
        if prev and prev.get("caveats"):
            ref["caveats"] = prev["caveats"]
        new_refs.append(ref)

    dropped = sorted(set(existing) - set(plan_tasks))
    data["taskWikiRefs"] = new_refs
    return list(plan_tasks), dropped


def _write_context(path: Path, data: dict[str, Any]) -> None:
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    tmp = path.with_name(path.name + ".tmp")
    # Pin LF so the sidecar is byte-deterministic across platforms (Windows text mode
    # would otherwise translate "\n" to "\r\n" and churn against an LF-committed file).
    with tmp.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    tmp.replace(path)


def main() -> int:
    _configure_stdio()
    parser = argparse.ArgumentParser(description="Validate and render schemaVersion 4 selected wiki context JSON.")
    parser.add_argument("context_path", help="Path to docs/superpowers/plans/<plan-stem>.wiki-context.json")
    parser.add_argument("--task", action="append", default=[], help="Deprecated compatibility option; selected wiki context is not filtered by task string")
    parser.add_argument("--task-id", help="Render only wiki refs bound to the finalized plan task id, plus global refs")
    parser.add_argument("--plan-path", help="Implementation plan path used for task fingerprint preflight")
    parser.add_argument("--execution-ready", action="store_true", help="Require confirmed taskRouting and per-section destination routing suitable for execution")
    parser.add_argument("--fingerprint-preflight", action="store_true", help="Compare taskWikiRefs fingerprints against the current plan task text")
    parser.add_argument("--bind-fingerprints", action="store_true", help="Stamp taskWikiRefs taskFingerprint values from the current plan task text and write the sidecar in place (requires --plan-path)")
    parser.add_argument("--role", choices=["implementer", "reviewer"], default="implementer")
    parser.add_argument("--format", choices=["markdown"], default="markdown")
    parser.add_argument("--validate-only", action="store_true")
    parser.add_argument("--reread-list", action="store_true")
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--scaffold", metavar="SELECTION_JSON", help="Generate a sidecar skeleton from a wiki-researcher selection JSON and write it to the positional context path")
    parser.add_argument("--keep-selection", action="store_true", help="With --scaffold, keep the consumed selection JSON instead of removing it on success (for tests/debugging, or to regenerate from an edited selection)")
    parser.add_argument("--scaffold-tasks", action="store_true", help="Scaffold the taskWikiRefs roster (taskId/taskTitle) from stable plan headings into the existing sidecar, preserving any prior taskFingerprint (requires --plan-path)")
    args = parser.parse_args()

    try:
        if args.scaffold and args.scaffold_tasks:
            raise ValidationError("Run --scaffold and --scaffold-tasks in separate invocations: --scaffold builds the sidecar from a selection, --scaffold-tasks adds task routing after the plan stabilizes")
        if args.scaffold:
            selection_path = Path(args.scaffold)
            selection = _load_json(selection_path, "wiki selection")
            data = scaffold_from_selection(selection, args.plan_path)
            _validate_context(data, args.strict, execution_ready=False)
            context_path = Path(args.context_path)
            _write_context(context_path, data)
            summary = f"scaffolded wiki context with {len(data['wikiPages'])} page(s) -> {args.context_path}"
            # The selection is a transient intermediate: scaffolding is its only consumer (execution reads
            # the generated sidecar, never the selection). Remove it on success so only the plan and its
            # .wiki-context.json persist. A malformed selection raises above before this write, so a failed
            # scaffold always keeps the selection for repair. --keep-selection opts out (tests/debugging,
            # or to regenerate from an edited selection).
            if args.keep_selection:
                print(f"{summary} (kept selection {selection_path})")
            elif selection_path.resolve() == context_path.resolve():
                print(f"{summary} (selection path equals context path; not removed)")
            else:
                try:
                    selection_path.unlink()
                    print(f"{summary}; removed consumed selection {selection_path}")
                except OSError as exc:
                    print(f"Warning: scaffolded the sidecar but could not remove selection {selection_path}: {exc}", file=sys.stderr)
                    print(summary)
            return 0
        data = _load_context(Path(args.context_path))
        if args.scaffold_tasks:
            if not args.plan_path:
                raise ValidationError("--scaffold-tasks requires --plan-path")
            task_ids, dropped = scaffold_tasks(data, Path(args.plan_path))
            _validate_context(data, args.strict, execution_ready=False)
            _write_context(Path(args.context_path), data)
            for task_id in dropped:
                print(f"Warning: dropped taskWikiRefs entry no longer in plan: {task_id}", file=sys.stderr)
            print(f"scaffolded {len(task_ids)} task(s): {', '.join(task_ids)}")
            return 0
        if args.bind_fingerprints:
            if not args.plan_path:
                raise ValidationError("--bind-fingerprints requires --plan-path")
            # Validate structure but tolerate missing/placeholder fingerprints; stamping fixes them.
            _validate_context(data, args.strict, execution_ready=False)
            total, changed, task_ids = bind_fingerprints(data, Path(args.plan_path))
            # With real fingerprints stamped, confirm the result is fully execution-ready before
            # writing, so a successful bind is transactional (correct fingerprints + valid routing).
            if args.execution_ready:
                _validate_context(data, args.strict, execution_ready=True)
            _write_context(Path(args.context_path), data)
            status = f"{changed} updated" if changed else "already current"
            print(f"bound taskFingerprint for {total} task(s) ({status}): {', '.join(task_ids)}")
            return 0
        caveats = _validate_context(data, args.strict, args.execution_ready)
        if args.fingerprint_preflight:
            if not args.plan_path:
                raise ValidationError("--fingerprint-preflight requires --plan-path")
            print(fingerprint_preflight(data, Path(args.plan_path)))
            return 0
        if args.validate_only:
            # --plan-path alone cannot catch stale fingerprints in validate-only mode (format-only),
            # so when execution-ready validation is requested with a plan, run the same fingerprint
            # preflight execution uses. This closes the gap where placeholder/stale fingerprints
            # passed planning validation and only failed later at dispatch time.
            if args.execution_ready and args.plan_path:
                fingerprint_preflight(data, Path(args.plan_path))
            for caveat in caveats:
                print(f"Warning: {caveat}", file=sys.stderr)
            print("wiki context JSON is valid")
            return 0
        if args.reread_list:
            print(render_reread_list(data, args.task_id))
            return 0
        print(render_markdown(data, args.role, args.task_id))
        return 0
    except (ValidationError, FingerprintError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
