#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import json
import re

DEFAULT_IGNORED_DIR_NAMES = {"draft", "archive", "examples"}
AUTO_START = "<!-- superpower-adapter:auto:start -->"
AUTO_END = "<!-- superpower-adapter:auto:end -->"
PROJECT_WIKI_REL = Path(".superpowers") / "wiki"
SHARED_WIKI_REL = Path(".shared-superpowers") / "wiki"
PROJECT_SETTINGS_REL = Path(".superpowers") / "settings.json"
SHARED_SETTINGS_REL = Path(".shared-superpowers") / "settings.json"
WIKI_POLICY_SKIP = "skip"
WIKI_POLICY_ASK = "ask"
WIKI_POLICY_REFUSE = "refuse"
WIKI_POLICY_VALUES = {WIKI_POLICY_SKIP, WIKI_POLICY_ASK, WIKI_POLICY_REFUSE}
WIKI_OPERATION_UPDATE = "updateExistingPage"
WIKI_OPERATION_CREATE = "createNewDocument"
DEFAULT_WIKI_UPDATE_AUTHORIZATION = {
    WIKI_OPERATION_UPDATE: WIKI_POLICY_SKIP,
    WIKI_OPERATION_CREATE: WIKI_POLICY_ASK,
}
DEFAULT_SHARED_WIKI_NEUTRALITY = {
    "blockedTerms": [],
    "blockedPatterns": [],
}
ENTRY_STUB = "# Project Wiki\n\nUse this file as the entry point for project-specific wiki pages.\n\n" + AUTO_START + "\n" + AUTO_END + "\n"


@dataclass(frozen=True)
class WikiRoot:
    name: str
    path: Path
    display_path: str


@dataclass(frozen=True)
class IndexReference:
    source: Path
    raw: str
    target: Path
    kind: str


@dataclass
class WikiIndexGraph:
    wiki_root: Path
    indexes: list[Path] = field(default_factory=list)
    leaves: list[Path] = field(default_factory=list)
    directories: list[Path] = field(default_factory=list)
    missing: list[str] = field(default_factory=list)
    invalid: list[str] = field(default_factory=list)
    cycles: list[str] = field(default_factory=list)

    @property
    def files(self) -> list[Path]:
        return [*self.indexes, *self.leaves]

    @property
    def warnings(self) -> list[str]:
        return [*self.invalid, *self.missing, *self.cycles]


def repo_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in (current, *current.parents):
        if (candidate / ".superpowers").exists() or (candidate / ".shared-superpowers").exists() or (candidate / "superpowers").exists():
            return candidate
    return current


def known_wiki_roots(project_root: Path) -> list[WikiRoot]:
    project_root = project_root.resolve()
    return [
        WikiRoot("project", project_root / PROJECT_WIKI_REL, PROJECT_WIKI_REL.as_posix()),
        WikiRoot("shared", project_root / SHARED_WIKI_REL, SHARED_WIKI_REL.as_posix()),
    ]


def wiki_root_by_name(project_root: Path, name: str) -> WikiRoot:
    for root in known_wiki_roots(project_root):
        if root.name == name:
            return root
    raise ValueError(f"Unknown wiki root: {name}")


def existing_wiki_roots(project_root: Path, require_index: bool = True) -> list[WikiRoot]:
    roots: list[WikiRoot] = []
    for root in known_wiki_roots(project_root):
        if require_index:
            if (root.path / "index.md").is_file():
                roots.append(root)
        elif root.path.is_dir():
            roots.append(root)
    return roots


def select_wiki_root(project_root: Path, selector: str = "project", create: bool = False) -> WikiRoot:
    root = wiki_root_by_name(project_root, selector)
    if create:
        root.path.mkdir(parents=True, exist_ok=True)
    return root


def selected_wiki_roots(project_root: Path, selector: str = "all", require_index: bool = True) -> list[WikiRoot]:
    if selector == "all":
        return existing_wiki_roots(project_root, require_index=require_index)
    if selector in {"project", "shared"}:
        root = wiki_root_by_name(project_root, selector)
        if require_index and not (root.path / "index.md").is_file():
            return []
        if not require_index and not root.path.is_dir():
            return []
        return [root]
    raise ValueError(f"Unknown wiki root selector: {selector}")


def display_wiki_path(root: WikiRoot, file_path: Path) -> str:
    return f"{root.display_path}/{rel_posix(root.path.resolve(), file_path.resolve())}"


def wiki_settings_path(project_root: Path, root: WikiRoot) -> Path:
    if root.name == "project":
        return project_root / PROJECT_SETTINGS_REL
    if root.name == "shared":
        return project_root / SHARED_SETTINGS_REL
    raise ValueError(f"Unknown wiki root: {root.name}")


def load_wiki_settings(project_root: Path, root: WikiRoot) -> dict:
    settings_path = wiki_settings_path(project_root, root)
    if not settings_path.is_file():
        return {}

    try:
        payload = json.loads(settings_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in {settings_path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"Settings must be a JSON object: {settings_path}")

    wiki_settings = payload.get("wiki", {})
    if wiki_settings is None:
        return {}
    if not isinstance(wiki_settings, dict):
        raise ValueError(f"wiki settings must be an object in {settings_path}")
    return wiki_settings


def _read_string_list(settings_path: Path, payload: dict, key: str) -> list[str]:
    value = payload.get(key, [])
    if value is None:
        return []
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise ValueError(f"wiki.sharedNeutrality.{key} must be a string array in {settings_path}")
    return value


def load_wiki_update_authorization_policy(project_root: Path, root: WikiRoot) -> dict[str, str]:
    settings_path = wiki_settings_path(project_root, root)
    policy = dict(DEFAULT_WIKI_UPDATE_AUTHORIZATION)
    wiki_settings = load_wiki_settings(project_root, root)

    update_auth = wiki_settings.get("updateAuthorization", {})
    if update_auth is None:
        update_auth = {}
    if not isinstance(update_auth, dict):
        raise ValueError(f"wiki.updateAuthorization must be an object in {settings_path}")

    for operation in DEFAULT_WIKI_UPDATE_AUTHORIZATION:
        value = update_auth.get(operation, policy[operation])
        if value not in WIKI_POLICY_VALUES:
            allowed = ", ".join(sorted(WIKI_POLICY_VALUES))
            raise ValueError(f"Invalid wiki.updateAuthorization.{operation} in {settings_path}: {value!r}; expected one of {allowed}")
        policy[operation] = value
    return policy


def load_shared_wiki_neutrality_policy(project_root: Path, root: WikiRoot) -> dict[str, list[str]]:
    if root.name != "shared":
        return dict(DEFAULT_SHARED_WIKI_NEUTRALITY)

    settings_path = wiki_settings_path(project_root, root)
    wiki_settings = load_wiki_settings(project_root, root)
    neutrality = wiki_settings.get("sharedNeutrality", {})
    if neutrality is None:
        neutrality = {}
    if not isinstance(neutrality, dict):
        raise ValueError(f"wiki.sharedNeutrality must be an object in {settings_path}")

    policy = {
        "blockedTerms": _read_string_list(settings_path, neutrality, "blockedTerms"),
        "blockedPatterns": _read_string_list(settings_path, neutrality, "blockedPatterns"),
    }
    for pattern in policy["blockedPatterns"]:
        try:
            re.compile(pattern)
        except re.error as exc:
            raise ValueError(f"Invalid wiki.sharedNeutrality.blockedPatterns entry in {settings_path}: {pattern!r}: {exc}") from exc
    return policy


def shared_wiki_neutrality_violations(project_root: Path, root: WikiRoot, text: str, label: str) -> list[str]:
    if root.name != "shared":
        return []

    policy = load_shared_wiki_neutrality_policy(project_root, root)
    violations: list[str] = []
    for term in policy["blockedTerms"]:
        if term and term in text:
            violations.append(f"{label}: blocked term {term!r}")
    for pattern in policy["blockedPatterns"]:
        if pattern and re.search(pattern, text):
            violations.append(f"{label}: blocked pattern {pattern!r}")
    return violations


def enforce_shared_wiki_neutrality(project_root: Path, root: WikiRoot, text: str, label: str) -> None:
    violations = shared_wiki_neutrality_violations(project_root, root, text, label)
    if violations:
        details = "; ".join(violations)
        raise ValueError(f"Shared wiki requires neutral/portable content; remove system-specific identifiers before writing. {details}")


def wiki_update_operation_for_target(target_exists: bool) -> str:
    return WIKI_OPERATION_UPDATE if target_exists else WIKI_OPERATION_CREATE


def enforce_wiki_update_authorization(
    project_root: Path,
    root: WikiRoot,
    operation: str,
    *,
    authorized_update: bool = False,
    authorized_create: bool = False,
) -> None:
    policy = load_wiki_update_authorization_policy(project_root, root)
    action = policy[operation]
    if action == WIKI_POLICY_SKIP:
        return
    if action == WIKI_POLICY_REFUSE:
        raise PermissionError(f"{root.display_path} policy refuses wiki operation {operation}")

    authorized = authorized_update if operation == WIKI_OPERATION_UPDATE else authorized_create
    if not authorized:
        flag = "--authorized-update" if operation == WIKI_OPERATION_UPDATE else "--authorized-create"
        raise PermissionError(f"{root.display_path} policy requires user authorization for {operation}; rerun after approval with {flag}")


def parse_root_prefixed_wiki_path(project_root: Path, value: str) -> tuple[WikiRoot, Path] | None:
    clean = value.strip().strip("/")
    for root in known_wiki_roots(project_root):
        prefix = root.display_path.rstrip("/")
        if clean == prefix:
            return root, Path("index.md")
        if clean.startswith(prefix + "/"):
            return root, Path(clean[len(prefix) + 1:])
    return None


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def load_ignored_dir_names(wiki_root: Path) -> set[str]:
    ignored = set(DEFAULT_IGNORED_DIR_NAMES)
    ignore_file = wiki_root / ".adapter-ignore"
    if ignore_file.is_file():
        for line in ignore_file.read_text(encoding="utf-8").splitlines():
            value = line.strip()
            if not value or value.startswith("#"):
                continue
            ignored.add(value)
    return ignored


def is_ignored_directory(path: Path, ignored_dir_names: set[str]) -> bool:
    return path.name in ignored_dir_names or path.name.startswith(".")


def relevant_markdown_files(directory: Path) -> list[Path]:
    return sorted(
        path
        for path in directory.iterdir()
        if path.is_file() and path.suffix == ".md" and path.name != "index.md"
    )


def summary_from_markdown(path: Path) -> str:
    try:
        lines = read_text(path).splitlines()
    except OSError:
        return ""

    title = ""
    summary = ""
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if not title and stripped.startswith("#"):
            title = stripped.lstrip("#").strip()
            continue
        if stripped.startswith("<!--"):
            continue
        summary = stripped
        break

    if title and summary:
        return f"{title} — {summary}"
    if title:
        return title
    return summary


def has_relevant_content(directory: Path, ignored_dir_names: set[str]) -> bool:
    if relevant_markdown_files(directory):
        return True
    return any(
        has_relevant_content(child, ignored_dir_names)
        for child in directory.iterdir()
        if child.is_dir() and not is_ignored_directory(child, ignored_dir_names)
    )


def relevant_child_directories(directory: Path, ignored_dir_names: set[str]) -> list[Path]:
    return sorted(
        child
        for child in directory.iterdir()
        if child.is_dir()
        and not is_ignored_directory(child, ignored_dir_names)
        and has_relevant_content(child, ignored_dir_names)
    )


def child_directory_summary(directory: Path, ignored_dir_names: set[str]) -> str:
    leaf_files = relevant_markdown_files(directory)
    if leaf_files:
        return summary_from_markdown(leaf_files[0])

    for child in relevant_child_directories(directory, ignored_dir_names):
        summary = child_directory_summary(child, ignored_dir_names)
        if summary:
            return summary

    index_path = directory / "index.md"
    if index_path.is_file():
        return summary_from_markdown(index_path)
    return ""


def is_path_within(root: Path, target: Path) -> bool:
    try:
        target.relative_to(root)
        return True
    except ValueError:
        return False


def rel_posix(root: Path, target: Path) -> str:
    return target.relative_to(root).as_posix()


def replace_auto_section(text: str, content: str) -> str:
    if AUTO_START not in text or AUTO_END not in text:
        text = text.rstrip() + "\n\n" + AUTO_START + "\n" + AUTO_END + "\n"
    start = text.index(AUTO_START) + len(AUTO_START)
    end = text.index(AUTO_END)
    body = "\n" + content.rstrip() + "\n" if content.strip() else "\n"
    return text[:start] + body + text[end:]


def _looks_like_wiki_ref(value: str) -> bool:
    clean = value.split("#", 1)[0].strip()
    return bool(clean) and (clean.endswith("/") or clean.endswith(".md") or clean.endswith(".markdown") or clean.endswith(".mdx"))


def _candidate_refs(text: str) -> list[str]:
    refs: list[str] = []
    in_fence = False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("```") or stripped.startswith("````"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        for match in re.finditer(r"\[[^\]]+\]\(([^)]+)\)", line):
            raw = match.group(1).strip()
            if _looks_like_wiki_ref(raw):
                refs.append(raw)
        for match in re.finditer(r"`([^`]+)`", line):
            raw = match.group(1).strip()
            if _looks_like_wiki_ref(raw):
                refs.append(raw)
        match = re.match(r"^[-*]\s+([^\s`][^\s]*(?:\.md|\.markdown|\.mdx|/))\s*(?:$|[—#])", stripped)
        if match:
            raw = match.group(1).strip()
            if _looks_like_wiki_ref(raw):
                refs.append(raw)
    return list(dict.fromkeys(refs))


def _is_external_ref(raw: str) -> bool:
    lowered = raw.lower()
    return (
        not raw
        or raw.startswith("#")
        or "://" in raw
        or lowered.startswith("mailto:")
        or raw.startswith("/")
    )


def _has_hidden_part(path: Path) -> bool:
    return any(part.startswith(".") and part not in {".", ".."} for part in path.parts)


def _resolve_reference(index_path: Path, wiki_root: Path, raw: str, ignored_dir_names: set[str]) -> tuple[Path | None, str, str | None]:
    clean = raw.split("#", 1)[0].strip()
    if _is_external_ref(clean):
        return None, "invalid", f"Ignored unsupported reference from {rel_posix(wiki_root, index_path)}: {raw}"

    rel_path = Path(clean)
    if any(part == ".." for part in rel_path.parts):
        return None, "invalid", f"Rejected escaping reference from {rel_posix(wiki_root, index_path)}: {raw}"
    if _has_hidden_part(rel_path):
        return None, "invalid", f"Rejected hidden-path reference from {rel_posix(wiki_root, index_path)}: {raw}"
    if any(part in ignored_dir_names for part in rel_path.parts[:-1]):
        return None, "invalid", f"Rejected ignored-directory reference from {rel_posix(wiki_root, index_path)}: {raw}"

    candidate = (index_path.parent / rel_path).resolve()
    if not is_path_within(wiki_root.resolve(), candidate):
        return None, "invalid", f"Rejected out-of-wiki reference from {rel_posix(wiki_root, index_path)}: {raw}"

    is_directory_ref = clean.endswith("/") or (candidate.exists() and candidate.is_dir())
    if is_directory_ref:
        candidate = candidate / "index.md"
        kind = "index"
    elif candidate.name == "index.md":
        kind = "index"
    elif candidate.suffix == ".md":
        kind = "leaf"
    else:
        return None, "invalid", f"Rejected non-markdown reference from {rel_posix(wiki_root, index_path)}: {raw}"

    return candidate.resolve(), kind, None


def parse_index_references(index_path: Path, wiki_root: Path) -> list[IndexReference]:
    ignored_dir_names = load_ignored_dir_names(wiki_root)
    text = index_path.read_text(encoding="utf-8") if index_path.is_file() else ""
    references: list[IndexReference] = []
    for raw in _candidate_refs(text):
        target, kind, _ = _resolve_reference(index_path, wiki_root, raw, ignored_dir_names)
        if target is not None:
            references.append(IndexReference(index_path, raw, target, kind))
    return references


def build_wiki_index_graph(wiki_root: Path) -> WikiIndexGraph:
    graph = WikiIndexGraph(wiki_root=wiki_root.resolve())
    ignored_dir_names = load_ignored_dir_names(wiki_root)
    root_index = (wiki_root / "index.md").resolve()
    visited: set[Path] = set()
    visiting: set[Path] = set()
    seen_leaves: set[Path] = set()
    seen_dirs: set[Path] = set()

    def add_index(index_path: Path) -> None:
        if index_path in visiting:
            graph.cycles.append(f"Cycle detected at {rel_posix(wiki_root.resolve(), index_path)}")
            return
        if index_path in visited:
            return
        if not index_path.is_file():
            graph.missing.append(f"Missing index: {rel_posix(wiki_root.resolve(), index_path)}")
            return

        visiting.add(index_path)
        visited.add(index_path)
        graph.indexes.append(index_path)
        try:
            text = index_path.read_text(encoding="utf-8")
        except OSError as exc:
            graph.invalid.append(f"Could not read {rel_posix(wiki_root.resolve(), index_path)}: {exc}")
            visiting.remove(index_path)
            return

        for raw in _candidate_refs(text):
            target, kind, error = _resolve_reference(index_path, wiki_root.resolve(), raw, ignored_dir_names)
            if error:
                graph.invalid.append(error)
                continue
            if target is None:
                continue
            if kind == "index":
                directory = target.parent
                if directory not in seen_dirs:
                    seen_dirs.add(directory)
                    graph.directories.append(directory)
                if target.exists():
                    add_index(target)
                else:
                    graph.missing.append(f"Missing index referenced from {rel_posix(wiki_root.resolve(), index_path)}: {raw}")
            elif target.exists() and target.is_file():
                if target not in seen_leaves:
                    seen_leaves.add(target)
                    graph.leaves.append(target)
            else:
                graph.missing.append(f"Missing wiki page referenced from {rel_posix(wiki_root.resolve(), index_path)}: {raw}")

        visiting.remove(index_path)

    if root_index.is_file():
        add_index(root_index)
    else:
        graph.missing.append("Missing index: index.md")

    graph.indexes.sort(key=lambda path: (path != root_index, rel_posix(wiki_root.resolve(), path)))
    graph.leaves.sort(key=lambda path: rel_posix(wiki_root.resolve(), path))
    graph.directories.sort(key=lambda path: rel_posix(wiki_root.resolve(), path))
    return graph


def iter_indexed_wiki_files(wiki_root: Path, include_indexes: bool = False) -> list[Path]:
    graph = build_wiki_index_graph(wiki_root)
    return graph.files if include_indexes else graph.leaves


def is_indexed_wiki_path(wiki_root: Path, path: Path, include_indexes: bool = True) -> bool:
    target = path.resolve()
    graph = build_wiki_index_graph(wiki_root)
    candidates = graph.files if include_indexes else graph.leaves
    return target in {item.resolve() for item in candidates}


def append_index_reference(wiki_root: Path, target: Path) -> None:
    wiki_root = wiki_root.resolve()
    target = target.resolve()
    if not is_path_within(wiki_root, target):
        raise ValueError(f"Target is outside wiki root: {target}")
    if target.suffix != ".md" or target.name == "index.md":
        raise ValueError(f"Target must be a non-index markdown wiki page: {rel_posix(wiki_root, target)}")

    root_index = wiki_root / "index.md"
    if not root_index.exists():
        root_index.parent.mkdir(parents=True, exist_ok=True)
        root_index.write_text(ENTRY_STUB, encoding="utf-8")

    rel = target.relative_to(wiki_root).as_posix()
    if is_indexed_wiki_path(wiki_root, target, include_indexes=False):
        return

    text = root_index.read_text(encoding="utf-8")
    line = f"- `{rel}`"
    if line in text:
        return

    if AUTO_START in text and AUTO_END in text:
        start = text.index(AUTO_START) + len(AUTO_START)
        end = text.index(AUTO_END)
        existing = [item.rstrip() for item in text[start:end].splitlines() if item.strip()]
        existing.append(line)
        content = "\n".join(dict.fromkeys(existing))
        root_index.write_text(replace_auto_section(text, content), encoding="utf-8")
        return

    root_index.write_text(text.rstrip() + "\n\n" + AUTO_START + f"\n{line}\n" + AUTO_END + "\n", encoding="utf-8")
