#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import sys

import argparse
import json
from pathlib import Path

from wiki_common import (
    build_wiki_index_graph,
    display_wiki_path,
    repo_root,
    selected_wiki_roots,
    shared_wiki_neutrality_violations,
    wiki_root_by_name,
)
from wiki_section import list_section_ids, validate_section_markers

VALID = "valid"
WARNING = "warning"
INVALID = "invalid"
UPDATE_PREFIX = "## Update: "
REQUIRED_UPDATE_HEADERS = ["### Why", "### Rules / Contracts", "### Validation / Notes"]
def update_block_ranges(lines: list[str]) -> list[tuple[int, int]]:
    starts = [i for i, line in enumerate(lines) if line.startswith(UPDATE_PREFIX)]
    ranges: list[tuple[int, int]] = []
    for index, start in enumerate(starts):
        end = starts[index + 1] if index + 1 < len(starts) else len(lines)
        ranges.append((start, end))
    return ranges


def has_unclosed_fence(text: str) -> bool:
    open_fence: str | None = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("````"):
            fence = "````"
        elif stripped.startswith("```"):
            fence = "```"
        else:
            continue
        if open_fence is None:
            open_fence = fence
        elif stripped.startswith(open_fence):
            open_fence = None
    return open_fence is not None



def check_file(project_root: Path, root_desc, path: Path, *, leaf: bool) -> tuple[list[str], list[str]]:
    wiki_root = root_desc.path
    warnings: list[str] = []
    errors: list[str] = []
    rel = display_wiki_path(root_desc, path)
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return warnings, [f"Could not read {rel}: {exc}"]

    if not text.strip():
        warnings.append(f"Empty indexed wiki page: {rel}")
    if "<fill-me>" in text:
        warnings.append(f"Placeholder remains in {rel}: <fill-me>")
    if has_unclosed_fence(text):
        errors.append(f"Unclosed markdown fence in {rel}")
    errors.extend(shared_wiki_neutrality_violations(project_root, root_desc, text, rel))

    lines = text.splitlines()
    lines_count = len(lines)

    if leaf:
        for start, end in update_block_ranges(lines):
            block = {line.strip() for line in lines[start:end]}
            missing = [header for header in REQUIRED_UPDATE_HEADERS if header not in block]
            if missing:
                title = lines[start].strip()
                warnings.append(f"Incomplete update block in {rel} ({title}): missing {', '.join(missing)}")

    if leaf:
        marker_errors = validate_section_markers(text)
        for err in marker_errors:
            errors.append(f"Section marker error in {rel}: {err}")
        if lines_count > 100 and not list_section_ids(text):
            warnings.append(f"Leaf page over 100 lines without section markers: {rel} ({lines_count} lines)")
        section_index_path = path.parent / f"{path.stem}.index.md"
        if list_section_ids(text) and section_index_path.is_file():
            index_text = section_index_path.read_text(encoding="utf-8")
            doc_ids = set(list_section_ids(text))
            index_ids = {sid for sid in doc_ids if sid in index_text}
            missing_in_index = doc_ids - index_ids
            if missing_in_index:
                warnings.append(f"Section index stale for {rel}: sections {', '.join(sorted(missing_in_index))} not in {path.stem}.index.md")

    return warnings, errors


def check_root(project_root: Path, root_desc) -> dict:
    wiki_root = root_desc.path
    graph = build_wiki_index_graph(wiki_root)
    warnings = [f"{root_desc.display_path}: {warning}" for warning in graph.warnings]
    errors: list[str] = []
    for index in graph.indexes:
        index_warnings, index_errors = check_file(project_root, root_desc, index, leaf=False)
        warnings.extend(index_warnings)
        errors.extend(index_errors)

    for leaf in graph.leaves:
        leaf_warnings, leaf_errors = check_file(project_root, root_desc, leaf, leaf=True)
        warnings.extend(leaf_warnings)
        errors.extend(leaf_errors)

    if not graph.leaves:
        warnings.append(f"No indexed leaf wiki pages found in {root_desc.display_path}")

    status = INVALID if errors else WARNING if warnings else VALID
    return {
        "status": status,
        "root": root_desc.name,
        "wikiRoot": str(wiki_root),
        "displayPath": root_desc.display_path,
        "filesChecked": len(graph.files),
        "indexesChecked": len(graph.indexes),
        "leavesChecked": len(graph.leaves),
        "warnings": warnings,
        "errors": errors,
    }


def aggregate_status(roots: list[dict], warnings: list[str], errors: list[str]) -> str:
    if errors or any(root["status"] == INVALID for root in roots):
        return INVALID
    if warnings or any(root["status"] == WARNING for root in roots):
        return WARNING
    return VALID


def check_wiki_tree(selector: str) -> dict:
    root = repo_root(Path.cwd())
    root_descs = selected_wiki_roots(root, selector, require_index=True)
    missing_warnings: list[str] = []
    if selector in {"project", "shared"} and not root_descs:
        root_desc = wiki_root_by_name(root, selector)
        root_descs = [root_desc]
    elif selector == "all" and not root_descs:
        missing_warnings.append("No wiki indexes found under .superpowers/wiki or .shared-superpowers/wiki")

    root_results = [check_root(root, root_desc) for root_desc in root_descs]
    warnings = [*missing_warnings, *(warning for item in root_results for warning in item["warnings"])]
    errors = [error for item in root_results for error in item["errors"]]
    status = aggregate_status(root_results, missing_warnings, errors)
    project_wiki_root = root / ".superpowers" / "wiki"
    return {
        "status": status,
        "wikiRoot": str(project_wiki_root),
        "roots": root_results,
        "filesChecked": sum(item["filesChecked"] for item in root_results),
        "indexesChecked": sum(item["indexesChecked"] for item in root_results),
        "leavesChecked": sum(item["leavesChecked"] for item in root_results),
        "warnings": warnings,
        "errors": errors,
        "mechanicalOnly": True,
    }


def render_text(result: dict) -> str:
    status = result["status"]
    heading = {
        VALID: "WIKI_UPDATE_CHECK_VALID: wiki index and leaf mechanics look valid",
        WARNING: "WIKI_UPDATE_CHECK_WARN: mechanical warnings found",
        INVALID: "WIKI_UPDATE_CHECK_INVALID: mechanical errors found",
    }[status]
    lines = [heading, f"Files checked: {result['filesChecked']}"]
    if result["roots"]:
        lines.extend(["", "Roots:"])
        for root_result in result["roots"]:
            lines.append(f"- {root_result['displayPath']}: {root_result['filesChecked']} files checked")
    if result["warnings"]:
        lines.extend(["", "Warnings:"])
        lines.extend(f"- {warning}" for warning in result["warnings"])
    if result["errors"]:
        lines.extend(["", "Errors:"])
        lines.extend(f"- {error}" for error in result["errors"])
    lines.extend(["", "This is a mechanical validator only; it does not decide whether durable knowledge exists."])
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Validate project/shared wiki index and leaf mechanics.")
    parser.add_argument("--json", action="store_true", help="Emit JSON validation result.")
    parser.add_argument("--summary", default="", help="Deprecated compatibility option; ignored.")
    parser.add_argument("--changed-file", action="append", default=[], help="Deprecated compatibility option; ignored.")
    parser.add_argument("--wiki-root", choices=["project", "shared", "all"], default="project", help="Wiki root to validate")
    return parser



def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if not hasattr(stream, "reconfigure"):
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="replace", newline="\n")
        except (OSError, ValueError):
            pass

def main() -> int:
    _configure_stdio()
    args = build_parser().parse_args()
    result = check_wiki_tree(args.wiki_root)
    if args.summary or args.changed_file:
        result["warnings"].append("Deprecated semantic inputs were ignored: --summary / --changed-file")
        if result["status"] == VALID:
            result["status"] = WARNING
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(render_text(result))
    return 1 if result["status"] == INVALID else 0


if __name__ == "__main__":
    raise SystemExit(main())
