#!/usr/bin/env python3
"""Generated by superpower-adapter.

Section marker extraction for wiki documents.

Markers use HTML comments: <!-- wiki-section:section-id --> / <!-- /wiki-section:section-id -->
Section IDs are restricted to kebab-case: [a-z0-9][a-z0-9_-]*
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

SECTION_ID_PATTERN = r"[a-z0-9][a-z0-9_-]*"
DOCUMENT_OVERVIEW_LIMIT = 600
AUTO_GENERATED_INDEX_NOTICE = "Auto-generated from section markers. Do not edit manually."
# The opening marker may carry optional HTML-comment attributes after the id, currently
# just an authored one-line summary: <!-- wiki-section:id summary="…" -->. The attribute
# tail is captured (group 2) but every existing caller reads group 1 (the id) only, so
# legacy markers without attributes keep matching unchanged.
OPEN_RE = re.compile(r"^<!-- wiki-section:(" + SECTION_ID_PATTERN + r")(\s[^>]*?)?\s*-->$")
CLOSE_RE = re.compile(r"^<!-- /wiki-section:(" + SECTION_ID_PATTERN + r") -->$")
SUMMARY_ATTR_RE = re.compile(r'\bsummary="([^"]*)"')
# A discovery-card marker may also declare which execution roles the card binds to:
#   <!-- wiki-section:id summary="…" roles="review" -->
# roles is a comma-separated subset of KNOWN_BINDING_ROLES. Role binding is intrinsic to the
# skill (a review-checklist skill is review-only no matter which plan selects it), so it lives
# on the card marker — the single source of truth — and is read mechanically by the sidecar
# generator, never authored per-plan. An ABSENT attribute (and an all-roles value) both mean
# "binds to every role", so existing cards without the attribute keep matching unchanged.
ROLES_ATTR_RE = re.compile(r'\broles="([^"]*)"')
KNOWN_BINDING_ROLES = ("implement", "review")
# Catches lines that intend to be a marker but match neither OPEN_RE nor CLOSE_RE — e.g. a
# summary containing '>' truncates the comment, which would otherwise silently drop the
# whole section from parsing/indexing instead of surfacing an error.
LOOSE_MARKER_RE = re.compile(r"^<!--\s*/?wiki-section:")
FENCE_OPEN_RE = re.compile(r"^(`{3,}|~{3,})")

# Knowledge edges are only the explicit [[page#section]] form (a deliberate
# "this is a knowledge edge" signal). Plain markdown links like (path#anchor)
# are incidental prose and are NOT treated as section edges.
WIKILINK_RE = re.compile(r"\[\[([^\[\]]+)\]\]")
INLINE_CODE_RE = re.compile(r"`[^`]*`")

# Typed edges use an inline prefix: [[type: page#section]]. The colon must be
# followed by whitespace so a bare URL ([[http://...]]) or untyped link is not
# mistaken for a type. A bare [[ ]] (no recognized prefix) defaults to see-also.
KNOWN_EDGE_TYPES = ("see-also", "depends-on", "supersedes", "contradicts")
DEFAULT_EDGE_TYPE = "see-also"
EDGE_TYPE_RE = re.compile(r"^([a-z][a-z0-9-]*):\s+(.+)$")

# Page-level node type, declared in a leading YAML-ish frontmatter block:
#   ---
#   type: decision
#   ---
# A page with no frontmatter (or no type key) defaults to "constraint". This lets the
# wiki hold coding constraints AND broader project memory (domain facts, ADR decisions,
# cross-cutting guides) as first-class, retrieval-distinguishable node types.
KNOWN_PAGE_TYPES = ("constraint", "domain", "decision", "guide")
DEFAULT_PAGE_TYPE = "constraint"
FRONTMATTER_FENCE = "---"


@dataclass
class _SectionSpan:
    section_id: str
    start_line: int
    end_line: int | None = None
    children: list[_SectionSpan] = field(default_factory=list)


def _skip_fenced_blocks(lines: list[str]) -> set[int]:
    """Return set of line indices that are inside fenced code blocks."""
    inside: set[int] = set()
    fence_char: str | None = None
    fence_len: int = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if fence_char is None:
            m = FENCE_OPEN_RE.match(stripped)
            if m:
                fence_char = m.group(1)[0]
                fence_len = len(m.group(1))
                inside.add(i)
        else:
            inside.add(i)
            if stripped.startswith(fence_char * fence_len) and stripped.rstrip(fence_char) == "":
                fence_char = None
                fence_len = 0
    return inside


def _parse_spans(text: str) -> tuple[list[_SectionSpan], list[str]]:
    """Parse all section spans from text, returning top-level spans and errors."""
    lines = text.splitlines()
    fenced = _skip_fenced_blocks(lines)
    errors: list[str] = []
    stack: list[_SectionSpan] = []
    top_level: list[_SectionSpan] = []

    for i, line in enumerate(lines):
        if i in fenced:
            continue
        stripped = line.strip()
        open_m = OPEN_RE.match(stripped)
        if open_m:
            span = _SectionSpan(section_id=open_m.group(1), start_line=i)
            if stack:
                stack[-1].children.append(span)
            else:
                top_level.append(span)
            stack.append(span)
            continue
        close_m = CLOSE_RE.match(stripped)
        if close_m:
            sid = close_m.group(1)
            if not stack:
                errors.append(f"Line {i + 1}: closing marker for '{sid}' without matching open")
            elif stack[-1].section_id != sid:
                errors.append(
                    f"Line {i + 1}: closing marker for '{sid}' but expected '{stack[-1].section_id}'"
                )
            else:
                stack[-1].end_line = i
                stack.pop()
            continue
        if LOOSE_MARKER_RE.match(stripped):
            errors.append(
                f"Line {i + 1}: malformed wiki-section marker (id must be kebab-case; a "
                f'summary="…" must avoid > and stay on one line): {stripped[:80]}'
            )

    for span in stack:
        errors.append(f"Line {span.start_line + 1}: unclosed section '{span.section_id}'")

    return top_level, errors


def _collect_all(spans: list[_SectionSpan], lines: list[str]) -> dict[str, str]:
    """Recursively collect all sections (including nested) into a flat dict."""
    result: dict[str, str] = {}
    for span in spans:
        if span.end_line is None:
            continue
        content_lines = lines[span.start_line + 1 : span.end_line]
        result[span.section_id] = "\n".join(content_lines)
        result.update(_collect_all(span.children, lines))
    return result


def extract_all_sections(text: str) -> dict[str, str]:
    """Extract all sections from text, returning {section_id: content}.

    Parent sections include child markers in their content.
    Child sections return only their own content.
    """
    lines = text.splitlines()
    top_level, _ = _parse_spans(text)

    def _collect(spans: list[_SectionSpan]) -> dict[str, str]:
        result: dict[str, str] = {}
        for span in spans:
            if span.end_line is None:
                continue
            content_lines = lines[span.start_line + 1 : span.end_line]
            result[span.section_id] = "\n".join(content_lines)
            result.update(_collect(span.children))
        return result

    return _collect(top_level)


def extract_section(text: str, section_id: str) -> str | None:
    """Extract a single named section. Returns None if not found."""
    sections = extract_all_sections(text)
    return sections.get(section_id)


def extract_document_context_from_index(index_text: str) -> dict[str, object]:
    title: str | None = None
    overview_lines: list[str] = []
    caveats: list[str] = []
    in_overview = False

    for line in index_text.splitlines():
        stripped = line.strip()
        if title is None and stripped.startswith("# "):
            title = stripped.lstrip("#").strip()
            continue
        if stripped.startswith("|"):
            break
        if stripped.startswith(">"):
            value = stripped.lstrip(">").strip()
            if not value or value == AUTO_GENERATED_INDEX_NOTICE or value.startswith("Type:"):
                continue
            overview_lines.append(value)
            in_overview = True
            continue
        if in_overview:
            break

    if not title:
        caveats.append("document title missing from companion index")
    overview = " ".join(overview_lines).strip()
    if len(overview) > DOCUMENT_OVERVIEW_LIMIT:
        overview = overview[:DOCUMENT_OVERVIEW_LIMIT].rstrip() + "…"
    if not overview:
        caveats.append("document overview missing from companion index")

    return {
        "title": title,
        "overview": overview or None,
        "caveats": caveats,
    }


def list_section_ids(text: str) -> list[str]:
    """List all section IDs in document order."""
    lines = text.splitlines()
    fenced = _skip_fenced_blocks(lines)
    ids: list[str] = []
    for i, line in enumerate(lines):
        if i in fenced:
            continue
        m = OPEN_RE.match(line.strip())
        if m:
            ids.append(m.group(1))
    return ids


def validate_section_markers(text: str) -> list[str]:
    """Validate section markers, returning a list of error messages (empty = valid)."""
    _, errors = _parse_spans(text)
    return errors


def extract_section_summaries(text: str) -> dict[str, str]:
    """Map section id -> authored one-line summary from ``summary="…"`` on the open marker.

    Only markers that declare a non-empty summary attribute are returned; sections without
    one fall back to a mechanically derived description at index-generation time. Markers in
    fenced code blocks are ignored, mirroring the other section parsers.
    """
    lines = text.splitlines()
    fenced = _skip_fenced_blocks(lines)
    summaries: dict[str, str] = {}
    for i, line in enumerate(lines):
        if i in fenced:
            continue
        m = OPEN_RE.match(line.strip())
        if not m:
            continue
        attrs = m.group(2) or ""
        summary_match = SUMMARY_ATTR_RE.search(attrs)
        if summary_match:
            value = summary_match.group(1).strip()
            if value:
                summaries[m.group(1)] = value
    return summaries


def parse_binding_roles(raw: str) -> list[str]:
    """Normalize a comma-separated roles attribute into ordered, deduped known roles.

    Tokens are lowercased and trimmed; unknown or empty tokens are dropped. The result is
    ordered as KNOWN_BINDING_ROLES (implement before review) so a card serializes
    deterministically. An empty or all-roles result both mean "binds to every role".
    """
    seen = {token.strip().lower() for token in raw.split(",")}
    return [role for role in KNOWN_BINDING_ROLES if role in seen]


def extract_section_roles(text: str) -> dict[str, list[str]]:
    """Map section id -> declared binding roles from a ``roles="…"`` open-marker attribute.

    Only markers that RESTRICT to a strict subset of the known roles are returned; a section
    with no roles attribute, an empty/unrecognized one, or one covering every known role binds
    to all roles and is omitted (the filter treats omission as "no restriction"). Markers in
    fenced code blocks are ignored, mirroring the other section parsers.
    """
    lines = text.splitlines()
    fenced = _skip_fenced_blocks(lines)
    roles: dict[str, list[str]] = {}
    for i, line in enumerate(lines):
        if i in fenced:
            continue
        m = OPEN_RE.match(line.strip())
        if not m:
            continue
        attrs = m.group(2) or ""
        roles_match = ROLES_ATTR_RE.search(attrs)
        if not roles_match:
            continue
        parsed = parse_binding_roles(roles_match.group(1))
        if parsed and len(parsed) < len(KNOWN_BINDING_ROLES):
            roles[m.group(1)] = parsed
    return roles


def section_role_warnings(text: str) -> list[str]:
    """Flag any ``roles="…"`` attribute whose tokens are not all recognized binding roles.

    extract_section_roles silently treats an unrecognized roles attr as "binds to every role",
    so a typo (e.g. roles="reviewer" instead of "review") would quietly widen a card back to both
    roles. This surfaces such markers so validation can reject them.
    """
    lines = text.splitlines()
    fenced = _skip_fenced_blocks(lines)
    warnings: list[str] = []
    for i, line in enumerate(lines):
        if i in fenced:
            continue
        m = OPEN_RE.match(line.strip())
        if not m:
            continue
        roles_match = ROLES_ATTR_RE.search(m.group(2) or "")
        if not roles_match:
            continue
        tokens = [token.strip().lower() for token in roles_match.group(1).split(",") if token.strip()]
        unknown = [token for token in tokens if token not in KNOWN_BINDING_ROLES]
        if not tokens or unknown:
            warnings.append(
                f"section '{m.group(1)}' has roles=\"{roles_match.group(1)}\"; expected a non-empty "
                f"subset of {list(KNOWN_BINDING_ROLES)}"
            )
    return warnings


def _parse_wikilink(raw: str) -> tuple[str, str | None, str]:
    """Parse the inside of a [[...]] into (page, target_section_id, edge_type).

    Supports an optional typed prefix ([[type: target]]), an optional Obsidian-style
    display alias ([[target|alias]]), and an optional section anchor ([[page#section]]
    / [[page]] / [[#section]]). An empty page means a same-page link; a missing anchor
    means target_section_id is None. A bare link (no recognized "type: " prefix) gets
    edge_type "see-also"; an unrecognized prefix is returned verbatim for the caller to
    flag.
    """
    inner = raw.strip()
    type_match = EDGE_TYPE_RE.match(inner)
    if type_match:
        edge_type = type_match.group(1)
        rest = type_match.group(2).strip()
    else:
        edge_type = DEFAULT_EDGE_TYPE
        rest = inner
    target = rest.split("|", 1)[0].strip()
    page, _, section = target.partition("#")
    return page.strip(), (section.strip() or None), edge_type


def _innermost_section_at(spans: list[_SectionSpan], line: int) -> str | None:
    """Return the deepest section id whose content range strictly contains ``line``."""
    for span in spans:
        if span.end_line is None:
            continue
        if span.start_line < line < span.end_line:
            return _innermost_section_at(span.children, line) or span.section_id
    return None


def extract_page_frontmatter(text: str) -> dict[str, str]:
    """Parse a leading ``---`` frontmatter block into a flat {key: value} dict.

    Only a minimal ``key: value`` form is parsed (no nested YAML); a page without a
    leading frontmatter fence returns {}. Keys/values are stripped; values keep their
    case. This is intentionally tolerant — frontmatter is optional metadata.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != FRONTMATTER_FENCE:
        return {}
    result: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == FRONTMATTER_FENCE:
            break
        key, sep, value = line.partition(":")
        if sep:
            result[key.strip()] = value.strip()
    return result


def page_type(text: str) -> str:
    """Return the page's declared node type, or the default when absent.

    An unrecognized value is returned verbatim so callers (lint) can flag it.
    """
    declared = extract_page_frontmatter(text).get("type")
    return declared.strip().lower() if isinstance(declared, str) and declared.strip() else DEFAULT_PAGE_TYPE


def extract_section_links(text: str) -> dict[str, list[tuple[str, str | None, str]]]:
    """Map each section id to the [[page#section]] knowledge edges declared inside it.

    Each [[...]] is attributed to the innermost enclosing section (so a link in a
    child section is not double-counted on its parent). Links in fenced code blocks
    and inline code spans are ignored, and links outside any section are dropped
    (edges are section-to-section). Each edge is (page, target_section, edge_type);
    page="" denotes a same-page link.
    """
    lines = text.splitlines()
    fenced = _skip_fenced_blocks(lines)
    top_level, _ = _parse_spans(text)
    result: dict[str, list[tuple[str, str | None, str]]] = {}

    for i, line in enumerate(lines):
        if i in fenced:
            continue
        section_id = _innermost_section_at(top_level, i)
        if section_id is None:
            continue
        scrubbed = INLINE_CODE_RE.sub("", line)
        for match in WIKILINK_RE.finditer(scrubbed):
            page, target_section, edge_type = _parse_wikilink(match.group(1))
            result.setdefault(section_id, []).append((page, target_section, edge_type))

    return result
