#!/usr/bin/env python3
"""Generated by superpower-adapter.

Generate per-document section index files from wiki-section markers.

Usage:
  wiki_generate_section_index.py <wiki-file-path> [--wiki-root project|shared] [--project-root PATH]
  wiki_generate_section_index.py --all [--wiki-root project|shared|all] [--project-root PATH]

Scans section markers in wiki documents and generates companion .index.md files.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from wiki_section import (  # noqa: E402
    extract_section,
    extract_section_summaries,
    list_section_ids,
    page_type,
)
from wiki_common import (  # noqa: E402
    build_section_graph,
    build_wiki_index_graph,
    existing_wiki_roots,
    repo_root,
    select_wiki_root,
    wiki_root_from_dir,
    write_text_lf,
)

HARD_KEYWORDS = {"必须", "禁止", "MUST", "MUST NOT", "REQUIRED", "SHALL NOT"}
GENERATED_HEADER = "> Auto-generated from section markers. Do not edit manually.\n"
SECTION_GRAPH_FILE = ".graph.json"
# Stable substring of the now-removed relation-column maintenance note; used to strip
# the line from preserved headers of any index regenerated while the column existed.
LEGACY_NOTE_MARKER = "由源文档的 `[[page#section]]` 链接生成"


def _split_header_and_table(content: str) -> tuple[str, str]:
    """Split existing .index.md into preserved header and generated table."""
    lines = content.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.strip().startswith("|---"):
            split_at = max(i - 1, 0)
            return "".join(lines[:split_at]), "".join(lines[split_at:])
    return content, ""


def detect_strength(content: str) -> str:
    upper = content.upper()
    for kw in HARD_KEYWORDS:
        if kw.upper() in upper:
            return "hard"
    return "soft"


DESC_LIMIT = 140
_LIST_MARKER_RE = re.compile(r"^([-*+]|\d+[.)])\s+")
_WIKI_EDGE_RE = re.compile(r"\[\[[^\]]*\]\]")
_MD_LINK_RE = re.compile(r"\[([^\]]+)\]\([^)]*\)")
_TRAILING_SEP = "；：。，,;:、 ·-"


def _bound_desc(text: str) -> str:
    """Collapse whitespace, neutralize table-breaking ``|``, and bound to DESC_LIMIT.

    Applied to both the authored ``summary="…"`` and the mechanically derived description
    so a hand-written summary can never break the markdown table or run unboundedly long.
    """
    text = re.sub(r"\s+", " ", text).replace("|", "/").strip()
    if len(text) > DESC_LIMIT:
        text = text[:DESC_LIMIT].rstrip(_TRAILING_SEP) + "…"
    return text


def _clean_summary_fragment(text: str) -> str:
    """Strip inline knowledge edges / markdown links / list markup from one line.

    Section prose embeds ``[[page#section]]`` knowledge edges and ``[text](url)`` links;
    those are structure, not summary signal, so drop the edge markup and keep only the
    readable link text. List markers and surrounding punctuation are trimmed.
    """
    text = _LIST_MARKER_RE.sub("", text.strip())
    text = _WIKI_EDGE_RE.sub("", text)
    text = _MD_LINK_RE.sub(r"\1", text)
    return text.strip(_TRAILING_SEP).strip()


def first_description(content: str) -> str:
    """One-line section summary: the heading plus the gist of its content.

    The heading alone usually just echoes the section id (e.g. "服务端状态" for
    ``server-state-boundary``), giving the wiki-researcher almost no signal during the
    brainstorm phase where only the index table is read. So fold in the first substantive
    content lines — cleaned of edge/link markup and list bullets — up to a bounded length
    and with table-breaking ``|`` neutralized.
    """
    heading = ""
    body_parts: list[str] = []
    for raw in content.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("<!--"):
            continue
        if stripped.startswith("#"):
            text = _clean_summary_fragment(stripped.lstrip("#"))
            if not heading:
                heading = text
            elif text:
                body_parts.append(text)
            continue
        fragment = _clean_summary_fragment(stripped)
        if fragment:
            body_parts.append(fragment)

    body = "；".join(part for part in body_parts if part)
    if heading and body:
        summary = f"{heading}：{body}"
    else:
        summary = heading or body
    summary = re.sub(r"\s+", " ", summary)
    summary = re.sub(r"[；;]{2,}", "；", summary).strip(_TRAILING_SEP)
    return _bound_desc(summary) or "(empty section)"


def _with_trailing_newline(content: str) -> str:
    return content if content.endswith("\n") else content + "\n"


def generate_index(
    file_path: Path,
    existing_content: str | None = None,
) -> str | None:
    """Generate index content for a wiki file. Returns None if no markers found.

    The table carries section name, description, and constraint strength — the fields the
    wiki-researcher reads for section-level relevance. Knowledge-graph relationships are
    NOT rendered here: they live in ``.graph.json`` and are queried mechanically
    (``wiki_graph_neighbors.py`` / the shared-wiki MCP) rather than parsed from this table.
    """
    text = file_path.read_text(encoding="utf-8")
    section_ids = list_section_ids(text)
    if not section_ids:
        return None

    summaries = extract_section_summaries(text)
    table_lines = [
        "| section | 描述 | 约束强度 |",
        "|---|---|---|",
    ]

    for sid in section_ids:
        content = extract_section(text, sid)
        if content is None:
            continue
        # Prefer the author/agent-written one-line summary; fall back to a mechanical
        # description folded from the section's leading content.
        authored = summaries.get(sid)
        desc = _bound_desc(authored) if authored else first_description(content)
        strength = detect_strength(content)
        table_lines.append(f"| {sid} | {desc} | {strength} |")

    table_lines.append("")
    table_part = "\n".join(table_lines)

    if existing_content:
        header_part = _split_header_and_table(existing_content)[0]
    else:
        title_line = ""
        for line in text.splitlines():
            if line.startswith("# "):
                title_line = line.lstrip("# ").strip()
                break
        if not title_line:
            title_line = file_path.stem
        header_part = f"# {title_line} — Section Index\n\n{GENERATED_HEADER}\n"

    header_part = _reconcile_type_line(header_part, page_type(text))
    header_part = _with_trailing_newline(_strip_legacy_note_line(header_part))
    return header_part + table_part


def _reconcile_type_line(header: str, ptype: str) -> str:
    """Ensure the index header carries a single ``> Type: <ptype>`` metadata line.

    Idempotent: stale Type lines are dropped and the current one is re-inserted right
    after the auto-generated notice (or after the title). Type is a blockquote metadata
    line, like the notice, so extract_document_context_from_index skips it from overview.
    """
    kept = [line for line in header.splitlines() if not line.strip().lstrip(">").strip().startswith("Type:")]
    type_line = f"> Type: {ptype}"
    insert_at = next((i + 1 for i, line in enumerate(kept) if "Auto-generated from section markers" in line), None)
    if insert_at is None:
        insert_at = next((i + 1 for i, line in enumerate(kept) if line.startswith("# ")), 0)
    kept.insert(insert_at, type_line)
    return "\n".join(kept).rstrip() + "\n\n"


def _strip_legacy_note_line(header: str) -> str:
    """Drop the old relation-column maintenance note from a preserved header.

    The relation column was removed; any index regenerated while it existed carries a
    plain note line (see LEGACY_NOTE_MARKER) in its preserved header. Strip it so the
    header converges cleanly on regeneration. Idempotent for headers that never had one.
    """
    kept = [line for line in header.splitlines() if LEGACY_NOTE_MARKER not in line]
    return "\n".join(kept).rstrip() + "\n\n"


def index_path_for(file_path: Path) -> Path:
    return file_path.parent / f"{file_path.stem}.index.md"


def process_file(file_path: Path) -> bool:
    """Process a single file. Returns True if index was written."""
    out = index_path_for(file_path)
    existing = out.read_text(encoding="utf-8") if out.is_file() else None
    content = generate_index(file_path, existing)
    if content is None:
        return False
    write_text_lf(out, content)
    print(f"  Generated: {out.name}")
    return True


def write_section_graph(wiki_root: Path):
    """Build and persist the section graph for a wiki root; return the graph.

    The graph (nodes / edges / backlinks / dangling) is the single source of truth for
    knowledge-graph relationships, consumed by neighbor queries, update-wiki, and doctor.
    """
    graph = build_section_graph(wiki_root)
    payload = json.dumps(graph.to_payload(), indent=2, ensure_ascii=False) + "\n"
    write_text_lf(wiki_root / SECTION_GRAPH_FILE, payload)
    print(f"  Generated: {SECTION_GRAPH_FILE} ({len(graph.edges)} edge(s), {len(graph.dangling)} dangling)")
    return graph


def process_roots(roots) -> int:
    """Process every indexed leaf page under each given root. Returns count generated."""
    count = 0
    for root in roots:
        if not (root.path / "index.md").is_file():
            continue
        write_section_graph(root.path)
        graph = build_wiki_index_graph(root.path)
        for leaf in graph.leaves:
            if leaf.name == "index.md" or leaf.suffix == ".index.md":
                continue
            print(f"Scanning: {leaf.relative_to(root.path)}")
            if process_file(leaf):
                count += 1
    return count


def process_all(project_root: Path, wiki_root_selector: str, wiki_dir: Path | str | None = None) -> int:
    """Process all indexed leaf pages. Returns count of generated indexes.

    When ``wiki_dir`` is set the wiki is rooted directly at that directory
    (repo-root wiki layout) and ``wiki_root_selector`` is ignored.
    """
    if wiki_dir:
        roots = [wiki_root_from_dir(wiki_dir)]
    elif wiki_root_selector == "all":
        roots = existing_wiki_roots(project_root)
    else:
        roots = [select_wiki_root(project_root, wiki_root_selector)]
    return process_roots(roots)



def _configure_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        if not hasattr(stream, "reconfigure"):
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="replace", newline="\n")
        except (OSError, ValueError):
            pass

def main() -> None:
    _configure_stdio()
    parser = argparse.ArgumentParser(description="Generate section index files.")
    parser.add_argument("file_path", nargs="?", help="Wiki file path (relative to wiki root or absolute)")
    parser.add_argument("--all", action="store_true", help="Process all indexed leaf pages")
    parser.add_argument("--wiki-root", choices=["project", "shared", "all"], default="project")
    parser.add_argument("--project-root", default=None)
    parser.add_argument("--wiki-dir", default=None, help="Treat this directory as the wiki root directly (repo-root wiki layout); overrides --wiki-root/--project-root resolution")
    args = parser.parse_args()

    project = Path(args.wiki_dir).resolve() if args.wiki_dir else (Path(args.project_root) if args.project_root else repo_root(Path.cwd()))

    if args.all:
        count = process_all(project, args.wiki_root, wiki_dir=args.wiki_dir)
        print(f"\nGenerated {count} section index file(s).")
    elif args.file_path:
        wiki = wiki_root_from_dir(args.wiki_dir) if args.wiki_dir else select_wiki_root(project, "project" if args.wiki_root == "all" else args.wiki_root)
        file_path = Path(args.file_path)
        if not file_path.is_absolute():
            file_path = wiki.path / file_path
        if not file_path.is_file():
            print(f"Error: file not found: {file_path}", file=sys.stderr)
            sys.exit(1)
        # A single edited page can shift the whole root's graph, so rebuild the
        # root-level .graph.json before regenerating this file's index.
        write_section_graph(wiki.path)
        if not process_file(file_path):
            print("No section markers found. No index generated.")
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
