#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from wiki_common import build_wiki_index_graph, display_wiki_path, repo_root, selected_wiki_roots, summary_from_markdown


def candidate_rows(root_desc) -> list[dict[str, str]]:
    wiki_root = root_desc.path
    graph = build_wiki_index_graph(wiki_root)
    return [
        {
            "root": root_desc.name,
            "wikiRoot": str(wiki_root),
            "path": display_wiki_path(root_desc, path),
            "relativePath": path.relative_to(wiki_root).as_posix(),
            "summary": summary_from_markdown(path),
            "kind": "leaf",
        }
        for path in graph.leaves
    ]


def render_text(payload: dict) -> str:
    lines = [
        "Indexed wiki page candidates only; no target decision was made.",
        "Read relevant wiki pages and choose ownership yourself.",
    ]
    if payload["hint"]:
        lines.append(f"Hint: {payload['hint']}")
    if payload["warnings"]:
        lines.append("")
        lines.append("Warnings:")
        lines.extend(f"- {warning}" for warning in payload["warnings"])
    lines.append("")
    lines.append("Candidates:")
    if not payload["candidates"]:
        lines.append("- <none>")
    else:
        for candidate in payload["candidates"]:
            summary = f" — {candidate['summary']}" if candidate["summary"] else ""
            lines.append(f"- `{candidate['path']}`{summary}")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="List indexed leaf wiki page candidates without choosing an update target."
    )
    parser.add_argument("hint", nargs="?", default="", help="Optional context to echo for the agent; not used for scoring.")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable candidate data.")
    parser.add_argument("--wiki-root", choices=["project", "shared", "all"], default="all", help="Wiki root to list")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    root = repo_root(Path.cwd())
    roots = selected_wiki_roots(root, args.wiki_root, require_index=True)
    candidates: list[dict[str, str]] = []
    warnings: list[str] = []
    wiki_roots: list[dict[str, str]] = []
    for root_desc in roots:
        graph = build_wiki_index_graph(root_desc.path)
        wiki_roots.append({
            "root": root_desc.name,
            "wikiRoot": str(root_desc.path),
            "displayPath": root_desc.display_path,
        })
        candidates.extend(candidate_rows(root_desc))
        warnings.extend(f"{root_desc.display_path}: {warning}" for warning in graph.warnings)

    payload = {
        "decisionMade": False,
        "hint": args.hint,
        "wikiRoot": str((root / ".superpowers" / "wiki")),
        "wikiRoots": wiki_roots,
        "candidates": candidates,
        "warnings": warnings,
    }

    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        print(render_text(payload))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
