#!/usr/bin/env python3
"""Generated by superpower-adapter."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

from wiki_common import (
    build_wiki_index_graph,
    is_indexed_wiki_path,
    is_path_within,
    read_text,
    repo_root,
    summary_from_markdown,
)


def render_tree(wiki_root: Path, depth: int) -> list[str]:
    graph = build_wiki_index_graph(wiki_root)
    lines: list[str] = ["Wiki root: `.superpowers/wiki/`"]
    for path in graph.files:
        rel = path.relative_to(wiki_root).as_posix()
        display_path = f".superpowers/wiki/{rel}"
        level = len(path.relative_to(wiki_root).parts) - 1
        if level > depth:
            continue
        indent = "  " * level
        summary = summary_from_markdown(path)
        if summary:
            lines.append(f"{indent}- `{display_path}` — {summary}")
        else:
            lines.append(f"{indent}- `{display_path}`")

    for warning in graph.warnings:
        lines.append(f"- warning: {warning}")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", help="Read one indexed wiki page file relative to .superpowers/wiki")
    parser.add_argument("--category", help="Compatibility alias: read an indexed directory index relative to .superpowers/wiki")
    parser.add_argument("--tree", action="store_true", help="Render a lightweight index-driven summary tree")
    parser.add_argument("--depth", type=int, default=2, help="Maximum tree depth for --tree")
    args = parser.parse_args()

    root = repo_root(Path.cwd())
    wiki_root = root / ".superpowers" / "wiki"
    if not wiki_root.is_dir():
        print("No .superpowers/wiki directory found", file=sys.stderr)
        return 1

    if args.file:
        target = (wiki_root / args.file).resolve()
        if not is_path_within(wiki_root.resolve(), target) or not target.is_file():
            print(f"Wiki page not found: {args.file}", file=sys.stderr)
            return 1
        if not is_indexed_wiki_path(wiki_root, target, include_indexes=True):
            print(f"Wiki page is not indexed: {args.file}", file=sys.stderr)
            return 1
        print(read_text(target))
        return 0

    if args.category:
        target = (wiki_root / args.category / "index.md").resolve()
        if not is_path_within(wiki_root.resolve(), target) or not target.is_file():
            print(f"Indexed path not found: {args.category}", file=sys.stderr)
            return 1
        if not is_indexed_wiki_path(wiki_root, target, include_indexes=True):
            print(f"Wiki index is not indexed: {args.category}", file=sys.stderr)
            return 1
        print(read_text(target))
        return 0

    if args.tree:
        tree = render_tree(wiki_root, max(args.depth, 0))
        if not tree:
            print("- No wiki indexes discovered yet")
        else:
            print("\n".join(tree))
        return 0

    entry = wiki_root / "index.md"
    if not entry.is_file():
        print("Missing .superpowers/wiki/index.md", file=sys.stderr)
        return 1
    print(read_text(entry))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
